CREATE TRIGGER reservation_insert BEFORE INSERT ON records WHEN NEW.kind='reservations' AND json_extract(NEW.data,'$.status')='reserved' BEGIN
 SELECT CASE WHEN COALESCE((SELECT quantity FROM stock_balances WHERE owner=NEW.owner AND product_id=json_extract(NEW.data,'$.productId') AND warehouse=json_extract(NEW.data,'$.warehouse')),0) - COALESCE((SELECT SUM(CAST(ROUND(json_extract(data,'$.quantity')*1000) AS INTEGER)) FROM records WHERE owner=NEW.owner AND kind='reservations' AND archived=0 AND json_extract(data,'$.status')='reserved' AND json_extract(data,'$.productId')=json_extract(NEW.data,'$.productId') AND json_extract(data,'$.warehouse')=json_extract(NEW.data,'$.warehouse')),0) < CAST(ROUND(json_extract(NEW.data,'$.quantity')*1000) AS INTEGER) THEN RAISE(ABORT,'insufficient_available_stock') END;
END;
--> statement-breakpoint
CREATE TRIGGER reservation_update BEFORE UPDATE ON records WHEN NEW.kind='reservations' AND json_extract(NEW.data,'$.status')='reserved' AND NEW.archived=0 BEGIN
 SELECT CASE WHEN COALESCE((SELECT quantity FROM stock_balances WHERE owner=NEW.owner AND product_id=json_extract(NEW.data,'$.productId') AND warehouse=json_extract(NEW.data,'$.warehouse')),0) - COALESCE((SELECT SUM(CAST(ROUND(json_extract(data,'$.quantity')*1000) AS INTEGER)) FROM records WHERE owner=NEW.owner AND kind='reservations' AND archived=0 AND id!=NEW.id AND json_extract(data,'$.status')='reserved' AND json_extract(data,'$.productId')=json_extract(NEW.data,'$.productId') AND json_extract(data,'$.warehouse')=json_extract(NEW.data,'$.warehouse')),0) < CAST(ROUND(json_extract(NEW.data,'$.quantity')*1000) AS INTEGER) THEN RAISE(ABORT,'insufficient_available_stock') END;
END;
--> statement-breakpoint
CREATE TRIGGER available_stock_out BEFORE INSERT ON records WHEN NEW.kind='movements' AND json_extract(NEW.data,'$.direction')='stockOut' BEGIN
 SELECT CASE WHEN COALESCE((SELECT quantity FROM stock_balances WHERE owner=NEW.owner AND product_id=json_extract(NEW.data,'$.productId') AND warehouse=json_extract(NEW.data,'$.warehouse')),0) - COALESCE((SELECT SUM(CAST(ROUND(json_extract(data,'$.quantity')*1000) AS INTEGER)) FROM records WHERE owner=NEW.owner AND kind='reservations' AND archived=0 AND json_extract(data,'$.status')='reserved' AND json_extract(data,'$.productId')=json_extract(NEW.data,'$.productId') AND json_extract(data,'$.warehouse')=json_extract(NEW.data,'$.warehouse')),0) < CAST(ROUND(json_extract(NEW.data,'$.quantity')*1000) AS INTEGER) THEN RAISE(ABORT,'insufficient_available_stock') END;
END;
