CREATE UNIQUE INDEX uq_vehicle_keys_held ON records(owner,json_extract(data,'$.vehicleId')) WHERE kind='vehicleKeys' AND archived=0 AND json_extract(data,'$.status')='held';
--> statement-breakpoint
CREATE UNIQUE INDEX uq_withholding_reference ON records(owner,json_extract(data,'$.direction'),json_extract(data,'$.reference'),json_extract(data,'$.operation')) WHERE kind='withholdings' AND archived=0;
--> statement-breakpoint
CREATE INDEX idx_chat_conversation ON records(owner,kind,json_extract(data,'$.conversationId'),created_at);
--> statement-breakpoint
CREATE TRIGGER guard_credit_issue BEFORE UPDATE ON records WHEN NEW.kind='invoices' AND json_extract(NEW.data,'$.invoiceType')='creditNote' AND json_extract(NEW.data,'$.status')='issued' AND json_extract(OLD.data,'$.status')!='issued' BEGIN
 SELECT CASE WHEN COALESCE((SELECT SUM(json_extract(data,'$.total')) FROM records WHERE owner=NEW.owner AND kind='invoices' AND archived=0 AND id!=NEW.id AND json_extract(data,'$.invoiceType')='creditNote' AND json_extract(data,'$.status')='issued' AND json_extract(data,'$.originalId')=json_extract(NEW.data,'$.originalId')),0)+json_extract(NEW.data,'$.total')>COALESCE((SELECT json_extract(data,'$.total') FROM records WHERE id=json_extract(NEW.data,'$.originalId') AND owner=NEW.owner AND kind='invoices' AND json_extract(data,'$.status')='issued'),0) THEN RAISE(ABORT,'credit_exceeds_invoice') END;
END;
--> statement-breakpoint
CREATE TRIGGER guard_credit_insert BEFORE INSERT ON records WHEN NEW.kind='invoices' AND json_extract(NEW.data,'$.invoiceType')='creditNote' AND json_extract(NEW.data,'$.status')='issued' BEGIN
 SELECT CASE WHEN COALESCE((SELECT SUM(json_extract(data,'$.total')) FROM records WHERE owner=NEW.owner AND kind='invoices' AND archived=0 AND json_extract(data,'$.invoiceType')='creditNote' AND json_extract(data,'$.status')='issued' AND json_extract(data,'$.originalId')=json_extract(NEW.data,'$.originalId')),0)+json_extract(NEW.data,'$.total')>COALESCE((SELECT json_extract(data,'$.total') FROM records WHERE id=json_extract(NEW.data,'$.originalId') AND owner=NEW.owner AND kind='invoices' AND json_extract(data,'$.status')='issued'),0) THEN RAISE(ABORT,'credit_exceeds_invoice') END;
END;
--> statement-breakpoint
CREATE TRIGGER guard_withholding_payment BEFORE UPDATE ON records WHEN NEW.kind='withholdings' AND json_extract(NEW.data,'$.status')='validated' AND json_extract(OLD.data,'$.status')='draft' AND json_extract(NEW.data,'$.operation')='add' BEGIN
 SELECT CASE WHEN COALESCE((SELECT SUM(json_extract(data,'$.total')) FROM records WHERE owner=NEW.owner AND kind='withholdings' AND archived=0 AND id!=NEW.id AND json_extract(data,'$.status')!='draft' AND json_extract(data,'$.operation')='add' AND json_extract(data,'$.paymentId')=json_extract(NEW.data,'$.paymentId') AND NOT EXISTS(SELECT 1 FROM records c WHERE c.owner=NEW.owner AND c.kind='withholdings' AND c.archived=0 AND json_extract(c.data,'$.direction')=json_extract(NEW.data,'$.direction') AND json_extract(c.data,'$.reference')=json_extract(records.data,'$.reference') AND json_extract(c.data,'$.status')!='draft' AND json_extract(c.data,'$.operation') IN ('modify','cancel'))),0)+json_extract(NEW.data,'$.total')>COALESCE((SELECT json_extract(data,'$.amount') FROM records WHERE id=json_extract(NEW.data,'$.paymentId') AND owner=NEW.owner AND kind='payments' AND json_extract(data,'$.status')='cleared'),0) THEN RAISE(ABORT,'retention_exceeds_payment') END;
END;
