'use client';
import {Entry} from '@/lib/solar/domain';
import {amountWords} from '@/lib/solar/words';
import {Lang} from '@/lib/solar/modules';
export default function CalibratedEffect({entry,profile,lang,calibration=false}:{entry:Entry,profile?:Entry,lang:Lang,calibration?:boolean}){
 if(!profile||profile.data.instrument!==entry.data.instrument||profile.data.bank!==entry.data.bank)return <p>Profil bancaire correspondant requis / يلزم ملف البنك المطابق / Matching bank profile required</p>;
 const p=profile.data,values:Record<string,string>={...entry.data,amount:(entry.data.amount/1000).toFixed(3),words:amountWords(entry.data.amount,lang)};
 const allowed=p.status==='calibrated'||calibration;return <div className="bank-print-shell" dir={lang==='ar'?'rtl':'ltr'}><style>{`@page{size:${p.width}mm ${p.height}mm;margin:0}.bank-paper{position:relative;width:${p.width}mm;height:${p.height}mm;background:white;overflow:hidden}.bank-field{position:absolute;line-height:1.2;white-space:pre-wrap;overflow-wrap:anywhere}.bank-controls{padding:20px;font:16px sans-serif;background:#eef5fa}.calibration{background:repeating-linear-gradient(0deg,transparent,transparent 9.8mm,#dae3eb 10mm),repeating-linear-gradient(90deg,transparent,transparent 9.8mm,#dae3eb 10mm)}.bank-controls a,.bank-controls button{margin-inline-end:16px;padding:8px}@media print{html,body{margin:0!important;padding:0!important;background:white}.bank-controls{display:none}.bank-paper{margin:0;box-shadow:none;break-after:page}.bank-field{color:black}}`}</style><div className="bank-controls"><a href={`/print/${entry.id}?lang=${lang}`}>← {lang==='fr'?'Document':lang==='ar'?'الوثيقة':'Document'}</a><p>{lang==='fr'?'Sur formule originale : échelle 100 %, marges nulles, format papier du profil. Testez sur papier blanc avant utilisation.':lang==='ar'?'على الورقة الأصلية: الحجم 100٪ والهوامش صفر. اختبر أولا على ورقة بيضاء.':'On original bank stationery: 100% scale, zero margins, profile paper size. Test on plain paper first.'}</p><p>{p.name} · {p.bank} · {p.width} × {p.height} mm</p>{!allowed&&<p>{lang==='fr'?'Profil non calibré : effectuez un test et validez le profil.':lang==='ar'?'الملف غير مضبوط: اختبر ثم اعتمد الملف.':'Profile is not calibrated: test then approve the profile.'}</p>}<button disabled={!allowed} onClick={()=>window.print()}>{calibration?'Test / اختبار':'Imprimer / طباعة / Print'}</button><a href={`/print/${entry.id}?lang=${lang}&bank=1&calibration=1`}>Test calibration</a></div>{allowed&&<article className={'bank-paper '+(calibration?'calibration':'')}>{p.positions.map((position:any,i:number)=><div className="bank-field" key={i} style={{left:`${position.x+(p.offsetX??0)}mm`,top:`${position.y+(p.offsetY??0)}mm`,width:`${position.width}mm`,fontSize:`${position.fontSize}pt`}}>{values[position.key]??''}</div>)}</article>}</div>;
}
