'use client';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import QRCode from 'qrcode';
import {Moon,Sun,Bell,Send,Paperclip,ScanLine,Printer,Download,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type {WorkspaceData} from '@/lib/solar/client';
import {byKey,text,type Lang} from '@/lib/solar/modules';
import {specialViews} from '@/lib/solar/enterprise-modules';
import {dashboardReport,tunisToday} from '@/lib/solar/enterprise-domain';
import type {Entry} from '@/lib/solar/domain';
import {money} from '@/lib/solar/i18n';
import {toast} from 'sonner';
export {specialViews};
export async function enterprise(body:any){const r=await fetch('/api/enterprise',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d:any=await r.json();if(!r.ok)throw new Error(d.error);return d;}
const fail=(e:unknown)=>toast.error(e instanceof Error?e.message:String(e));
const can=(d:WorkspaceData,k:string,verb='edit')=>!d.access||d.access.admin||(verb==='add'?(d.access.add??d.access.write):verb==='delete'?(d.access.delete??d.access.write):d.access.write).includes(k);
function saveFile(name:string,body:string,type='text/plain'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
export function ThemeSwitch(){const [mode,setMode]=useState('light');useEffect(()=>{const saved=localStorage.getItem('solar-theme')??(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');setMode(saved);document.documentElement.classList.toggle('dark',saved==='dark')},[]);return <Button variant="ghost" size="icon" aria-label={mode==='dark'?'Mode clair':'Mode sombre'} onClick={()=>{const next=mode==='dark'?'light':'dark';setMode(next);localStorage.setItem('solar-theme',next);document.documentElement.classList.toggle('dark',next==='dark')}}>{mode==='dark'?<Sun size={18}/>:<Moon size={18}/>}</Button>;}
export function NotificationButton({data,onOpen}:{data:WorkspaceData,onOpen:()=>void}){return <Button variant="ghost" aria-label="Notifications personnelles" onClick={onOpen}><Bell size={18}/>{data.records.filter(r=>r.kind==='notifications'&&r.data.status==='unread').length||''}</Button>}
function Selection({label,value,onChange,items,required=true}:{label:string;value:string;onChange:(v:string)=>void;items:{id:string;name:string}[];required?:boolean}){return <label className="field"><span>{label}</span><select aria-label={label} required={required} value={value} onChange={e=>onChange(e.target.value)}><option value="">Sélectionner…</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>}
export default function EnterpriseTools({data,view,lang,online,onReload,agency,onOpen,onNew}:{data:WorkspaceData;view:string;lang:Lang;online:boolean;onReload:()=>Promise<void>;agency:string;onOpen:(e:Entry)=>void;onNew:(kind:string,preset?:any)=>void}){
 const [stamp,setStamp]=useState(''),[pollError,setPollError]=useState(false),[clock,setClock]=useState(Date.now());
 useEffect(()=>{if(!['bi','vat','vehicleKeys','conversations','notifications'].includes(view))return;let disposed=false,running=false;const refresh=async()=>{if(running||!navigator.onLine||document.hidden)return;running=true;try{await onReload();if(!disposed){setPollError(false)}}catch{if(!disposed)setPollError(true)}finally{running=false;if(!disposed)setClock(Date.now())}};void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>{disposed=true;clearInterval(timer)}},[view,onReload]);
 useEffect(()=>{if(data.generatedAt)setStamp(new Date(data.generatedAt).toLocaleTimeString())},[data.generatedAt]);
 if(data.access&&!data.access.read.includes(view))return null;
 return <>{['bi','vat','vehicleKeys','conversations','notifications'].includes(view)&&<p className="live-status"><RefreshCw size={14}/>{online?'Actualisation automatique toutes les 5 s':'Hors connexion — données conservées'}{stamp?' · '+stamp:''}{pollError||(online&&data.generatedAt&&clock-Date.parse(data.generatedAt)>15000)?' · Actualisation indisponible — données anciennes':''}</p>}
 {['bi','vat'].includes(view)&&<BI data={data} lang={lang} agency={agency} vatOnly={view==='vat'} onOpen={onOpen}/>}
 {view==='qr'&&<StockQR data={data} onOpen={onOpen}/>}
 {view==='vehicleKeys'&&<FleetKeys data={data} online={online} onReload={onReload}/>}
 {view==='notifications'&&<Notifications data={data} online={online} onReload={onReload}/>}
 {view==='conversations'&&<LiveChat data={data} online={online} onReload={onReload}/>}
 {view==='vat'&&<div className="enterprise-form">{can(data,'vatAdjustments','add')&&<Button variant="outline" onClick={()=>onNew('vatAdjustments')}>Ajouter un ajustement TVA</Button>}{data.access?.admin&&<Button variant="outline" onClick={()=>onNew('vatReturns')}>Préparer une clôture TVA</Button>}</div>}
 {view==='withholdings'&&<FiscalExports/>}
 {view==='eInvoices'&&<div className="inline-notice">Le XML TEIF est un brouillon technique. La qualification avec le XSD 1.1 TTN en vigueur, la signature par certificat et le dépôt El Fatoora doivent être réalisés auprès du prestataire agréé. Les étapes validées à l’extérieur sont enregistrées avec justificatif. Aucun dépôt fiscal automatique n’est activé.</div>}
 {view==='inventories'&&<div className="inline-notice">Le comptage est par dépôt : inclure tous les articles présents. Pour les pièces suivies individuellement, scanner et renseigner un identifiant unique par pièce. La validation compare le stock courant et refuse une modification concurrente.</div>}
 {view==='transits'&&<div className="inline-notice">Le transfert sert de BL inter-dépôts : expédier retire le stock de départ, puis confirmer la réception l’ajoute au dépôt destinataire. Imprimer le document pour accompagner le transport.</div>}
 {view==='transferOrders'&&<Button variant="outline" onClick={()=>onNew('transits')}>Créer un transfert / BL inter-dépôts</Button>}
 </>;
}
function BI({data,lang,agency,vatOnly,onOpen}:{data:WorkspaceData;lang:Lang;agency:string;vatOnly:boolean;onOpen:(e:Entry)=>void}){
 const [from,setFrom]=useState(tunisToday().slice(0,4)+'-01-01'),[to,setTo]=useState(tunisToday()),[warehouse,setWarehouse]=useState('all'),[opening,setOpening]=useState('0'),[scenario,setScenario]=useState('base'),[module,setModule]=useState('invoices');
 const report=useMemo(()=>dashboardReport(data,{from,to,agency,warehouse,opening:Math.round((Number(opening)||0)*1000),scenario}),[data,from,to,agency,warehouse,opening,scenario]);
 const labels:Record<string,string>={sales:'Chiffre d’affaires HT net des avoirs',receivables:'Créances à échéancier',overdue:'Impayés échus',netCash:'Flux encaissés − décaissés',stockValue:'Valeur du stock au coût catalogue',payrollCost:'Coût employeur validé',outputVat:'TVA collectée',inputVat:'TVA achats reçus',vatDue:'TVA indicative à rapprocher',withholdingIssued:'Retenues émises',withholdingReceived:'Retenues reçues'};
 const keys=vatOnly?['outputVat','inputVat','vatDue','withholdingIssued','withholdingReceived']:Object.keys(labels);
 const scopeRows=data.records.filter(r=>r.kind===module&&(agency==='all'||r.data.agencyId===agency||r.data.destinationAgencyId===agency)&&(!r.data.date||r.data.date>=from&&r.data.date<=to));
 const moduleChoices=Object.keys(byKey).filter(k=>data.access?.read.includes(k)&&!specialViews.has(k));
 const exportReport=()=>{const rows=[['Rapport',from,to],['Périmètre',agency,warehouse],['Indicateur','Montant TND'],...keys.map(k=>[labels[k],((report.kpis as any)[k]/1000).toFixed(3)])];saveFile('BI-'+from+'-'+to+'.csv','\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+\-@]/,' $&').replaceAll('"','""')+'"').join(';')).join('\r\n'),'text/csv;charset=utf-8')};
 return <div className="enterprise-stack"><section className="panel"><div className="panel-head"><h2>{vatOnly?'TVA & retenues à la source':'BI — pilotage de la société'}</h2><Button variant="outline" onClick={exportReport}><Download size={16}/>Exporter les indicateurs</Button></div><div className="enterprise-form"><label className="field">Du<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">Au<Input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><label className="field">Dépôt<select value={warehouse} onChange={e=>setWarehouse(e.target.value)}><option value="all">Tous les dépôts autorisés</option>{data.records.filter(r=>r.kind==='warehouses').map(r=><option key={r.id} value={r.id}>{r.data.name}</option>)}</select></label></div><p className="small-note">Les rapports couvrent uniquement les modules et dossiers autorisés. La période filtre les flux ; les soldes de stock et créances reflètent la situation courante, les prévisions incluent les échéances futures. Les ventes ne portent pas d’emplacement de stock : choisir un dépôt limite les données de stock et ses opérations.</p></section>
 <div className="metric-grid">{keys.map(k=><section className="metric" key={k}><span>{labels[k]}</span><strong>{money((report.kpis as any)[k],lang)}</strong></section>)}</div>
 {vatOnly?<section className="panel"><div className="panel-head"><h2>Pièces de rapprochement TVA</h2></div><p className="small-note">TVA sur factures émises et avoirs ; TVA achats calculée sur réceptions valorisées. L’éligibilité à déduction, les exclusions, le crédit antérieur et les ajustements fiscaux doivent être rapprochés par la comptabilité. Ce calcul ne constitue pas une déclaration déposée.</p>{report.invoices.map(r=><button className="report-link" key={r.id} onClick={()=>onOpen(r)}>{r.data.name}<strong>{money((r.data.invoiceType==='creditNote'?-1:1)*r.data.tax,lang)}</strong></button>)}{report.purchases.map(r=><button className="report-link" key={r.id} onClick={()=>onOpen(r)}>{r.data.name}<small>Réception achat</small></button>)}</section>:<>
 <div className="enterprise-grid"><section className="panel"><div className="panel-head"><h2>Balance âgée</h2></div>{report.ageing.map(b=><div className="report-link" key={b.label}>{b.label}<strong>{money(b.amount,lang)}</strong></div>)}</section><section className="panel"><div className="panel-head"><h2>Performance par agence</h2></div>{report.reportByAgency.map(r=><div className="report-link" key={r.id}>{r.name}<span>Ventes {money(r.sales,lang)} · Créances {money(r.receivables,lang)}</span></div>)}</section></div>
 <section className="panel"><div className="panel-head"><h2>Marges par projet</h2></div><div className="table-scroll"><table className="enterprise-table"><thead><tr><th>Projet</th><th>Ventes HT</th><th>Coûts affectés</th><th>Marge</th></tr></thead><tbody>{report.projectMargins.map(p=><tr key={p.id}><td><button onClick={()=>{const e=data.records.find(r=>r.id===p.id);if(e)onOpen(e)}}>{p.name}</button></td><td>{money(p.revenue,lang)}</td><td>{money(p.cost,lang)}</td><td>{money(p.margin,lang)}</td></tr>)}</tbody></table></div><p className="small-note">Coûts affectés : matériel sorti hors transferts, charges, pointages et véhicule. Les frais généraux non affectés restent à répartir.</p></section>
 <section className="panel"><div className="panel-head"><h2>Cash-flow prévisionnel</h2></div><div className="enterprise-form"><label className="field">Solde bancaire / caisse initial (TND)<Input inputMode="decimal" value={opening} onChange={e=>setOpening(e.target.value)}/></label><label className="field">Scénario<select value={scenario} onChange={e=>setScenario(e.target.value)}><option value="base">Central</option><option value="optimistic">Optimiste</option><option value="pessimistic">Prudent</option></select></label></div><div className="table-scroll"><table className="enterprise-table"><thead><tr><th>Date</th><th>Origine</th><th>Entrées</th><th>Sorties</th><th>Solde prévu</th></tr></thead><tbody>{report.cash.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.name}<small>{r.source}</small></td><td>{money(r.incoming,lang)}</td><td>{money(r.outgoing,lang)}</td><td className={r.balance<0?'negative':''}>{money(r.balance,lang)}</td></tr>)}</tbody></table></div><p className="small-note">Échéances non encaissées + prévisions du module Cash-flow, pondérées par probabilité. Une prévision portant la référence d’une échéance la remplace. Ajouter les achats, salaires, taxes et entretiens attendus pour compléter les sorties ; les commandes ne sont pas automatiquement assimilées à une dette exigible.</p></section>
 <section className="panel"><div className="panel-head"><h2>Rapports détaillés de tous les modules</h2><select aria-label="Module du rapport" value={module} onChange={e=>setModule(e.target.value)}>{moduleChoices.map(k=><option key={k} value={k}>{text(byKey[k].title,lang)}</option>)}</select></div><Button variant="outline" onClick={()=>saveFile('BI-'+module+'.json',JSON.stringify(scopeRows,null,2),'application/json')}>Exporter les détails</Button>{scopeRows.map(r=><button className="report-link" key={r.id} onClick={()=>onOpen(r)}>{r.data.name}<small>{r.data.status} · {r.data.date??r.updatedAt.slice(0,10)}</small></button>)}</section>
 </>}
 </div>;
}
function StockQR({data,onOpen}:{data:WorkspaceData;onOpen:(e:Entry)=>void}){
 const [scan,setScan]=useState(''),[product,setProduct]=useState(''),[labels,setLabels]=useState<{serial:string;image:string;value:string}[]>([]),[count,setCount]=useState(1),[result,setResult]=useState('');const input=useRef<HTMLInputElement>(null);
 const products=data.records.filter(r=>r.kind==='products'),selected=products.find(r=>r.id===product);
 const payload=(id:string,serial:string)=>'SOLU1|'+id+'|'+encodeURIComponent(serial);
 const generate=async(newPieces=false)=>{try{if(!selected)return;const serials=newPieces?Array.from({length:Math.min(100,Math.max(1,count))},()=>('SM-'+crypto.randomUUID())):data.serials.filter(s=>s.product_id===product).map(s=>s.serial);if(!serials.length){toast.info('Aucune pièce identifiée. Générer des identifiants puis les enregistrer à la réception ou à l’inventaire.');return}setLabels(await Promise.all(serials.slice(0,100).map(async serial=>{const value=payload(product,serial);return {serial,value,image:await QRCode.toDataURL(value,{errorCorrectionLevel:'M',width:190,margin:2})}})))}catch(e){fail(e)}};
 const lookup=()=>{try{const parts=scan.trim().split('|'),id=parts[0]==='SOLU1'?parts[1]:null,serial=parts[0]==='SOLU1'?decodeURIComponent(parts[2]??''):scan.trim();const p=products.find(r=>r.id===id||r.data.sku===scan.trim());const loc=data.serials.find(s=>s.serial===serial&&(!id||s.product_id===id));const target=p??products.find(r=>r.id===loc?.product_id);if(!target){setResult('Code inconnu ou hors périmètre autorisé');return}const warehouse=data.records.find(r=>r.id===loc?.warehouse),transit=data.records.find(r=>r.kind==='transits'&&r.data.status==='shipped'&&r.data.items.some((i:any)=>i.productId===target.id&&String(i.serials??'').split(/\r?\n/).includes(serial)));setResult(target.data.name+' · '+(warehouse?.data.name??(transit?'En transit · '+transit.data.name:loc?'Sortie de stock / chantier':'Référence catalogue — pièce non enregistrée')));onOpen(target)}catch{setResult('QR invalide')}};
 return <section className="panel qr-module"><div className="panel-head"><h2><ScanLine size={20}/>QR unitaires & scanner sans fil</h2></div><form className="enterprise-form" onSubmit={e=>{e.preventDefault();lookup()}}><label className="field">Scanner / référence<Input ref={input} autoComplete="off" value={scan} onChange={e=>setScan(e.target.value)} placeholder="Scanner un QR puis Entrée"/></label><Button type="submit">Rechercher</Button><Button variant="outline" type="button" onClick={()=>input.current?.focus()}>Activer la zone scanner</Button></form>{result&&<p role="status">{result}</p>}<p className="small-note">Sur chaque PC, connecter le lecteur 2D sans fil par son dongle USB ou Bluetooth en mode clavier HID ; configurer le suffixe Entrée. Le lecteur saisit dans le champ actif. L’application n’effectue pas l’appairage matériel.</p><div className="enterprise-form"><Selection label="Article" value={product} onChange={setProduct} items={products.map(r=>({id:r.id,name:r.data.name}))}/><label className="field">Nouvelles pièces (1–100)<Input type="number" min={1} max={100} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><Button variant="outline" onClick={()=>void generate(false)}>Étiquettes des pièces enregistrées</Button><Button variant="outline" onClick={()=>void generate(true)}>Générer de nouveaux identifiants</Button></div>{selected?.data.tracking!=='serialTracking'&&selected&&<p className="inline-notice">Pour tracer chaque pièce et sa position, activer le suivi unitaire avant la première réception. Un article ayant déjà du stock ne peut pas changer de suivi sans régularisation.</p>}{labels.length>0&&<><p className="small-note">Les nouveaux codes sont des étiquettes : ils entrent au stock uniquement après validation d’une réception / entrée / inventaire contenant ces identifiants.</p><Button variant="outline" onClick={()=>saveFile('identifiants-stock.txt',labels.map(l=>l.serial).join('\n'))}><Download size={16}/>Liste à saisir dans les séries de la réception</Button><Button variant="outline" onClick={()=>window.print()}><Printer size={16}/>Imprimer les QR</Button><div className="qr-labels">{labels.map(l=><figure key={l.serial}><img src={l.image} width="160" height="160" alt={'QR '+l.serial}/><figcaption>{selected?.data.sku}<br/>{l.serial}</figcaption></figure>)}</div></>}</section>;
}
function FleetKeys({data,online,onReload}:{data:WorkspaceData;online:boolean;onReload:()=>Promise<void>}){
 const [vehicle,setVehicle]=useState(''),[employee,setEmployee]=useState(''),[purpose,setPurpose]=useState(''),[km,setKm]=useState('0'),[condition,setCondition]=useState(''),[busy,setBusy]=useState(false);const rows=data.records.filter(r=>r.kind==='vehicles');
 return <section className="panel"><div className="panel-head"><h2>Qui détient les clés maintenant ?</h2></div>{rows.map(r=><div className="report-link" key={r.id}><strong>{r.data.registration}</strong><span>{r.data.keyHolderId?data.records.find(e=>e.id===r.data.keyHolderId)?.data.name??'Détenteur hors périmètre':'Clés au parc'}<small>{r.data.keyUpdatedAt?new Date(r.data.keyUpdatedAt).toLocaleString():''}</small></span></div>)}{can(data,'vehicleKeys','add')&&<form className="enterprise-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await enterprise({action:'handKeys',vehicleId:vehicle,employeeId:employee,purpose,startKm:Number(km),conditionOut:condition});await onReload();toast.success('Remise des clés enregistrée');setVehicle('');setPurpose('')}catch(e){fail(e)}finally{setBusy(false)}}}><Selection label="Véhicule disponible" value={vehicle} onChange={id=>{setVehicle(id);setKm(String(rows.find(r=>r.id===id)?.data.odometer??0))}} items={rows.filter(r=>r.data.status==='active'&&!r.data.keyHolderId).map(r=>({id:r.id,name:r.data.registration}))}/><Selection label="Employé détenteur" value={employee} onChange={setEmployee} items={data.records.filter(r=>r.kind==='employees'&&r.data.status==='active').map(r=>({id:r.id,name:r.data.name}))}/><label className="field">Mission / motif<Input required value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><label className="field">Compteur départ<Input required type="number" min={0} value={km} onChange={e=>setKm(e.target.value)}/></label><label className="field">État / accessoires<Input value={condition} onChange={e=>setCondition(e.target.value)}/></label><Button disabled={!online||busy} type="submit">Remettre les clés</Button></form>}</section>;
}
function Notifications({data,online,onReload}:{data:WorkspaceData;online:boolean;onReload:()=>Promise<void>}){
 const [recipient,setRecipient]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 return <section className="panel"><div className="panel-head"><h2>Mes notifications</h2></div>{data.records.filter(r=>r.kind==='notifications').map(r=><div className="notification-card" key={r.id}><strong>{r.data.name}</strong><p>{r.data.message}</p><small>{new Date(r.createdAt).toLocaleString()}</small>{r.data.status==='unread'&&<Button disabled={!online||busy} variant="outline" onClick={async()=>{setBusy(true);try{await enterprise({action:'acknowledge',id:r.id,revision:r.revision});await onReload()}catch(e){fail(e)}finally{setBusy(false)}}}>Marquer comme lue</Button>}</div>)}{data.access?.admin&&<form className="enterprise-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await enterprise({action:'notify',recipientEmail:recipient,message});await onReload();setMessage('')}catch(e){fail(e)}finally{setBusy(false)}}}><Selection label="Notifier un salarié" value={recipient} onChange={setRecipient} items={data.records.filter(r=>r.kind==='users'&&r.data.status==='active').map(r=>({id:r.data.email,name:r.data.name}))}/><label className="field">Notification<Input required value={message} onChange={e=>setMessage(e.target.value)} maxLength={4000}/></label><Button disabled={!online||busy} type="submit">Créer la notification</Button></form>}</section>;
}
function LiveChat({data,online,onReload}:{data:WorkspaceData;online:boolean;onReload:()=>Promise<void>}){
 const [conversation,setConversation]=useState(''),[body,setBody]=useState(''),[name,setName]=useState(''),[emails,setEmails]=useState(''),[directory,setDirectory]=useState<string[]>([]),[busy,setBusy]=useState(false),[pending,setPending]=useState<{id:string;body:string;chat:string}|null>(null);
 const chats=data.records.filter(r=>r.kind==='conversations');const current=chats.find(r=>r.id===conversation);const bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{fetch('/api/enterprise?directory=1',{cache:'no-store'}).then(async r=>{if(r.ok)setDirectory((await r.json() as any).emails??[])}).catch(()=>{})},[]);
 const messages=data.records.filter(r=>r.kind==='messages'&&r.data.conversationId===conversation).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id));
 useEffect(()=>{bottom.current?.scrollIntoView({block:'nearest'})},[conversation,messages.length]);
 const attach=async(file:File,messageId:string)=>{const form=new FormData();form.append('file',file);form.append('recordId',messageId);const r=await fetch('/api/files',{method:'POST',body:form}),result:any=await r.json();if(!r.ok)throw new Error(result.error);};
 return <div className="chat-grid"><section className="panel"><div className="panel-head"><h2>Conversations privées</h2></div>{chats.map(r=><Button key={r.id} variant={r.id===conversation?'default':'ghost'} className="chat-choice" onClick={()=>setConversation(r.id)}>{r.data.name}</Button>)}{can(data,'conversations','add')&&<form className="enterprise-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const result=await enterprise({action:'createConversation',name,emails:emails.split(/[;,\s]+/).filter(Boolean)});await onReload();setConversation(result.id);setName('');setEmails('')}catch(e){fail(e)}finally{setBusy(false)}}}><label className="field">Nouvelle conversation<Input required value={name} onChange={e=>setName(e.target.value)} maxLength={200}/></label><label className="field">Participants (e-mails séparés par virgule)<Input list="chat-directory" value={emails} onChange={e=>setEmails(e.target.value)} required/><datalist id="chat-directory">{directory.map(email=><option key={email} value={email}/>)}</datalist></label><Button disabled={!online||busy} type="submit">Créer</Button></form>}</section><section className="panel"><div className="panel-head"><h2>{current?.data.name??'Choisir une conversation'}</h2></div>{current&&<><p className="small-note">{current.data.members.map((r:any)=>r.email).join(', ')}</p><div className="chat-messages" aria-live="polite">{messages.map(r=><article className="chat-bubble" key={r.id}><strong>{r.data.senderEmail}</strong><p>{r.data.message}</p><small>{new Date(r.createdAt).toLocaleString()}</small>{data.files.filter(f=>f.record_id===r.id).map(f=><a key={f.id} href={'/api/files?id='+f.id}><Paperclip size={14}/>{f.filename}</a>)}{r.data.actorId===data.access?.actor&&can(data,'messages','add')&&<label className="chat-attach">Ajouter une pièce jointe (3 Mo)<input type="file" disabled={!online||busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{await attach(file,r.id);await onReload()}catch(e){fail(e)}finally{setBusy(false);e.target.value=''}}}/></label>}</article>)}<div ref={bottom}/></div>{can(data,'messages','add')&&<form className="enterprise-form" onSubmit={async e=>{e.preventDefault();setBusy(true);const send=pending?.body===body&&pending.chat===conversation?pending:{id:crypto.randomUUID(),body,chat:conversation};setPending(send);try{await enterprise({action:'sendMessage',conversationId:send.chat,message:send.body,requestId:send.id});setBody('');setPending(null);await onReload()}catch(e){fail(e)}finally{setBusy(false)}}}><label className="field">Message<textarea required maxLength={4000} value={body} onChange={e=>setBody(e.target.value)} rows={3}/></label><Button type="submit" disabled={!online||busy||!body.trim()}><Send size={16}/>Envoyer</Button></form>}</>}</section></div>;
}
function FiscalExports(){const [period,setPeriod]=useState(tunisToday().slice(0,7)),[act,setAct]=useState('0');return <section className="panel"><div className="panel-head"><h2>Export XML TEJ — XSD septembre 2026</h2></div><div className="enterprise-form"><label className="field">Mois des paiements<Input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><label className="field">Acte<select value={act} onChange={e=>setAct(e.target.value)}><option value="0">Déclaration initiale</option><option value="1">Rectificative</option></select></label><Button variant="outline" onClick={async()=>{try{const r=await fetch(`/api/enterprise?tej=1&period=${period}&act=${act}`);if(!r.ok)throw new Error((await r.json() as any).error);const cd=r.headers.get('content-disposition')??'',name=cd.match(/filename="([^"]+)"/)?.[1]??'TEJ.xml';saveFile(name,await r.text(),'application/xml')}catch(e){fail(e)}}}>Valider les XSD et télécharger</Button></div><p className="small-note">Retenues émises uniquement, validées et payées durant le mois sélectionné. Les montants sont en millimes. L’export validé doit être déposé et accepté sur TEJ. L’archive officielle contient une balise fermante dupliquée : seule cette erreur de syntaxe est corrigée dans la copie utilisée pour validation, les fichiers originaux sont conservés. Le certificat reçu documente une retenue opérée par un client. Le paiement représente le règlement brut ; le BI déduit la retenue pour obtenir le flux bancaire net.</p></section>}
export function EnterpriseActions({entry,data,online,onReload,onNew,lang}:{entry:Entry;data:WorkspaceData;lang:Lang;online:boolean;onReload:()=>Promise<void>;onNew:(kind:string,preset?:any)=>void}){
 const [busy,setBusy]=useState(false),[endKm,setEndKm]=useState(''),[condition,setCondition]=useState(''),[status,setStatus]=useState('prepared'),[file,setFile]=useState(''),[reference,setReference]=useState('');
 const execute=async(action:string,extra:any={})=>{setBusy(true);try{await enterprise({action,id:entry.id,revision:entry.revision,...extra});await onReload();toast.success('Opération enregistrée')}catch(e){fail(e)}finally{setBusy(false)}};
 const writable=can(data,entry.kind),d=entry.data;const button=(label:string,action:string)=><Button disabled={!online||busy} variant="outline" onClick={()=>void execute(action)}>{label}</Button>;
 return <div className="enterprise-actions">
 {entry.kind==='exitNotes'&&d.status==='draft'&&writable&&button('Valider le bon de sortie','postExit')}
 {entry.kind==='clientTransfers'&&d.status==='draft'&&writable&&button('Transférer le dossier','transferClient')}
 {entry.kind==='maintenanceJobs'&&d.status==='draft'&&writable&&button('Valider l’intervention et les échéances','completeMaintenance')}
 {entry.kind==='vatReturns'&&d.status==='draft'&&data.access?.admin&&button('Valider le rapprochement TVA','validateVatReturn')}
 {entry.kind==='vatReturns'&&d.snapshot&&<section className="inline-notice"><strong>État validé</strong><p>Collectée : {money(d.snapshot.outputVat,lang)} · Achats : {money(d.snapshot.inputVat,lang)} · Ajustements : {money(d.snapshot.adjustmentTotal,lang)} · Crédit antérieur : {money(d.snapshot.previousCredit,lang)}</p><p>À payer : {money(d.snapshot.payable,lang)} · Crédit à reporter : {money(d.snapshot.credit,lang)}</p><Button variant="outline" onClick={()=>saveFile('TVA-'+entry.id+'.json',JSON.stringify(d,null,2),'application/json')}>Exporter le rapprochement et ses références</Button><p>Validation interne. Joindre le justificatif du dépôt réalisé à l’extérieur.</p></section>}
 {entry.kind==='withholdings'&&d.status==='draft'&&writable&&button('Valider les calculs de retenue','issueWithholding')}
 {entry.kind==='invoices'&&d.invoiceType==='creditNote'&&d.status==='issued'&&!d.appliedAt&&writable&&button('Imputer l’avoir sur les échéances non payées','applyCredit')}
 {entry.kind==='invoices'&&d.status==='issued'&&can(data,'eInvoices','add')&&button('Préparer le dossier El Fatoora','createEInvoice')}
 {entry.kind==='salesOrders'&&d.status==='confirmed'&&<><Button variant="outline" disabled={!online||!can(data,'deliveryNotes','add')} onClick={()=>onNew('deliveryNotes',{name:'BL · '+d.name,clientId:d.clientId,projectId:d.projectId,salesOrderId:entry.id,items:d.items,agencyId:d.agencyId,date:tunisToday(),status:'draft'})}>Créer un BL client</Button><Button variant="outline" disabled={!online||!can(data,'invoices','add')} onClick={()=>onNew('invoices',{name:'FAC · '+d.name,clientId:d.clientId,projectId:d.projectId,agencyId:d.agencyId,date:tunisToday(),dueDate:tunisToday(),invoiceType:'invoice',lines:d.items.map((i:any)=>({productId:i.productId,description:data.records.find(r=>r.id===i.productId)?.data.name??i.productId,quantity:i.quantity,price:i.price??0,tax:i.tax??0})),discount:d.discount,stamp:d.stamp,status:'draft'})}>Créer la facture</Button></>}
 {entry.kind==='transferOrders'&&d.status==='approved'&&<Button variant="outline" disabled={!online||!can(data,'transits','add')} onClick={()=>onNew('transits',{name:'BL dépôt · '+d.name,from:d.from,to:d.to,date:tunisToday(),transferOrderId:entry.id,items:d.items,agencyId:d.agencyId,status:'draft'})}>Créer le transfert / BL</Button>}
 {entry.kind==='clients'&&can(data,'clientTransfers','add')&&<Button variant="outline" disabled={!online} onClick={()=>onNew('clientTransfers',{name:'Transfert · '+d.name,clientId:entry.id,agencyId:d.agencyId,date:tunisToday(),status:'draft'})}>Transférer vers une agence</Button>}
 {entry.kind==='vehicleKeys'&&d.status==='held'&&writable&&<form className="enterprise-stack" onSubmit={e=>{e.preventDefault();void execute('returnKeys',{endKm:Number(endKm),conditionIn:condition})}}><label className="field">Compteur retour<Input type="number" min={d.startKm??0} required value={endKm} onChange={e=>setEndKm(e.target.value)}/></label><label className="field">État / accessoires au retour<Input required value={condition} onChange={e=>setCondition(e.target.value)}/></label><Button disabled={!online||busy}>Restituer les clés</Button></form>}
 {['withholdings','vatReturns'].includes(entry.kind)&&d.status==='validated'&&writable&&<form className="enterprise-stack" onSubmit={e=>{e.preventDefault();void execute('fiscalSubmission',{fileId:file,reference})}}><Selection label="Accusé du dépôt réalisé à l’extérieur" value={file} onChange={setFile} items={data.files.filter(f=>f.record_id===entry.id).map(f=>({id:f.id,name:f.filename}))}/><label className="field">Référence du dépôt<Input required value={reference} onChange={e=>setReference(e.target.value)}/></label><Button disabled={!online||busy}>Enregistrer le dépôt et son justificatif</Button></form>}
 {d.submissionReference&&<p>Dépôt enregistré : {d.submissionReference} · {d.submittedAt}</p>}
 {entry.kind==='eInvoices'&&<><a href={'/api/enterprise?teif='+d.invoiceId}>Télécharger le XML TEIF brouillon (non validé)</a>{data.access?.admin&&<form className="enterprise-stack" onSubmit={e=>{e.preventDefault();void execute('eInvoiceEvidence',{status,fileId:file,reference})}}><label className="field">Étape réalisée à l’extérieur<select value={status} onChange={e=>setStatus(e.target.value)}><option value="prepared">Qualification du XML</option><option value="signed">Signature électronique</option><option value="submitted">Dépôt TTN</option><option value="accepted">Acceptation TTN</option><option value="rejected">Rejet TTN</option></select></label><Selection label="Justificatif joint au dossier" value={file} onChange={setFile} items={data.files.filter(f=>f.record_id===entry.id).map(f=>({id:f.id,name:f.filename}))}/><label className="field">Référence du rapport / accusé<Input required value={reference} onChange={e=>setReference(e.target.value)}/></label><Button disabled={!online||busy}>Enregistrer l’étape et son justificatif</Button></form>}</>}
 </div>;
}
