'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,Star,ChevronDown,ArrowUpRight,LayoutGrid,LayoutDashboard,Files,History,Settings2} from 'lucide-react';
import {SidebarContent,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,useSidebar} from '@/components/ui/sidebar';
import {byKey,text,type Lang} from '@/lib/solar/modules';
import {navigationSections,sectionOf,visibleNavigation,moduleMatches} from '@/lib/solar/navigation';
import {t} from '@/lib/solar/i18n';
const tr=(lang:Lang,fr:string,ar:string,en:string)=>text([fr,ar,en],lang);
export default function ModuleNavigation({view,lang,actor,read,admin,counts,onNavigate}:{view:string;lang:Lang;actor:string;read?:string[];admin:boolean;counts:Map<string,number>;onNavigate:(key:string)=>void}){
 const [query,setQuery]=useState(''),[expanded,setExpanded]=useState(['daily']),[favorites,setFavorites]=useState<string[]>([]);
 const {isMobile,setOpenMobile}=useSidebar();const available=useMemo(()=>visibleNavigation(read),[read]);
// Hydrate browser preferences after SSR, without changing server markup.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('solar-favorites-'+actor)??'[]');if(Array.isArray(saved))setFavorites(saved.filter(k=>typeof k==='string'&&byKey[k]));}catch{}},[actor]);
 const navigate=(key:string)=>{setQuery('');onNavigate(key);if(isMobile)setOpenMobile(false)};
 const favorite=(key:string)=>{const next=favorites.includes(key)?favorites.filter(k=>k!==key):[...favorites,key];setFavorites(next);localStorage.setItem('solar-favorites-'+actor,JSON.stringify(next));};
 const row=(key:string)=>{const m=byKey[key];return <SidebarMenuItem key={key} className="module-nav-row"><SidebarMenuButton isActive={view===key} onClick={()=>navigate(key)} title={text(m.title,lang)}><span className="module-nav-dot"/><span>{text(m.title,lang)}</span>{!!counts.get(key)&&<small className="nav-count">{counts.get(key)}</small>}</SidebarMenuButton><button className="nav-favorite" aria-label={tr(lang,'Favori : ','مفضل: ','Favorite: ')+text(m.title,lang)} aria-pressed={favorites.includes(key)} onClick={()=>favorite(key)}><Star size={13} fill={favorites.includes(key)?'currentColor':'none'}/></button></SidebarMenuItem>};
 return <SidebarContent><div className="nav-search"><Search size={15}/><input aria-label={tr(lang,'Rechercher un module','البحث عن وحدة','Find a module')} value={query} onChange={e=>setQuery(e.target.value)} placeholder={tr(lang,'Rechercher un module…','البحث عن وحدة…','Find a module…')}/>{query&&<button aria-label={tr(lang,'Effacer','مسح','Clear')} onClick={()=>setQuery('')}>×</button>}</div><SidebarGroup><SidebarMenu><SidebarMenuItem><SidebarMenuButton isActive={view==='dashboard'} onClick={()=>navigate('dashboard')}><LayoutDashboard size={18}/>{t('dashboard',lang)}</SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton isActive={view==='modules'} onClick={()=>navigate('modules')}><LayoutGrid size={18}/>{tr(lang,'Tous les modules','كل الوحدات','All modules')}</SidebarMenuButton></SidebarMenuItem></SidebarMenu></SidebarGroup>
 {!query&&favorites.some(k=>available.some(m=>m.key===k))&&<SidebarGroup><SidebarGroupLabel>{tr(lang,'Mes favoris','المفضلة','Favorites')}</SidebarGroupLabel><SidebarMenu>{favorites.filter(k=>available.some(m=>m.key===k)).map(row)}</SidebarMenu></SidebarGroup>}
 {navigationSections.map(section=>{const list=available.filter(m=>sectionOf(m)===section.key&&moduleMatches(m,query));if(!list.length)return null;const open=!!query||expanded.includes(section.key)||list.some(m=>m.key===view);return <SidebarGroup key={section.key}><SidebarGroupLabel asChild><button className="nav-group" aria-expanded={open} onClick={()=>setExpanded(old=>old.includes(section.key)?old.filter(k=>k!==section.key):[...old,section.key])}>{text(section.title,lang)}<ChevronDown size={14} className={open?'rotated':''}/></button></SidebarGroupLabel>{open&&<SidebarMenu>{list.map(m=>row(m.key))}</SidebarMenu>}</SidebarGroup>})}
 {query&&!available.some(m=>moduleMatches(m,query))&&<p className="nav-no-result">{tr(lang,'Aucun module accessible.','لا توجد وحدة متاحة.','No accessible modules.')}</p>}
 <SidebarGroup><SidebarMenu>{[{key:'documents',icon:Files},{key:'audit',icon:History},...(admin?[{key:'settings',icon:Settings2}]:[])].map(({key,icon:Icon})=><SidebarMenuItem key={key}><SidebarMenuButton isActive={view===key} onClick={()=>navigate(key)}><Icon size={18}/>{t(key,lang)}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent>;
}
export function ModuleDirectory({lang,read,counts,onNavigate}:{lang:Lang;read?:string[];counts:Map<string,number>;onNavigate:(key:string)=>void}){
 const [query,setQuery]=useState('');const available=visibleNavigation(read);
 return <div className="module-directory"><label className="directory-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label={tr(lang,'Filtrer les modules','تصفية الوحدات','Filter modules')} placeholder={tr(lang,'Trouver un module ou une activité…','البحث عن وحدة أو نشاط…','Find a module or activity…')}/></label><div className="directory-grid">{navigationSections.map(section=>{const list=available.filter(m=>sectionOf(m)===section.key&&moduleMatches(m,query));return !!list.length&&<section className="panel directory-section" key={section.key}><h2>{text(section.title,lang)}</h2><p>{text(section.description,lang)}</p><div>{list.map(m=><button key={m.key} onClick={()=>onNavigate(m.key)}><span>{text(m.title,lang)}</span>{!!counts.get(m.key)&&<small>{counts.get(m.key)}</small>}<ArrowUpRight size={16}/></button>)}</div></section>})}</div>{!available.some(m=>moduleMatches(m,query))&&<p>{tr(lang,'Aucun module pour cette recherche.','لا نتائج لهذا البحث.','No modules match this search.')}</p>}</div>;
}
