'use client';
import {useState} from 'react';
import type {WorkspaceData} from '@/lib/solar/client';
import type {Entry} from '@/lib/solar/domain';
import {type Lang,text} from '@/lib/solar/modules';
import type {StegChallenge} from '@/lib/solar/steg-connector-domain';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
async function connectorRequest(body:any){const response=await fetch('/api/steg-connectors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result:any=await response.json();if(!response.ok)throw new Error(result.error);return result;}
const labels:Record<string,[string,string,string]>={steg_integration_required:['La passerelle STEG doit être configurée sur le serveur pour permettre la connexion et le CAPTCHA interactif.','يجب تهيئة بوابة الستاغ على الخادم للربط واختبار التحقق.','Configure the server STEG bridge for login and interactive CAPTCHA.'],steg_connector_required:['Configurez un seul connecteur actif pour ce site.','هيّئ ربطًا نشطًا واحدًا لهذا الموقع.','Configure exactly one active connector for this site.'],steg_consent_required:['Joignez le consentement du client à sa fiche site et renseignez sa date de validité.','أرفق موافقة الحريف بالموقع وحدد صلاحيتها.','Attach customer consent to the site and set its validity.'],steg_captcha_expired:['Le CAPTCHA a expiré. Relancez la vérification.','انتهت صلاحية التحقق. ابدأ من جديد.','CAPTCHA expired. Start a new check.'],invalid_provider_response:['Réponse STEG incomplète ou non reconnue. Aucun paiement n’a été déclaré vérifié.','إجابة غير مكتملة. لم يتم اعتماد حالة الخلاص.','Incomplete or unrecognized provider response. No payment status was verified.']};
const errorLabel=(e:unknown,lang:Lang)=>{const code=e instanceof Error?e.message:String(e);return labels[code]?text(labels[code],lang):code;};
export function StegVerification({project,lang,online,onVerified}:{project:Entry,lang:Lang,online:boolean,onVerified:(id:string)=>Promise<void>}){
 const [challenge,setChallenge]=useState<StegChallenge|null>(null),[answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const run=async(action:'start'|'resume')=>{setBusy(true);setError('');try{const r=await connectorRequest({action,projectId:project.id,...(action==='resume'?{sessionId:challenge?.sessionId,answer}:{})});setAnswer('');if(r.status==='captcha_required')setChallenge(r);else {setChallenge(null);await onVerified(r.id);}}catch(e){setError(errorLabel(e,lang));if(action==='resume')setChallenge(null);}finally{setBusy(false)}};
 return <div className="technical-card"><h3>{text(['Vérification STEG depuis le logiciel','التحقق من الستاغ من البرنامج','Check STEG from the application'],lang)}</h3><p>{text(['Le client résout le CAPTCHA demandé par le portail. Le solde est vérifié uniquement après une réponse complète de la session autorisée.','يحل الحريف اختبار التحقق. يعتمد الرصيد بعد إجابة كاملة من الجلسة المرخصة فقط.','The customer completes the portal CAPTCHA. Balance is verified only from a complete authorized session response.'],lang)}</p><Button disabled={busy||!online} onClick={()=>void run('start')}>{text(['Vérifier chez STEG','التحقق لدى الستاغ','Check with STEG'],lang)}</Button>{error&&<p role="alert" className="form-error">{error}</p>}
 <Dialog open={!!challenge} onOpenChange={open=>{if(!open&&!busy){setChallenge(null);setAnswer('')}}}><DialogContent className="steg-captcha-dialog"><DialogHeader><DialogTitle>{text(['Validation CAPTCHA par le client','اختبار التحقق بواسطة الحريف','Customer CAPTCHA verification'],lang)}</DialogTitle><DialogDescription>{challenge?.challenge.prompt}</DialogDescription></DialogHeader>{challenge&&<><p>{text(['Session valable jusqu’à','الجلسة صالحة إلى','Session expires at'],lang)} {new Date(challenge.expiresAt).toLocaleTimeString(lang==='ar'?'ar-TN':'fr-TN')}</p>{challenge.challenge.kind==='image'?<form onSubmit={e=>{e.preventDefault();void run('resume')}}><img src={challenge.challenge.image} alt={text(['Image CAPTCHA fournie par le portail','صورة التحقق من البوابة','Portal CAPTCHA challenge'],lang)} className="captcha-image"/><label className="field"><span>{text(['Code affiché','الرمز الظاهر','Displayed code'],lang)}</span><Input value={answer} autoComplete="off" autoFocus required maxLength={500} onChange={e=>setAnswer(e.target.value)}/></label><Button type="submit" disabled={busy||!online}>{text(['Valider et reprendre','تأكيد ومواصلة','Submit and continue'],lang)}</Button></form>:<><iframe title="STEG — CAPTCHA interactif" src={challenge.challenge.url} referrerPolicy="no-referrer" sandbox="allow-scripts allow-forms allow-same-origin" className="captcha-frame"/><p>{text(['Terminez le CAPTCHA dans cette fenêtre, puis reprenez. Si le portail refuse l’affichage intégré, ouvrez la même session sécurisée.','أكمل التحقق في هذه النافذة ثم واصل. إذا منع العرض المدمج افتح نفس الجلسة الآمنة.','Complete the CAPTCHA above, then continue. If embedding is blocked, open the same secure session.'],lang)}</p><a href={challenge.challenge.url} target="_blank" rel="noopener noreferrer">{text(['Ouvrir la session CAPTCHA','فتح جلسة التحقق','Open CAPTCHA session'],lang)}</a><Button disabled={busy||!online} onClick={()=>void run('resume')}>{text(['J’ai terminé — reprendre la vérification','أكملت الاختبار — مواصلة التحقق','Completed — resume verification'],lang)}</Button></>}</>}</DialogContent></Dialog></div>;
}
export default function StegConnectors({data,lang,online,onReload}:{data:WorkspaceData,lang:Lang,online:boolean,onReload:()=>Promise<void>}){
 const [editing,setEditing]=useState<Entry|null>(null),[name,setName]=useState('Connecteur STEG'),[clientId,setClient]=useState(''),[siteId,setSite]=useState(''),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[status,setStatus]=useState('active'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const canSave=!data.access||(editing?data.access.write:(data.access.add??data.access.write)).includes('stegConnectors');
 return <section className="panel technical-card"><h2>{text(['Connecteurs STEG','ربط الستاغ','STEG connectors'],lang)}</h2><p>{text(['Identifiants chiffrés côté serveur. Le consentement du client est requis sur la fiche site. Les vérifications se lancent depuis son chantier.','بيانات الدخول مشفرة على الخادم. يجب موافقة الحريف في بطاقة الموقع. يبدأ التحقق من المشروع.','Credentials are encrypted server-side. Customer consent is required on the site record. Start checks from the project.'],lang)}</p><div className="related-records">{data.records.filter(e=>e.kind==='stegConnectors').map(e=><button key={e.id} onClick={()=>{setEditing(e);setName(e.data.name);setClient(e.data.clientId);setSite(e.data.siteId);setStatus(e.data.status);setLogin('');setPassword('');setError('')}}>{e.data.name} · {e.data.loginHint} · {e.data.status}</button>)}</div><Button variant="outline" onClick={()=>{setEditing(null);setLogin('');setPassword('');setSite('');setClient('');setName('Connecteur STEG');setStatus('active')}}>{text(['Nouveau connecteur','ربط جديد','New connector'],lang)}</Button><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await connectorRequest({action:'save',id:editing?.id,revision:editing?.revision,name,clientId,siteId,login,password,status});setPassword('');setLogin('');setEditing(null);await onReload();}catch(e){setError(errorLabel(e,lang))}finally{setBusy(false)}}} className="form-grid">
 <label className="field"><span>{text(['Nom','الاسم','Name'],lang)}</span><Input required value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>{text(['Client','الحريف','Customer'],lang)}</span><select required value={clientId} onChange={e=>{setClient(e.target.value);setSite('')}}><option value="">—</option>{data.records.filter(e=>e.kind==='clients').map(e=><option key={e.id} value={e.id}>{e.data.name}</option>)}</select></label><label className="field"><span>{text(['Site STEG','موقع الستاغ','STEG site'],lang)}</span><select required value={siteId} onChange={e=>setSite(e.target.value)}><option value="">—</option>{data.records.filter(e=>e.kind==='sites'&&e.data.clientId===clientId).map(e=><option key={e.id} value={e.id}>{e.data.name} · {e.data.stegRef}</option>)}</select></label><label className="field"><span>{text(['Login STEG','اسم المستخدم للستاغ','STEG username'],lang)}</span><Input required autoComplete="username" value={login} maxLength={200} onChange={e=>setLogin(e.target.value)}/></label><label className="field"><span>{text(['Mot de passe STEG','كلمة سر الستاغ','STEG password'],lang)}</span><Input type="password" autoComplete="current-password" required={!editing} value={password} maxLength={500} onChange={e=>setPassword(e.target.value)}/>{editing&&<small>{text(['Laisser vide pour conserver le mot de passe ; ressaisir le même login.','اتركها فارغة للحفاظ على كلمة السر وأعد إدخال اسم المستخدم نفسه.','Leave blank to preserve password; re-enter the same username.'],lang)}</small>}</label><label className="field"><span>{text(['État','الحالة','Status'],lang)}</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Actif</option><option value="inactive">Inactif</option></select></label>{error&&<p role="alert" className="form-error full-width">{error}</p>}<Button type="submit" disabled={!canSave||!online||busy}>{text(['Enregistrer le connecteur','حفظ الربط','Save connector'],lang)}</Button></form></section>;
}
