'use client';
import {useMemo,useState} from 'react';
import {Box,Download,Search,ArrowUpRight,Loader2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {text,type Lang} from '@/lib/solar/modules';
import {option} from '@/lib/solar/i18n';
import type {Entry} from '@/lib/solar/domain';
import type {WorkspaceData} from '@/lib/solar/client';
import {technicalExamples,TECHNICAL_EXAMPLES_ID} from '@/lib/solar/technical-examples';
import {planModel,planProjector,defaultPlanCamera} from '@/lib/solar/plan-3d';
import PlanViewer from './plan-viewer';
const tr=(lang:Lang,fr:string,ar:string,en:string)=>text([fr,ar,en],lang);
function PlanThumbnail({entry}:{entry:Entry}){
 const model=useMemo(()=>planModel(entry),[entry]),project=planProjector(model,defaultPlanCamera);
 const faces=model.meshes.filter(m=>m.layer!=='supports').flatMap(m=>m.faces.map((f,i)=>{const p=f.map(v=>project(m.vertices[v]));return {id:m.id+'-'+i,background:m.layer==='roof',p:p.map(v=>`${v.x},${v.y}`).join(' '),depth:p.reduce((n,v)=>n+v.depth,0)/p.length,color:m.color};})).sort((a,b)=>Number(b.background)-Number(a.background)||a.depth-b.depth);
 return <svg viewBox="0 0 800 560" className="plan-thumbnail" aria-hidden="true">{faces.map(f=><polygon key={f.id} points={f.p} fill={f.color} stroke="#64748b" strokeWidth="1"/>)}</svg>;
}
export default function TechnicalPlansWorkspace({data,plans,lang,online,query,onQuery,status,onStatus,onOpen,onReload}:{data:WorkspaceData;plans:Entry[];lang:Lang;online:boolean;query:string;onQuery:(v:string)=>void;status:string;onStatus:(v:string)=>void;onOpen:(e:Entry)=>void;onReload:()=>Promise<void>}){
 const samples=useMemo(()=>technicalExamples().filter(e=>e.kind==='technicalPlans'),[]),[example,setExample]=useState<Entry|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[page,setPage]=useState(0);
 const loaded=data.records.some(r=>r.data.sampleDataset===TECHNICAL_EXAMPLES_ID),sampleMode=!!data.access?.admin;
 const load=async()=>{setBusy(true);setError('');try{const r=await fetch('/api/technical',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'loadExamples'})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error??'load_failed');await onReload();setExample(null);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
 const lastPage=Math.max(0,Math.ceil(plans.length/12)-1),current=Math.min(page,lastPage),cards=plans.slice(current*12,(current+1)*12);
 return <div className="technical-plans-workspace"><section className="plans-intro"><span className="plans-intro-icon"><Box size={25}/></span><div><h2>{tr(lang,'Vos plans, du dossier au chantier','مخططاتك من الملف إلى المشروع','Drawings, from dossier to job site')}</h2><p>{tr(lang,'Implantation 2D, maquette 3D et câblage dans une même fiche.','مخطط 2D ونموذج 3D وأسلاك في بطاقة واحدة.','2D layout, 3D model and wiring in one record.')}</p></div></section>
  <section className="panel plans-library"><div className="plans-filters"><label className="module-search"><Search size={18}/><input value={query} aria-label={tr(lang,'Rechercher un plan','البحث عن مخطط','Search drawings')} placeholder={tr(lang,'Plan, client ou chantier…','مخطط أو حريف أو مشروع…','Drawing, client or project…')} onChange={e=>{onQuery(e.target.value);setPage(0)}}/></label><select value={status} aria-label={tr(lang,'État du plan','حالة المخطط','Drawing status')} onChange={e=>{onStatus(e.target.value);setPage(0)}}><option value="all">{tr(lang,'Tous les états','كل الحالات','All statuses')}</option>{['draft','generated','reviewed'].map(s=><option key={s} value={s}>{option(s,lang)}</option>)}</select><small>{plans.length} {tr(lang,'plans','مخططات','drawings')}</small></div>
   <div className="plans-grid">{cards.map(e=>{const s=e.data.snapshot??e.data.studySnapshot,client=data.records.find(r=>r.id===e.data.clientId);return <button key={e.id} className="plan-card" onClick={()=>onOpen(e)}>{s?<PlanThumbnail entry={e}/>:<div className="plan-thumbnail plan-not-generated"><Box size={36}/><span>{tr(lang,'Relevé à compléter','أكمل الرفع','Survey required')}</span></div>}<div className="plan-card-body"><div className="plan-card-badges"><span>{option(e.data.status,lang)}</span>{e.demo===1&&<span>{tr(lang,'Exemple','مثال','Sample')}</span>}</div><h3>{e.data.name}</h3><p>{client?.data.name??tr(lang,'Client lié','الحريف المرتبط','Linked client')}</p><div className="plan-card-facts"><strong>{s?.actualKwc??e.data.capacity} kWc</strong><span>{s?.count??'—'} {tr(lang,'panneaux','لوح','modules')}</span>{s&&<span>{s.roofWidth} × {s.roofLength} m</span>}</div><span className="plan-open">{tr(lang,'Ouvrir 2D / 3D','فتح 2D / 3D','Open 2D / 3D')}<ArrowUpRight size={16}/></span></div></button>})}</div>
   {!plans.length&&<div className="plans-empty"><h3>{tr(lang,query||status!=='all'?'Aucun plan pour ces filtres':'Votre premier plan commence ici',query||status!=='all'?'لا توجد نتيجة':'ابدأ مخططك الأول',query||status!=='all'?'No drawings match these filters':'Your first drawing starts here')}</h3><p>{tr(lang,'Ouvrez un dossier STEG puis « Ouvrir / préparer le plan technique ». Les exemples ci-dessous sont déjà prêts à explorer.','افتح ملف الستاغ ثم إعداد المخطط. الأمثلة جاهزة للاستكشاف.','Open a STEG dossier and choose Open / prepare technical plan. Explore the ready-made samples below.')}</p></div>}
   {plans.length>12&&<nav className="records-pagination" aria-label={tr(lang,'Pages des plans','صفحات المخططات','Drawing pages')}><Button variant="outline" disabled={current===0} onClick={()=>setPage(current-1)}>{tr(lang,'Précédent','السابق','Previous')}</Button><span>{current+1} / {lastPage+1}</span><Button variant="outline" disabled={current===lastPage} onClick={()=>setPage(current+1)}>{tr(lang,'Suivant','التالي','Next')}</Button></nav>}
  </section>
  {!loaded&&<section className="plans-examples"><div className="panel-head"><div><h2>{tr(lang,'Explorez trois projets tunisiens','استكشف ثلاثة مشاريع تونسية','Explore three Tunisian projects')}</h2><small>{tr(lang,'Données fictives · aucune approbation STEG réelle','بيانات وهمية · دون موافقة ستاغ حقيقية','Fictional data · no actual STEG approval')}</small></div>{sampleMode&&<Button variant="outline" disabled={!online||busy} onClick={()=>void load()}>{busy?<Loader2 size={16} className="spin"/>:<Download size={16}/>} {tr(lang,'Ajouter les 3 exemples','إضافة الأمثلة الثلاثة','Add all 3 samples')}</Button>}</div><div className="plans-grid">{samples.map(e=><button key={e.id} className="plan-card" onClick={()=>setExample(e)}><PlanThumbnail entry={e}/><div className="plan-card-body"><span className="sample-label">{tr(lang,'Exemple prêt à explorer','مثال جاهز','Ready-made sample')}</span><h3>{e.data.name}</h3><p>{e.data.support==='steel'?tr(lang,'Support métallique','هيكل معدني','Steel mounting'):tr(lang,'Support aluminium','هيكل ألمنيوم','Aluminium mounting')} · {e.data.tilt}°</p><span className="plan-open">{tr(lang,'Explorer en 3D','استكشاف 3D','Explore in 3D')}<ArrowUpRight size={16}/></span></div></button>)}</div><p className="small-note">{tr(lang,'L’ajout crée des fiches client, site, chantier et dossier liées. Vos données existantes sont conservées ; aucun mouvement de stock ni facture n’est créé.','تضاف بطاقات حريف وموقع ومشروع وملف مرتبطة دون تغيير البيانات أو المخزون أو الفواتير.','Adding samples creates linked customer, site, project and dossier records, preserving existing data. No stock movements or invoices are created.')}</p></section>}
  {error&&<p role="alert" className="form-error">{error}</p>}
  <Dialog open={!!example} onOpenChange={open=>{if(!open)setExample(null)}}><DialogContent className="example-plan-dialog" dir={lang==='ar'?'rtl':'ltr'}><DialogHeader><DialogTitle>{example?.data.name}</DialogTitle><DialogDescription>{tr(lang,'Exemple fictif : toiture rectangulaire et installation indicative.','مثال وهمي لسطح مستطيل وتركيب أولي.','Fictional sample: rectangular roof and indicative installation.')}</DialogDescription></DialogHeader>{example&&<PlanViewer key={example.id} entry={example} lang={lang} local/>}</DialogContent></Dialog>
 </div>;
}
