import type {Field, Module, Words} from './modules';
const words=(fr:string,ar:string,en:string):Words=>[fr,ar,en];
export const field=(key:string,fr:string,ar:string,en:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,label:words(fr,ar,en),type,...extra});
const name=field('name','Désignation','التسمية','Name','text',{required:true});
const date=field('date','Date','التاريخ','Date','date',{required:true});
const notes=field('notes','Notes','ملاحظات','Notes','textarea');
const link=(key:string,fr:string,ar:string,en:string,target:string,required=true)=>field(key,fr,ar,en,'link',{target,required});
const num=(key:string,fr:string,ar:string,en:string,max?:number)=>field(key,fr,ar,en,'number',{min:0,max});
const money=(key:string,fr:string,ar:string,en:string)=>field(key,fr,ar,en,'money');
const select=(key:string,fr:string,ar:string,en:string,options:string[])=>field(key,fr,ar,en,'select',{options,required:true});
const rows=(key:string,fr:string,ar:string,en:string,columns:Field[],required=true)=>field(key,fr,ar,en,'rows',{columns,required});
const mod=(key:string,title:Words,group:number,fields:Field[],states=['draft','validated'],columns=['name']):Module=>({key,title,singular:title,group,icon:group===6?'Landmark':'ClipboardCheck',fields:[name,...fields,notes],states,columns});
export const itemRows=[link('productId','Article','المنتج','Product','products'),field('quantity','Quantité','الكمية','Quantity','number',{required:true,min:0.001}),money('price','Coût unitaire','تكلفة الوحدة','Unit cost'),num('tax','TVA %','الأداء %','VAT %',100),field('serials','Séries (une par ligne)','الأرقام التسلسلية','Serials (one per line)','textarea')];
export const advancedModules:Module[]=[
 mod('roles',words('Rôles et permissions','الأدوار والصلاحيات','Roles & permissions'),7,[rows('rules','Permissions par module','الصلاحيات حسب الوحدة','Module permissions',[field('module','Module','الوحدة','Module','text',{required:true}),select('access','Accès','الدخول','Access',['read','write'])])],['active','inactive']),
 mod('users',words('Comptes salariés','حسابات الموظفين','Employee accounts'),7,[field('email','E-mail de connexion ChatGPT','بريد حساب ChatGPT','ChatGPT sign-in email','email',{required:true}),link('employeeId','Employé','الموظف','Employee','employees',false),link('roleId','Rôle','الدور','Role','roles'),rows('branches','Agences autorisées','الوكالات المرخصة','Allowed branches',[link('agencyId','Agence','الوكالة','Branch','agencies')])],['active','inactive'],['name','email','roleId']),
 mod('accounts',words('Plan de comptes','دليل الحسابات','Chart of accounts'),6,[field('code','Numéro de compte','رقم الحساب','Account code','text',{required:true}),select('type','Classe','الصنف','Class',['asset','liability','equity','revenue','expense'])],['active','inactive'],['name','code','type']),
 mod('journals',words('Journaux comptables','الدفاتر المحاسبية','Accounting journals'),6,[field('code','Code journal','رمز الدفتر','Journal code','text',{required:true})],['active','inactive'],['name','code']),
 mod('journalEntries',words('Écritures comptables','القيود المحاسبية','Journal entries'),6,[date,link('journalId','Journal','الدفتر','Journal','journals'),field('reference','Pièce justificative','الوثيقة','Document reference','text',{required:true}),link('projectId','Projet','المشروع','Project','projects',false),rows('rows','Lignes comptables','سطور القيد','Entry lines',[link('accountId','Compte','الحساب','Account','accounts'),money('debit','Débit','مدين','Debit'),money('credit','Crédit','دائن','Credit'),field('label','Libellé','البيان','Description')])],['draft','posted'],['name','date','journalId']),
 mod('fiscalPeriods',words('Périodes et clôtures','الفترات والإقفال','Periods & closing'),6,[field('startDate','Début','البداية','Start','date',{required:true}),field('endDate','Fin','النهاية','End','date',{required:true})],['open','closed'],['name','startDate','endDate']),
 mod('accountingSettings',words('Liaisons comptables','الربط المحاسبي','Accounting mappings'),6,[link('salesJournal','Journal ventes','دفتر المبيعات','Sales journal','journals'),link('cashJournal','Journal trésorerie','دفتر الخزينة','Treasury journal','journals'),link('purchaseJournal','Journal achats','دفتر الشراء','Purchase journal','journals'),link('payrollJournal','Journal paie','دفتر الأجور','Payroll journal','journals'),...['receivable','payable','sales','vat','inputVat','cash','purchases','salary','social','tax','stampTax','employeePayable','staffAdvances','payrollTax'].map(k=>link(k,({receivable:'Clients',payable:'Fournisseurs',sales:'Ventes',vat:'TVA collectée',inputVat:'TVA déductible',cash:'Banque / caisse',purchases:'Achats',salary:'Salaires',social:'Organismes sociaux',tax:'Retenues salariales',stampTax:'Timbre fiscal',employeePayable:'Salaires à payer',staffAdvances:'Avances salariés',payrollTax:'Taxes employeur'} as any)[k],k,k,'accounts'))],['active','inactive']),
 mod('receipts',words('Réceptions fournisseur','استلام المورّد','Supplier receipts'),3,[link('orderId','Commande fournisseur','طلب المورّد','Purchase order','orders'),link('warehouse','Dépôt','المستودع','Warehouse','warehouses'),date,rows('items','Articles reçus','المواد المستلمة','Received items',itemRows)],['draft','posted'],['name','orderId','date']),
 mod('deliveryNotes',words('Bons de livraison','أذون التسليم','Delivery notes'),3,[link('clientId','Client','الحريف','Customer','clients'),link('projectId','Projet','المشروع','Project','projects',false),link('warehouse','Dépôt','المستودع','Warehouse','warehouses'),date,rows('items','Articles livrés','المواد المسلمة','Delivered items',itemRows)],['draft','posted'],['name','clientId','date']),
 mod('inventories',words('Inventaires','الجرد','Stocktakes'),3,[link('warehouse','Dépôt','المستودع','Warehouse','warehouses'),date,rows('items','Quantités comptées','الكميات المعدودة','Counted quantities',[link('productId','Article','المنتج','Product','products'),num('quantity','Quantité physique','الكمية الفعلية','Physical quantity'),field('serials','Séries présentes','الأرقام الموجودة','Present serials','textarea')])],['draft','posted'],['name','warehouse','date']),
 mod('transits',words('Stock en transit','المخزون في الطريق','Stock in transit'),3,[link('from','Dépôt expéditeur','مستودع الإرسال','Sending warehouse','warehouses'),link('to','Dépôt destinataire','مستودع الوصول','Destination warehouse','warehouses'),date,rows('items','Articles transférés','المواد المنقولة','Transferred items',itemRows)],['draft','shipped','received'],['name','from','to']),
 mod('collections',words('Recouvrement et impayés','الاستخلاص والمتأخرات','Collections & arrears'),2,[link('clientId','Client','الحريف','Customer','clients'),link('invoiceId','Facture','الفاتورة','Invoice','invoices'),date,field('dueDate','Prochaine action','المتابعة القادمة','Next action','date'),select('stage','Étape','المرحلة','Stage',['reminder','promise','dispute','legal','settled']),field('message','Compte rendu / relance','المتابعة','Follow-up / reminder','textarea'),money('fees','Frais documentés','المصاريف الموثقة','Documented fees')],['open','closed'],['name','invoiceId','dueDate']),
 mod('bankProfiles',words('Calibration bancaire','ضبط الطباعة البنكية','Bank print profiles'),2,[field('bank','Banque','البنك','Bank','text',{required:true}),select('instrument','Instrument','الوسيلة','Instrument',['cheque','bill']),num('width','Largeur papier (mm)','عرض الورق (مم)','Paper width (mm)'),num('height','Hauteur papier (mm)','طول الورق (مم)','Paper height (mm)'),field('offsetX','Décalage X (mm)','الإزاحة الأفقية','X offset (mm)','number',{min:-100,max:100}),field('offsetY','Décalage Y (mm)','الإزاحة العمودية','Y offset (mm)','number',{min:-100,max:100}),rows('positions','Position des champs (mm)','مواضع الخانات (مم)','Field positions (mm)',[select('key','Champ','الخانة','Field',['beneficiary','amount','words','date','place','drawer','drawee','account','dueDate']),num('x','X','X','X'),num('y','Y','Y','Y'),num('width','Largeur','العرض','Width'),num('fontSize','Taille (pt)','الحجم','Font size (pt)')])],['draft','calibrated'],['name','bank','instrument']),
 mod('payrollPolicies',words('Paramètres de paie','إعدادات الأجور','Payroll policies'),4,[field('startDate','Date d’effet','تاريخ السريان','Effective date','date',{required:true}),field('endDate','Fin de validité','نهاية الصلاحية','Valid until','date',{required:true}),field('source','Sources et régime','المصادر والنظام','Sources & regime','textarea',{required:true}),...['employeeRate','employerRate','unemploymentEmployee','unemploymentEmployer','accidentRate','tfpRate','foprolosRate','professionalRate','cssRate'].map(k=>num(k,({employeeRate:'CNSS salarié %',employerRate:'CNSS employeur %',unemploymentEmployee:'Perte emploi salarié %',unemploymentEmployer:'Perte emploi employeur %',accidentRate:'Accidents du travail %',tfpRate:'TFP %',foprolosRate:'FOPROLOS %',professionalRate:'Déduction professionnelle %',cssRate:'CSS %'} as any)[k],k,k,100)),money('professionalCap','Plafond professionnel annuel','السقف المهني السنوي','Annual professional cap'),money('cssThreshold','Seuil CSS annuel','حد المساهمة السنوي','Annual CSS threshold'),num('overtimeMultiplier','Coefficient heures supplémentaires','معامل الساعات الإضافية','Overtime multiplier',5),num('monthlyHours','Heures mensuelles','الساعات الشهرية','Monthly hours',300),num('leavePerMonth','Congés acquis / mois','العطل المكتسبة شهريا','Leave earned / month',5),num('leaveCap','Plafond congés annuels','سقف العطل السنوية','Annual leave cap',100),rows('brackets','Barème IRPP annuel','جدول الضريبة السنوي','Annual IRPP brackets',[money('ceiling','Plafond tranche (0 = dernière)','حد الشريحة (0 للأخيرة)','Band ceiling (0 = last)'),num('rate','Taux %','النسبة %','Rate %',100)])],['draft','validated'],['name','startDate','endDate']),
 mod('commissions',words('Commissions','العمولات','Commissions'),4,[link('employeeId','Employé','الموظف','Employee','employees'),link('invoiceId','Facture','الفاتورة','Invoice','invoices'),select('basis','Base','الأساس','Basis',['invoiced','collected']),num('rate','Taux %','النسبة %','Rate %',100),field('period','Mois de paie (AAAA-MM)','شهر الأجر','Payroll month'),money('amount','Montant calculé','المبلغ المحسوب','Calculated amount')],['draft','approved','paid'],['name','employeeId','amount']),
 mod('contractTemplates',words('Modèles de contrats','نماذج العقود','Contract templates'),0,[select('type','Type','النوع','Type',['sale','installation','installment','maintenance','employment','subcontract','amendment','termination']),select('language','Langue','اللغة','Language',['fr','ar','en']),field('version','Version','النسخة','Version','text',{required:true}),field('terms','Clauses avec variables','البنود والمتغيرات','Clauses with placeholders','textarea',{required:true})],['draft','approved'],['name','type','language']),
 mod('monitoring',words('Relevés et monitoring','القراءات والمراقبة','Readings & monitoring'),1,[link('projectId','Installation','التركيب','Installation','projects'),date,num('production','Production (kWh)','الإنتاج','Production (kWh)'),num('expected','Production attendue (kWh)','الإنتاج المتوقع','Expected production (kWh)'),select('connection','Connexion','الاتصال','Connection',['connected','disconnected']),select('source','Source','المصدر','Source',['manual','manufacturerCsv','solaredge']),field('observedAt','Date/heure du relevé','وقت القراءة','Reading timestamp','text',{required:true}),field('providerSiteId','Identifiant fournisseur','معرف المزوّد','Provider site ID')],['recorded'],['name','projectId','production']),
];
export function extendModules(modules:Module[]){
 const get=(k:string)=>modules.find(m=>m.key===k)!;
 get('orders').fields.find(f=>f.key==='amount')!.required=false;
 get('payroll').fields.push(money('unemploymentDeduction','Cotisation perte emploi salarié','مساهمة فقدان الشغل','Employee unemployment contribution'));
 get('orders').fields.push(rows('items','Articles commandés','المواد المطلوبة','Ordered items',itemRows));
 get('payments').fields.push(rows('allocations','Répartition sur échéances','توزيع الأقساط','Installment allocations',[link('installmentId','Échéance / facture','القسط والفاتورة','Installment / invoice','installments'),money('amount','Montant affecté','المبلغ المخصص','Allocated amount')],false));
 get('projects').fields.push(field('solarEdgeSiteId','Identifiant site SolarEdge','معرّف موقع SolarEdge','SolarEdge site ID'));
 get('employees').fields.push(money('annualTaxAllowance','Déductions personnelles annuelles','الخصومات الشخصية السنوية','Annual personal deductions'),num('openingLeave','Report congés','رصيد العطل المرحّل','Opening leave balance'));
 get('effects').fields.push(link('profileId','Profil d’impression','إعداد الطباعة','Print profile','bankProfiles',false),field('place','Lieu','المكان','Place'));
 get('contracts').fields.push(link('templateId','Modèle','النموذج','Template','contractTemplates',false),link('parentId','Contrat initial','العقد الأصلي','Original contract','contracts',false),field('version','Version','النسخة','Version'),field('signedBy','Signataire','الموقّع','Signatory'),field('signatureFileId','Identifiant pièce signée','وثيقة التوقيع','Signed attachment ID'));
 get('studies').fields.push(field('latitude','Latitude','خط العرض','Latitude','number',{min:-90,max:90}),field('longitude','Longitude','خط الطول','Longitude','number',{min:-180,max:180}),num('tilt','Inclinaison °','الميل °','Tilt °',90),field('azimuth','Azimut PVGIS (0=sud)','السمت (0 جنوب)','PVGIS azimuth (0=south)','number',{min:-180,max:180}),num('losses','Pertes %','الخسائر %','Losses %',100),num('batteryKwh','Batterie (kWh)','البطارية','Battery (kWh)'),num('loadKw','Charge secourue (kW)','الحمل الاحتياطي','Backup load (kW)'),num('autonomyHours','Autonomie (h)','الاستقلالية','Autonomy (h)'),num('usableBatteryPercent','Capacité batterie utilisable %','نسبة البطارية المستعملة','Usable battery %',100));
 modules.push(...advancedModules);
 const permissions=get('roles').fields.find(f=>f.key==='rules')!.columns![0];permissions.type='select';permissions.options=modules.filter(m=>!['users','roles'].includes(m.key)).map(m=>m.key);
}
