import type {Module,Field,Words} from './modules';
const w=(fr:string,ar:string,en:string):Words=>[fr,ar,en];
const f=(key:string,fr:string,ar:string,en:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,label:w(fr,ar,en),type,...extra});
const link=(key:string,fr:string,ar:string,en:string,target:string)=>f(key,fr,ar,en,'link',{target});
const common=[link('employeeId','Salarié responsable','الموظف المسؤول','Responsible employee','employees'),link('projectId','Chantier lié','المشروع المرتبط','Linked project','projects'),link('clientId','Client lié','الحريف المرتبط','Linked customer','clients'),f('priority','Priorité','الأولوية','Priority','select',{options:['low','normal','high','urgent']}),f('location','Lieu / lien réunion','المكان أو رابط الاجتماع','Location / meeting link'),f('reminderMinutes','Rappel avant (minutes)','التذكير قبل بالدقائق','Reminder minutes before','number',{min:0,max:10080})];
export function extendAgenda(modules:Module[]){
 const name=f('name','Intitulé','العنوان','Title','text',{required:true}),notes=f('notes','Détails','التفاصيل','Details','textarea');
 modules.push(
 {key:'agenda',title:w('Agenda & planning','الأجندة والتخطيط','Calendar & scheduling'),singular:w('agenda','أجندة','calendar'),group:11,icon:'CalendarDays',fields:[],states:['active'],columns:[]},
 {key:'tasks',title:w('Tâches des salariés','مهام الموظفين','Employee tasks'),singular:w('tâche','مهمة','task'),group:11,icon:'ClipboardCheck',fields:[name,...common,f('date','Début prévu','البداية المخططة','Planned start','date'),f('dueDate','Date limite','آخر أجل','Deadline','date',{required:true}),f('time','Heure prévue (HH:MM)','الساعة المخططة','Scheduled time (HH:MM)'),f('hours','Durée estimée (h)','المدة المقدرة','Estimated hours','number',{min:.1,max:168}),f('checklist','Checklist','قائمة التحقق','Checklist','rows',{columns:[f('label','Action','الإجراء','Action','text',{required:true}),f('done','Terminée','مكتملة','Done','select',{options:['no','yes']})]}),f('dependencies','Tâches préalables','المهام السابقة','Dependencies','rows',{columns:[{...link('taskId','Tâche préalable','المهمة السابقة','Preceding task','tasks'),required:true}]}),notes],states:['todo','inProgress','blocked','done','cancelled'],columns:['name','employeeId','dueDate','priority']},
 {key:'agendaEvents',title:w('Rendez-vous & réunions','المواعيد والاجتماعات','Appointments & meetings'),singular:w('rendez-vous','موعد','appointment'),group:11,icon:'CalendarClock',fields:[name,...common,f('date','Date de début','تاريخ البداية','Start date','date',{required:true}),f('endDate','Date de fin','تاريخ النهاية','End date','date'),f('allDay','Journée entière','كامل اليوم','All day','select',{options:['no','yes']}),f('time','Heure de début (HH:MM)','ساعة البداية','Start time (HH:MM)'),f('endTime','Heure de fin (HH:MM)','ساعة النهاية','End time (HH:MM)'),f('participants','Participants salariés','الموظفون المشاركون','Employee participants','rows',{columns:[{...link('employeeId','Salarié','الموظف','Employee','employees'),required:true}]}),f('repeat','Répétition','التكرار','Repeat','select',{options:['none','daily','weekly','monthly']}),f('repeatInterval','Répéter tous les','التكرار كل','Repeat every','number',{min:1,max:30}),f('repeatUntil','Fin de répétition','نهاية التكرار','Repeat until','date'),f('excludedDates','Occurrences annulées (AAAA-MM-JJ / ligne)','مواعيد ملغاة سطر لكل تاريخ','Cancelled occurrences (YYYY-MM-DD per line)','textarea'),notes],states:['planned','confirmed','completed','cancelled'],columns:['name','date','time','employeeId']}
 );
 const planning=modules.find(m=>m.key==='planning')!;planning.group=11;
 planning.fields.push(f('location','Lieu','المكان','Location'),f('priority','Priorité','الأولوية','Priority','select',{options:['low','normal','high','urgent']}),f('reminderMinutes','Rappel avant (minutes)','التذكير قبل بالدقائق','Reminder minutes before','number',{min:0,max:10080}));
 modules.find(m=>m.key==='roles')!.fields.find(f=>f.key==='rules')!.columns![0].options=modules.filter(m=>!['users','roles'].includes(m.key)).map(m=>m.key);
 modules.find(m=>m.key==='roles')!.fields.find(f=>f.key==='rules')!.columns!.find(f=>f.key==='scope')!.options!.push('self');
}
