import type {Entry} from './domain';
export const integer=(v:any,min=0)=>{if(!Number.isSafeInteger(v)||v<min||v>1e12)throw new Error('invalid_amount');return v as number;};
export function quantity(v:any){if(typeof v!=='number'||!Number.isFinite(v)||v<0||!Number.isSafeInteger(Math.round(v*1000))||Math.abs(v*1000-Math.round(v*1000))>1e-7)throw new Error('invalid_quantity');return Math.round(v*1000);}
export function journalTotals(rows:any[],balanced=true){if(!Array.isArray(rows)||rows.length<2||rows.length>100)throw new Error('required_lines');let debit=0,credit=0;for(const r of rows){const d=integer(r.debit??0),c=integer(r.credit??0);if(!r.accountId||(!d&&!c)||(d&&c))throw new Error('invalid_journal_line');debit+=d;credit+=c;}integer(debit);integer(credit);if(balanced&&debit!==credit)throw new Error('unbalanced_entry');return {debit,credit};}
export function annualTax(income:number,brackets:any[]){integer(income);if(!Array.isArray(brackets)||brackets.length<1||brackets.length>20)throw new Error('invalid_brackets');let previous=0,tax=0;for(let i=0;i<brackets.length;i++){const b=brackets[i],last=i===brackets.length-1;const ceiling=integer(b.ceiling??0);if(typeof b.rate!=='number'||b.rate<0||b.rate>100||(!last&&ceiling<=previous)||(last&&ceiling!==0))throw new Error('invalid_brackets');const top=last?income:Math.min(income,ceiling);if(top>previous)tax+=(top-previous)*b.rate/100;previous=ceiling;}return Math.round(tax);}
export function automaticPayroll(employee:Entry,period:string,policy:Entry,records:Entry[],input:any={}){
 if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(period))throw new Error('invalid_period');
 const p=policy.data,first=period+'-01',[y,m]=period.split('-').map(Number),days=new Date(Date.UTC(y,m,0)).getUTCDate(),last=period+'-'+days;
 if(p.status!=='validated'||p.startDate>first||p.endDate<last)throw new Error('payroll_policy_required');
 for(const k of ['employeeRate','employerRate','unemploymentEmployee','unemploymentEmployer','accidentRate','tfpRate','foprolosRate','professionalRate','cssRate'])if(typeof p[k]!=='number'||p[k]<0||p[k]>100)throw new Error('payroll_policy_required');
 if(!p.monthlyHours||!p.overtimeMultiplier)throw new Error('payroll_policy_required');
 const start=employee.data.startDate&&employee.data.startDate>first?employee.data.startDate:first,end=employee.data.endDate&&employee.data.endDate<last?employee.data.endDate:last;
 const paidDays=Math.max(0,Math.round((Date.parse(end)-Date.parse(start))/86400000)+1);
 let unpaidDays=0;for(const l of records.filter(r=>r.kind==='leave'&&r.data.employeeId===employee.id&&r.data.status==='approved'&&r.data.type==='unpaidLeave')){const a=l.data.startDate>start?l.data.startDate:start,b=l.data.endDate<end?l.data.endDate:end;if(b>=a)unpaidDays+=Math.round((Date.parse(b)-Date.parse(a))/86400000)+1;}
 const salary=integer(employee.data.salary??0),base=Math.round(salary*Math.max(0,paidDays-unpaidDays)/days);
 const hours=records.filter(r=>r.kind==='attendance'&&r.data.status==='approved'&&r.data.employeeId===employee.id&&r.data.date>=first&&r.data.date<=last).reduce((n,r)=>n+(r.data.overtime||0),0);
 const commissionRows=records.filter(r=>r.kind==='commissions'&&r.data.status==='approved'&&r.data.employeeId===employee.id&&r.data.period===period);
 const commissions=commissionRows.reduce((n,r)=>n+integer(r.data.amount||0),0),overtime=Math.round(salary/p.monthlyHours*hours*p.overtimeMultiplier),bonus=integer(input.bonus??0)+overtime+commissions,allowances=integer(input.allowances??0),gross=base+bonus+allowances;
 // Each component remains separately visible; allowances in this basic regime are taxable/social.
 const cnssDeduction=Math.round(gross*p.employeeRate/100),unemploymentDeduction=Math.round(gross*p.unemploymentEmployee/100),annualNet=Math.max(0,(gross-cnssDeduction-unemploymentDeduction)*12),professional=Math.min(Math.round(annualNet*p.professionalRate/100),integer(p.professionalCap??0));
 const annualTaxable=Math.ceil(Math.max(0,annualNet-professional-integer(employee.data.annualTaxAllowance??0))/1000)*1000,incomeTax=Math.round(annualTax(annualTaxable,p.brackets)/12),solidarity=annualTaxable>(p.cssThreshold??0)?Math.round(annualTaxable*p.cssRate/100/12):0;
 const advanceDeduction=integer(input.advanceDeduction??0),otherDeduction=integer(input.otherDeduction??0),deductions=cnssDeduction+unemploymentDeduction+incomeTax+solidarity+advanceDeduction+otherDeduction,net=gross-deductions;if(net<0)throw new Error('negative_net');
 const employerSocial=Math.round(gross*(p.employerRate+p.unemploymentEmployer+p.accidentRate)/100),employerTaxes=Math.round(gross*(p.tfpRate+p.foprolosRate)/100),employerCharges=employerSocial+employerTaxes;
 return {name:`Paie ${period} · ${employee.data.name}`,employeeId:employee.id,agencyId:employee.data.agencyId,period,base,bonus,allowances,cnssDeduction,unemploymentDeduction,incomeTax,solidarity,advanceDeduction,otherDeduction,employerSocial,employerTaxes,employerCharges,gross,deductions,net,employerCost:gross+employerCharges,policyId:policy.id,policyRevision:policy.revision,policySnapshot:p,commissionIds:commissionRows.map(r=>r.id),paidDays,unpaidDays,overtime,commissions,annualTaxable,calculationSource:p.source,status:'reviewed',automatic:true};
}
export function leaveBalance(employee:Entry,policy:Entry,records:Entry[],asOf:string){
 const year=asOf.slice(0,4),start=employee.data.startDate&&employee.data.startDate>year+'-01-01'?employee.data.startDate:year+'-01-01';
 let earned=0;for(let month=1;month<=12;month++){const first=`${year}-${String(month).padStart(2,'0')}-01`,n=new Date(Date.UTC(Number(year),month,0)).getUTCDate(),last=first.slice(0,8)+n;if(first>asOf)break;const a=start>first?start:first,b=asOf<last?asOf:last;if(b>=a)earned+=(Math.round((Date.parse(b)-Date.parse(a))/86400000)+1)/n*(policy.data.leavePerMonth??0);}
 const used=records.filter(r=>r.kind==='leave'&&r.data.employeeId===employee.id&&r.data.type==='paidLeave'&&r.data.status==='approved'&&r.data.startDate.slice(0,4)===year).reduce((n,r)=>n+(r.data.days||0),0);
 const acquired=Math.min(Math.floor(earned*100)/100,policy.data.leaveCap??365),opening=employee.data.openingLeave??0;return {opening,acquired,used,balance:Math.round((opening+acquired-used)*100)/100};
}
export function profitability(records:Entry[],allocations:any[]){return records.filter(r=>r.kind==='projects').map(project=>{
 const linked=records.filter(r=>r.data.projectId===project.id),invoices=linked.filter(r=>r.kind==='invoices'&&r.data.status==='issued'),revenue=invoices.reduce((n,r)=>n+((r.data.subtotal||0)-(r.data.discount||0))*(r.data.invoiceType==='creditNote'?-1:1),0);
 const material=linked.filter(r=>r.kind==='movements'&&!r.data.transferId).reduce((n,r)=>n+Math.round(r.data.quantity*(r.data.unitCost||0))*(r.data.direction==='stockOut'?1:-1),0),expenses=linked.filter(r=>r.kind==='expenses'&&['approved','paid'].includes(r.data.status)).reduce((n,r)=>n+(r.data.amount||0),0),labor=linked.filter(r=>r.kind==='attendance'&&r.data.status==='approved').reduce((n,r)=>n+(r.data.cost||0),0),vehicle=linked.filter(r=>r.kind==='vehicleCosts'&&['approved','paid'].includes(r.data.status)).reduce((n,r)=>n+(r.data.amount||0),0),sav=linked.filter(r=>r.kind==='tickets').reduce((n,r)=>n+(r.data.cost||0),0);
 const invoiceIds=new Set(invoices.map(r=>r.id)),dues=new Set(records.filter(r=>r.kind==='installments'&&invoiceIds.has(r.data.invoiceId)).map(r=>r.id)),collected=allocations.filter(a=>dues.has(a.installment_id)).reduce((n,a)=>n+a.amount,0),cost=material+expenses+labor+vehicle+sav;
 return {projectId:project.id,name:project.data.name,agencyId:project.data.agencyId,revenue,collected,material,expenses,labor,vehicle,sav,cost,margin:revenue-cost,budget:project.data.budget||0};
});}
export function solarSizing(d:any){if(!d.capacity||d.capacity<=0)throw new Error('invalid_capacity');const usable=(d.usableBatteryPercent??80)/100;if(usable<=0||usable>1)throw new Error('invalid_battery_capacity');return {batteryRequired:d.loadKw&&d.autonomyHours?Math.round(d.loadKw*d.autonomyHours/usable*100)/100:0,autonomy:d.batteryKwh&&d.loadKw?Math.round(d.batteryKwh*usable/d.loadKw*100)/100:0};}
