import {db,assertAdmin,assertRecord,assertModule,type Access} from './server';
import {byKey} from './modules';
import {validate,type Entry,plan} from './domain';
import {integer,quantity,journalTotals,automaticPayroll,leaveBalance,profitability,solarSizing} from './business-domain';
export const decodeRecord=(r:any):Entry=>({id:r.id,kind:r.kind,data:JSON.parse(r.data),revision:r.revision,demo:r.demo,archived:r.archived,createdAt:r.created_at,updatedAt:r.updated_at});
export async function all(owner:string){return (await db().prepare('SELECT * FROM records WHERE owner=? AND archived=0').bind(owner).all()).results.map(decodeRecord);}
export async function record(ctx:Access,id:string,kind?:string,write=false){const r=await db().prepare('SELECT * FROM records WHERE owner=? AND id=? AND archived=0').bind(ctx.owner,id).first();if(!r)throw new Error('not_found');const e=decodeRecord(r);if(kind&&e.kind!==kind)throw new Error('invalid_reference');assertRecord(ctx,e,write);return e;}
export function insert(ctx:Access,kind:string,data:any,id=crypto.randomUUID()){assertModule(ctx,kind,true);const now=new Date().toISOString();return db().prepare('INSERT INTO records(id,owner,kind,data,revision,demo,archived,created_at,updated_at) VALUES(?,?,?,?,1,0,0,?,?)').bind(id,ctx.owner,kind,JSON.stringify({...data,actorId:ctx.actor}),now,now);}
export function guard(ctx:Access,e:Entry){return db().prepare('INSERT INTO operation_guards(id,owner,record_id,revision) VALUES(?,?,?,?)').bind(crypto.randomUUID(),ctx.owner,e.id,e.revision);}
export function update(ctx:Access,e:Entry,data:any){assertRecord(ctx,e,true);return db().prepare('UPDATE records SET data=?,revision=revision+1,updated_at=? WHERE id=? AND owner=?').bind(JSON.stringify({...data,actorId:ctx.actor}),new Date().toISOString(),e.id,ctx.owner);}
export async function paymentReversal(ctx:Access,payment:Entry,reason:string){const journal=(await all(ctx.owner)).find(r=>r.kind==='journalEntries'&&r.data.sourceId===payment.id&&r.data.status==='posted'&&!r.data.originalId);if(!journal)return [];assertRecord(ctx,journal,true);return [insert(ctx,'journalEntries',{...journal.data,name:'Extourne · '+journal.data.name,date:new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Tunis'}),reference:reason,originalId:journal.id,rows:journal.data.rows.map((r:any)=>({...r,debit:r.credit??0,credit:r.debit??0})),status:'posted'},journal.id+'-reversal')];}
export async function reopenRestructured(ctx:Access,p:Entry){const links=(await db().prepare('SELECT installment_id FROM allocations WHERE payment_id=? AND owner=?').bind(p.id,ctx.owner).all()).results;const batch:D1PreparedStatement[]=[];for(const a of links as any[]){const due=await record(ctx,a.installment_id,'installments',true);if(due.data.status==='restructured')batch.push(guard(ctx,due),update(ctx,due,{...due.data,status:'open',reopenedFrom:p.id}));}return batch;}
export async function cancelPayment(ctx:Access,p:Entry,reason:string){if(p.kind!=='payments'||p.data.status!=='cleared'||!reason?.trim())throw new Error('invalid_cancellation');await db().batch([guard(ctx,p),...await reopenRestructured(ctx,p),...await paymentReversal(ctx,p,reason),update(ctx,p,{...p.data,status:'cancelled',cancellationReason:reason})]);return {ok:true};}
export async function referenceRows(ctx:Access,kind:string,data:any){for(const f of byKey[kind].fields){if(f.type==='link'&&data[f.key])await record(ctx,data[f.key],f.target);if(f.type==='rows')for(const r of data[f.key]??[])for(const c of f.columns??[])if(c.type==='link'&&r[c.key])await record(ctx,r[c.key],c.target);}}
export async function policyFor(ctx:Access,date:string){const policies=(await all(ctx.owner)).filter(r=>r.kind==='payrollPolicies'&&r.data.status==='validated'&&r.data.startDate<=date&&r.data.endDate>=date);if(policies.length!==1)throw new Error('payroll_policy_required');return policies[0];}
export async function validateBusinessSave(ctx:Access,kind:string,data:any,id?:string){
 data.actorId=ctx.actor;
 if(['users','roles','payrollPolicies','accountingSettings','fiscalPeriods'].includes(kind))assertAdmin(ctx);
 if(kind==='users'){data.email=data.email.toLowerCase();const duplicate=await db().prepare("SELECT id FROM records WHERE owner=? AND kind='users' AND archived=0 AND lower(json_extract(data,'$.email'))=? AND id!=?").bind(ctx.owner,data.email,id??'').first();if(duplicate)throw new Error('duplicate_account');}
 if(['receipts','deliveryNotes','inventories','transits','journalEntries','fiscalPeriods'].includes(kind)&&!['draft','open'].includes(data.status))throw new Error('use_business_action');
 if(kind==='orders'&&['partial','received'].includes(data.status))throw new Error('use_receipt_action');
 if(kind==='contracts'&&data.status==='signed')throw new Error('use_signature_action');
 if(kind==='payroll'&&data.status==='validated')throw new Error('use_payroll_action');
 if(kind==='payroll'&&id){const old=await record(ctx,id);if(old.data.automatic)throw new Error('use_payroll_action');}
 if(['receipts','deliveryNotes','inventories'].includes(kind)){const w=await record(ctx,data.warehouse,'warehouses');data.agencyId=w.data.agencyId;assertRecord(ctx,{id:id??'',kind,data} as Entry,true);}
 if(kind==='transits'){if(data.from===data.to)throw new Error('invalid_transfer');const w=await record(ctx,data.from,'warehouses');const destination=await record(ctx,data.to,'warehouses');data.agencyId=w.data.agencyId;data.destinationAgencyId=destination.data.agencyId;}
 if(kind==='fiscalPeriods'){const overlap=(await all(ctx.owner)).some(r=>r.kind==='fiscalPeriods'&&r.id!==id&&r.data.startDate<=data.endDate&&r.data.endDate>=data.startDate);if(overlap)throw new Error('period_overlap');}
 if(kind==='payrollPolicies'&&data.status==='validated'){const overlap=(await all(ctx.owner)).some(r=>r.kind==='payrollPolicies'&&r.id!==id&&r.data.status==='validated'&&r.data.startDate<=data.endDate&&r.data.endDate>=data.startDate);if(overlap)throw new Error('policy_overlap');}
 if(kind==='commissions'){const inv=await record(ctx,data.invoiceId,'invoices');const employee=await record(ctx,data.employeeId,'employees');data.agencyId=employee.data.agencyId;if(inv.data.invoiceType==='creditNote'||inv.data.status!=='issued')throw new Error('invalid_invoice');const dues=(await all(ctx.owner)).filter(r=>r.kind==='installments'&&r.data.invoiceId===inv.id);const ids=new Set(dues.map(r=>r.id));const allocated=(await db().prepare('SELECT * FROM allocations WHERE owner=?').bind(ctx.owner).all()).results.filter((a:any)=>ids.has(a.installment_id)).reduce((n:number,a:any)=>n+a.amount,0);data.amount=Math.round((data.basis==='collected'?allocated:inv.data.total)*data.rate/100);if(data.status==='paid')throw new Error('use_payroll_action');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(data.period??''))throw new Error('invalid_period');}
 if(kind==='collections'){const inv=await record(ctx,data.invoiceId,'invoices');if(inv.data.clientId!==data.clientId)throw new Error('client_project_mismatch');data.agencyId=inv.data.agencyId;}
 if(kind==='leave'){const employee=await record(ctx,data.employeeId,'employees');data.agencyId=employee.data.agencyId;const records=await all(ctx.owner);const overlap=records.some(r=>r.kind==='leave'&&r.id!==id&&r.data.employeeId===employee.id&&r.data.status==='approved'&&r.data.startDate<=data.endDate&&r.data.endDate>=data.startDate);if(data.status==='approved'&&overlap)throw new Error('leave_overlap');if(data.status==='approved'&&data.type==='paidLeave'){const p=await policyFor(ctx,data.startDate);const b=leaveBalance(employee,p,records.filter(r=>r.id!==id),data.startDate);if(!data.days||data.days>b.balance)throw new Error('insufficient_leave');data.annualLeaveLimit=b.opening+b.acquired;}}
 if(kind==='payments'){if(data.installmentId&&(await record(ctx,data.installmentId,'installments')).data.status==='restructured')throw new Error('invalid_allocation');for(const a of data.allocations??[]){const due=await record(ctx,a.installmentId,'installments');if(due.data.status==='restructured')throw new Error('invalid_allocation');}if(data.installmentId&&data.allocations?.length)throw new Error('invalid_allocation');const amount=(data.allocations??[]).reduce((n:number,r:any)=>n+integer(r.amount,1),0);if(amount>data.amount||data.allocations?.length&&data.direction!=='incoming')throw new Error('invalid_allocation');}
 if(kind==='effects'&&id){const old=await record(ctx,id,'effects');if(data.status==='rejected'&&old.data.paymentId){const payment=await record(ctx,old.data.paymentId,'payments',true);if(payment.data.status==='cleared')throw new Error('use_reject_effect_action');}}
}
export async function movement(ctx:Access,item:any,warehouse:string,direction:string,parent:Entry,extra:any={}){
 const product=await record(ctx,item.productId,'products'),w=await record(ctx,warehouse,'warehouses');const serialList=String(item.serials??'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);
 if(new Set(serialList).size!==serialList.length)throw new Error('duplicate_serial');if((product.data.tracking==='serialTracking'||serialList.length)&&(!Number.isInteger(item.quantity)||serialList.length!==item.quantity))throw new Error('serial_count');if(quantity(item.quantity)<=0)throw new Error('invalid_quantity');
 return insert(ctx,'movements',{name:parent.data.name,productId:product.id,warehouse,direction,quantity:item.quantity,serials:item.serials??'',serialList,agencyId:w.data.agencyId,projectId:parent.data.projectId,date:parent.data.date,reason:parent.id,unitCost:item.price??product.data.purchasePrice??0,status:'posted',...extra});
}
export async function postStock(ctx:Access,e:Entry,receiveTransit=false){
 const d=e.data;if(e.kind==='transits'&&receiveTransit){if(d.status!=='shipped')throw new Error('invalid_status');}else if(d.status!=='draft')throw new Error('already_posted');
 const batch:D1PreparedStatement[]=[guard(ctx,e)];
 if(e.kind==='receipts'){
  const order=await record(ctx,d.orderId,'orders',true);if(!['ordered','partial'].includes(order.data.status))throw new Error('invalid_order');batch.push(guard(ctx,order));const past=(await all(ctx.owner)).filter(r=>r.kind==='receipts'&&r.data.orderId===order.id&&r.data.status==='posted');
  const received=new Map<string,number>();for(const r of past)for(const i of r.data.items)received.set(i.productId,(received.get(i.productId)??0)+quantity(i.quantity));for(const i of d.items){const ordered=order.data.items?.find((x:any)=>x.productId===i.productId);if(!ordered||quantity(i.quantity)+(received.get(i.productId)??0)>quantity(ordered.quantity))throw new Error('overreceipt');received.set(i.productId,(received.get(i.productId)??0)+quantity(i.quantity));batch.push(await movement(ctx,{...i,price:ordered.price??0},d.warehouse,'stockIn',e));}
  batch.push(update(ctx,order,{...order.data,status:order.data.items.every((i:any)=>(received.get(i.productId)??0)===quantity(i.quantity))?'received':'partial'}));
 }else if(e.kind==='inventories'){
  const balances=(await db().prepare('SELECT * FROM stock_balances WHERE owner=? AND warehouse=?').bind(ctx.owner,d.warehouse).all()).results;
  const productIds=new Set(d.items.map((i:any)=>i.productId));if(balances.some((b:any)=>b.quantity&& !productIds.has(b.product_id)))throw new Error('inventory_incomplete');
  for(const i of d.items){const product=await record(ctx,i.productId,'products');const current=Number((balances.find((b:any)=>b.product_id===i.productId) as any)?.quantity??0),count=quantity(i.quantity);batch.push(db().prepare('INSERT INTO stock_guards(id,owner,product_id,warehouse,quantity) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),ctx.owner,i.productId,d.warehouse,current));if(product.data.tracking==='serialTracking'){const serials=(await db().prepare('SELECT serial FROM serial_locations WHERE owner=? AND warehouse=? AND product_id=?').bind(ctx.owner,d.warehouse,product.id).all()).results.map((s:any)=>s.serial);const counted=String(i.serials??'').split(/\r?\n/).filter(Boolean);if(new Set(counted).size!==counted.length||counted.length!==i.quantity)throw new Error('serial_count');const added=counted.filter((s:string)=>!serials.includes(s)),removed=serials.filter((s:any)=>!counted.includes(s));if(removed.length)batch.push(await movement(ctx,{...i,quantity:removed.length,serials:removed.join('\n')},d.warehouse,'stockOut',e));if(added.length)batch.push(await movement(ctx,{...i,quantity:added.length,serials:added.join('\n')},d.warehouse,'stockIn',e));}else if(current!==count)batch.push(await movement(ctx,{...i,quantity:Math.abs(count-current)/1000},d.warehouse,count>current?'stockIn':'stockOut',e));}
 }else if(e.kind==='deliveryNotes')for(const i of d.items)batch.push(await movement(ctx,i,d.warehouse,'stockOut',e));
 else if(e.kind==='transits')for(const i of d.items)batch.push(await movement(ctx,i,receiveTransit?d.to:d.from,receiveTransit?'stockIn':'stockOut',e,{transferId:e.id}));
 else throw new Error('invalid_action');
 batch.push(update(ctx,e,{...d,status:e.kind==='transits'?(receiveTransit?'received':'shipped'):'posted'}));await db().batch(batch);return {ok:true};
}
export async function postJournal(ctx:Access,e:Entry){if(e.data.status!=='draft')throw new Error('already_posted');journalTotals(e.data.rows);await referenceRows(ctx,e.kind,e.data);await db().batch([guard(ctx,e),update(ctx,e,{...e.data,status:'posted',postedBy:ctx.actor,postedAt:new Date().toISOString()})]);return {ok:true};}
export async function reverseJournal(ctx:Access,e:Entry,body:any){if(e.data.status!=='posted'||!body.reason?.trim())throw new Error('invalid_reversal');const date=validate('movements',{name:'date',productId:'x',warehouse:'x',direction:'stockIn',quantity:1,date:body.date,reason:'x'}).date;const id=e.id+'-reversal';const prior=await db().prepare('SELECT id FROM records WHERE id=? AND owner=?').bind(id,ctx.owner).first();if(prior)return {id};const data={...e.data,name:'Extourne · '+e.data.name,date,reference:body.reason,originalId:e.id,rows:e.data.rows.map((r:any)=>({...r,debit:r.credit??0,credit:r.debit??0})),status:'posted'};await insert(ctx,'journalEntries',data,id).run();return {id};}
export async function closePeriod(ctx:Access,e:Entry){assertAdmin(ctx);if(e.data.status!=='open')throw new Error('already_closed');const drafts=(await all(ctx.owner)).filter(r=>r.kind==='journalEntries'&&r.data.status==='draft'&&r.data.date>=e.data.startDate&&r.data.date<=e.data.endDate);if(drafts.length)throw new Error('unposted_entries');await db().batch([guard(ctx,e),update(ctx,e,{...e.data,status:'closed',closedBy:ctx.actor,closedAt:new Date().toISOString()})]);return {ok:true};}
export async function reschedule(ctx:Access,invoice:Entry,body:any){
 if(invoice.data.status!=='issued'||!body.reason?.trim())throw new Error('invalid_invoice');const dues=(await all(ctx.owner)).filter(r=>r.kind==='installments'&&r.data.invoiceId===invoice.id&&r.data.status!=='restructured');const allocations=(await db().prepare('SELECT * FROM allocations WHERE owner=?').bind(ctx.owner).all()).results;
 if(!dues.length)throw new Error('schedule_required');const paid=(id:string)=>allocations.filter((a:any)=>a.installment_id===id).reduce((n:number,a:any)=>n+a.amount,0),amount=dues.reduce((n,r)=>n+r.data.amount-paid(r.id),0);if(!/^\d{4}-\d{2}-\d{2}$/.test(body.firstDate)||new Date(body.firstDate+'T12:00:00Z').toISOString().slice(0,10)!==body.firstDate)throw new Error('invalid_date');const list=plan(amount,body.count,body.firstDate);assertModule(ctx,'installments',true);const batch=[guard(ctx,invoice)];for(const r of dues){assertRecord(ctx,r,true);batch.push(guard(ctx,r),update(ctx,r,{...r.data,originalAmount:r.data.amount,amount:paid(r.id),status:'restructured',restructureReason:body.reason}));}
 for(let i=0;i<list.length;i++)batch.push(insert(ctx,'installments',{name:`${invoice.data.name} · rééchelonnement ${i+1}`,clientId:invoice.data.clientId,agencyId:invoice.data.agencyId,projectId:invoice.data.projectId,invoiceId:invoice.id,...list[i],status:'open',restructureReason:body.reason}));batch.push(update(ctx,invoice,{...invoice.data,lastReschedule:body.reason}));await db().batch(batch);return {ok:true,count:list.length};
}
export async function settleInvoices(ctx:Access,body:any){
 assertModule(ctx,'payments',true);const data=validate('payments',body.data);const paymentId=typeof body.requestId==='string'&&/^[\w-]{8,80}$/.test(body.requestId)?body.requestId:crypto.randomUUID();const previous=await db().prepare('SELECT data FROM records WHERE id=? AND owner=?').bind(paymentId,ctx.owner).first<{data:string}>();if(previous){const old=JSON.parse(previous.data);if(old.amount!==data.amount||old.clientId!==data.clientId||old.date!==data.date||old.method!==data.method||JSON.stringify(old.invoiceAllocations)!==JSON.stringify(body.invoices))throw new Error('idempotency_conflict');return {id:paymentId};}if(data.direction!=='incoming'||data.status!=='cleared'||!Array.isArray(body.invoices)||!body.invoices.length||body.invoices.length>100)throw new Error('invalid_allocation');
 const entries=await all(ctx.owner),existing=(await db().prepare('SELECT * FROM allocations WHERE owner=?').bind(ctx.owner).all()).results,batch:D1PreparedStatement[]=[],parts:any[]=[];let total=0;
 if(new Set(body.invoices.map((r:any)=>r.invoiceId)).size!==body.invoices.length)throw new Error('invalid_allocation');
 for(const row of body.invoices){const invoice=await record(ctx,row.invoiceId,'invoices');if(invoice.data.clientId!==data.clientId||invoice.data.status!=='issued'||invoice.data.invoiceType==='creditNote')throw new Error('invalid_invoice');let remaining=integer(row.amount,1);total+=remaining;let dues=entries.filter(r=>r.kind==='installments'&&r.data.invoiceId===invoice.id&&r.data.status!=='restructured').sort((a,b)=>a.data.dueDate.localeCompare(b.data.dueDate));
  if(!dues.length){const id=invoice.id+'-direct-due';const d={name:invoice.data.name,invoiceId:invoice.id,clientId:data.clientId,agencyId:invoice.data.agencyId,projectId:invoice.data.projectId,amount:invoice.data.total,dueDate:invoice.data.dueDate,status:'open'};batch.push(insert(ctx,'installments',d,id));dues=[{id,kind:'installments',data:d} as unknown as Entry];}
  for(const due of dues){assertRecord(ctx,due);const paid=existing.filter((a:any)=>a.installment_id===due.id).reduce((n:number,a:any)=>n+a.amount,0),allocated=Math.min(remaining,due.data.amount-paid);if(allocated>0){parts.push({installmentId:due.id,amount:allocated});remaining-=allocated;}}
  if(remaining)throw new Error('overpayment');
 }
 if(total>data.amount)throw new Error('invalid_allocation');data.allocations=parts;delete data.installmentId;const id=paymentId;const prior=await db().prepare('SELECT data FROM records WHERE id=? AND owner=?').bind(id,ctx.owner).first<{data:string}>();if(prior){const old=JSON.parse(prior.data);if(old.amount!==data.amount||old.clientId!==data.clientId||JSON.stringify(old.invoiceAllocations)!==JSON.stringify(body.invoices))throw new Error('idempotency_conflict');return {id};}assertRecord(ctx,{id,kind:'payments',data} as Entry,true);batch.push(insert(ctx,'payments',{...data,invoiceAllocations:body.invoices},id));await db().batch(batch);return {id};
}
export async function rejectEffect(ctx:Access,e:Entry,reason:string){if(!reason?.trim()||['rejected','cancelled','replaced'].includes(e.data.status))throw new Error('invalid_rejection');const batch=[guard(ctx,e),update(ctx,e,{...e.data,status:'rejected',rejectionReason:reason})];if(e.data.paymentId){const p=await record(ctx,e.data.paymentId,'payments',true);if(p.data.status==='cleared')batch.push(guard(ctx,p),...await reopenRestructured(ctx,p),...await paymentReversal(ctx,p,reason),update(ctx,p,{...p.data,status:'cancelled',cancellationReason:reason}));}await db().batch(batch);return {ok:true};}
export async function calculatePayroll(ctx:Access,body:any){const employee=await record(ctx,body.employeeId,'employees');assertModule(ctx,'payroll',true);const p=await policyFor(ctx,body.period+'-01');const data=automaticPayroll(employee,body.period,p,await all(ctx.owner),body);const id=crypto.randomUUID();assertRecord(ctx,{id,kind:'payroll',data} as unknown as Entry,true);await insert(ctx,'payroll',data,id).run();return {id,data};}
export async function approvePayroll(ctx:Access,e:Entry){if(e.data.status!=='reviewed'||!e.data.automatic)throw new Error('automatic_payroll_required');const employee=await record(ctx,e.data.employeeId,'employees'),batch=[guard(ctx,e),guard(ctx,employee)];for(const id of e.data.commissionIds??[]){const c=await record(ctx,id,'commissions',true);if(c.data.status!=='approved')throw new Error('commission_already_paid');batch.push(guard(ctx,c),update(ctx,c,{...c.data,status:'paid',payrollId:e.id}));}batch.push(update(ctx,e,{...e.data,status:'validated',validatedBy:ctx.actor}));await db().batch(batch);return {ok:true};}
export async function signContract(ctx:Access,e:Entry,body:any){if(e.data.status==='signed'||!body.signedBy?.trim())throw new Error('invalid_signature');const f=await db().prepare('SELECT * FROM files WHERE id=? AND owner=? AND record_id=?').bind(body.fileId,ctx.owner,e.id).first<any>();if(!f)throw new Error('signature_attachment_required');const {env}=await import('cloudflare:workers');const object=await env.BUCKET?.get(`${ctx.owner}/${f.id}`);if(!object)throw new Error('signature_attachment_required');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await object.arrayBuffer()))).map(b=>b.toString(16).padStart(2,'0')).join('');await db().batch([guard(ctx,e),update(ctx,e,{...e.data,status:'signed',signedBy:body.signedBy,signatureFileId:f.id,signatureHash:hash,signedAt:new Date().toISOString(),signatureMethod:'uploaded_signed_document'})]);return {ok:true};}
export async function makeContract(ctx:Access,e:Entry,body:any){const template=await record(ctx,body.templateId,'contractTemplates');if(template.data.status!=='approved')throw new Error('template_not_approved');const client=e.data.clientId?await record(ctx,e.data.clientId,'clients'):null;const vars:Record<string,string>={reference:e.data.name,client:client?.data.name??'',amount:((e.data.total??e.data.amount??0)/1000).toFixed(3),date:e.data.date??new Date().toISOString().slice(0,10),project:e.data.projectId?(await record(ctx,e.data.projectId,'projects')).data.name:'',employee:e.data.employeeId?(await record(ctx,e.data.employeeId,'employees')).data.name:''};const terms=template.data.terms.replace(/\{\{(\w+)\}\}/g,(_:string,k:string)=>{if(!(k in vars))throw new Error('unknown_template_variable');return vars[k];});const id=crypto.randomUUID(),data={name:`Contrat · ${e.data.name}`,agencyId:e.data.agencyId,clientId:e.data.clientId,employeeId:e.data.employeeId,projectId:e.data.projectId,date:vars.date,type:template.data.type,terms,templateId:template.id,templateVersion:template.data.version,version:'1',status:'draft',sourceId:e.id,...(e.kind==='contracts'?{parentId:e.id,type:'amendment'}:{})};await insert(ctx,'contracts',data,id).run();return {id};}
export async function accountSource(ctx:Access,e:Entry){const cfg=(await all(ctx.owner)).find(r=>r.kind==='accountingSettings'&&r.data.status==='active');if(!cfg)throw new Error('accounting_mapping_required');const c=cfg.data;await referenceRows(ctx,'accountingSettings',c);let rows:any[]=[],journalId:string,date=e.data.date??e.data.period+'-01';const line=(accountId:string,debit=0,credit=0)=>({accountId,debit,credit,label:e.data.name});
 if(e.kind==='invoices'&&e.data.status==='issued'){const ht=e.data.subtotal-(e.data.discount||0);rows=[line(c.receivable,e.data.total),line(c.sales,0,ht),line(c.vat,0,e.data.tax),line(c.stampTax,0,e.data.stamp||0)];if(e.data.invoiceType==='creditNote')rows=rows.map(r=>({...r,debit:r.credit,credit:r.debit}));journalId=c.salesJournal;}
 else if(e.kind==='payments'&&e.data.status==='cleared'){if(e.data.direction==='incoming'&&!e.data.clientId||e.data.direction==='outgoing'&&!e.data.supplierId&&!e.data.employeeId)throw new Error('manual_journal_required');rows=e.data.direction==='incoming'?[line(c.cash,e.data.amount),line(c.receivable,0,e.data.amount)]:[line(e.data.employeeId?c.employeePayable:c.payable,e.data.amount),line(c.cash,0,e.data.amount)];journalId=c.cashJournal;}
 else if(e.kind==='receipts'&&e.data.status==='posted'){const order=await record(ctx,e.data.orderId,'orders');let ht=0,tax=0;for(const i of e.data.items){const item=order.data.items.find((r:any)=>r.productId===i.productId);const value=Math.round(i.quantity*(item.price||0));ht+=value;tax+=Math.round(value*(item.tax||0)/100);}rows=[line(c.purchases,ht),line(c.inputVat,tax),line(c.payable,0,ht+tax)];journalId=c.purchaseJournal;}
 else if(e.kind==='payroll'&&e.data.status==='validated'){rows=[line(c.salary,e.data.employerCost),line(c.employeePayable,0,e.data.net),line(c.social,0,(e.data.cnssDeduction||0)+(e.data.unemploymentDeduction||0)+(e.data.employerSocial??e.data.employerCharges)),line(c.tax,0,(e.data.incomeTax||0)+(e.data.solidarity||0)),line(c.staffAdvances,0,e.data.advanceDeduction||0),line(c.employeePayable,0,e.data.otherDeduction||0),line(c.payrollTax,0,e.data.employerTaxes||0)];journalId=c.payrollJournal;}
 else throw new Error('source_not_postable');rows=rows.filter(r=>r.debit||r.credit);journalTotals(rows);const id=e.id+'-accounting';const exists=await db().prepare('SELECT id FROM records WHERE id=? AND owner=?').bind(id,ctx.owner).first();if(exists)return {id};await db().batch([guard(ctx,e),insert(ctx,'journalEntries',{name:e.data.name,agencyId:e.data.agencyId,projectId:e.data.projectId,date,journalId,reference:e.id,sourceId:e.id,rows,status:'posted'},id),update(ctx,e,{...e.data,accountingEntryId:id})]);return {id};}
export async function calculateStudy(ctx:Access,e:Entry){const d=e.data,sizing=solarSizing(d);if(d.latitude===undefined||d.longitude===undefined)throw new Error('coordinates_required');const url=new URL('https://re.jrc.ec.europa.eu/api/v5_3/PVcalc');for(const [k,v] of Object.entries({lat:d.latitude,lon:d.longitude,peakpower:d.capacity,loss:d.losses??14,angle:d.tilt??30,aspect:d.azimuth??0,outputformat:'json'}))url.searchParams.set(k,String(v));let response:Response;try{response=await fetch(url,{signal:AbortSignal.timeout(20000)});}catch{throw new Error('integration_unavailable');}if(!response.ok)throw new Error('integration_unavailable');const result:any=await response.json(),monthly=result.outputs?.monthly?.fixed,total=result.outputs?.totals?.fixed?.E_y;if(!Array.isArray(monthly)||monthly.length!==12||new Set(monthly.map((r:any)=>r.month)).size!==12||monthly.some((r:any)=>!Number.isInteger(r.month)||r.month<1||r.month>12||!Number.isFinite(r.E_m)||r.E_m<0)||!Number.isFinite(total)||total<0)throw new Error('invalid_provider_response');await db().batch([guard(ctx,e),update(ctx,e,{...d,...sizing,productionYear:total,monthly:monthly.map((r:any)=>({month:r.month,production:r.E_m})),yield:total/d.capacity,provider:'PVGIS 5.3',calculatedAt:new Date().toISOString(),calculationAssumptions:{latitude:d.latitude,longitude:d.longitude,capacity:d.capacity,losses:d.losses??14,tilt:d.tilt??30,azimuth:d.azimuth??0}})]);return {ok:true};}
export async function monitoringTicket(ctx:Access,e:Entry){const p=await record(ctx,e.data.projectId,'projects');const lost=e.data.connection==='disconnected',low=!lost&&e.data.expected>0&&e.data.production<e.data.expected*0.7;if(!lost&&!low)throw new Error('no_monitoring_alert');const id=e.id+'-ticket';if(await db().prepare('SELECT id FROM records WHERE id=? AND owner=?').bind(id,ctx.owner).first())return {id};await insert(ctx,'tickets',{name:(lost?'Connexion monitoring interrompue':'Production inférieure à l’attendu')+' · '+p.data.name,clientId:p.data.clientId,projectId:p.id,agencyId:p.data.agencyId,priority:'normal',coverage:'toConfirm',diagnosis:lost?'Vérifier la communication ; la production réelle est inconnue.':'Vérifier météo, ombrage et mesure avant diagnostic.',status:'new',sourceId:e.id},id).run();return {id};}
export async function syncSolarEdge(ctx:Access,projectId:string){assertAdmin(ctx);const p=await record(ctx,projectId,'projects'),{env}=await import('cloudflare:workers'),key=(env as any).SOLAREDGE_API_KEY;
 if(!key||!/^\d+$/.test(p.data.solarEdgeSiteId??''))throw new Error('integration_configuration_required');
 const url=new URL(`https://monitoringapi.solaredge.com/site/${p.data.solarEdgeSiteId}/overview`);url.searchParams.set('api_key',key);
 let response:Response;try{response=await fetch(url,{signal:AbortSignal.timeout(15000),redirect:'manual'});}catch{throw new Error('integration_unavailable');}if(!response.ok)throw new Error('integration_unavailable');const result:any=await response.json(),overview=result.overview;
 if(!overview||!Number.isFinite(overview.lastDayData?.energy)||overview.lastDayData.energy<0||typeof overview.lastUpdateTime!=='string'||!/^\d{4}-\d{2}-\d{2}/.test(overview.lastUpdateTime))throw new Error('invalid_provider_response');
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Tunis'}),id=p.id+'-solaredge-'+today,data={name:`SolarEdge · ${p.data.name} · ${today}`,projectId:p.id,agencyId:p.data.agencyId,date:today,production:overview.lastDayData.energy/1000,source:'solaredge',providerSiteId:p.data.solarEdgeSiteId,observedAt:overview.lastUpdateTime,syncedAt:new Date().toISOString(),connection:overview.lastUpdateTime.slice(0,10)<today?'disconnected':'connected',status:'recorded'};
 const existing=(await all(ctx.owner)).find(r=>r.id===id);if(existing)await db().batch([guard(ctx,existing),update(ctx,existing,data)]);else await insert(ctx,'monitoring',data,id).run();return {id};
}
export async function setupPayroll(ctx:Access){assertAdmin(ctx);if((await all(ctx.owner)).some(r=>r.kind==='payrollPolicies'))throw new Error('payroll_policy_exists');
 const data={name:'Tunisie RSNA 2026 — paramètres à contrôler',startDate:'2026-01-01',endDate:'2026-12-31',employeeRate:9.18,employerRate:16.57,unemploymentEmployee:0.5,unemploymentEmployer:0.5,accidentRate:0,tfpRate:0,foprolosRate:0,professionalRate:10,professionalCap:2000000,cssRate:0.5,cssThreshold:5000000,monthlyHours:208,overtimeMultiplier:1.25,leavePerMonth:1,leaveCap:12,brackets:[{ceiling:5000000,rate:0},{ceiling:10000000,rate:15},{ceiling:20000000,rate:25},{ceiling:30000000,rate:30},{ceiling:40000000,rate:33},{ceiling:50000000,rate:36},{ceiling:70000000,rate:38},{ceiling:0,rate:40}],source:'À contrôler : CNSS RSNA ; LF2025 art.17 et 36 ; LF2026 art.87. Sources : https://www.cnss.tn/ ; https://www.finances.gov.tn/sites/default/files/2024-12/LF2025.pdf ; https://www.finances.gov.tn/sites/default/files/2026-01/115725.pdf . Renseigner accidents, TFP/FOPROLOS, convention, heures, congés, CSS et déductions avant validation.',status:'draft'};
 await insert(ctx,'payrollPolicies',data).run();return {ok:true};
}
export async function setupTemplates(ctx:Access){assertAdmin(ctx);const existing=await all(ctx.owner),batch:D1PreparedStatement[]=[];
 const texts:Record<string,[string,string,string]>={
 sale:['Vente de matériel selon le devis {{reference}}, à {{client}}, montant {{amount}} TND. Les références, quantités, conditions de livraison, garanties et modalités de règlement du devis accepté font partie du contrat. Compléter les délais, exclusions, responsabilités et procédure de réclamation avant approbation.','بيع معدات للحريف {{client}} حسب العرض {{reference}} بقيمة {{amount}} دينار. المراجع والكميات والتسليم والضمان والدفع حسب العرض المقبول. يجب استكمال الآجال والاستثناءات والمسؤوليات والشكوى قبل الاعتماد.','Equipment sale to {{client}} under quote {{reference}}, amount {{amount}} TND. The accepted quote defines items, quantities, delivery, warranties and payment. Complete deadlines, exclusions, responsibilities and claims before approval.'],
 installation:['Installation photovoltaïque {{project}} pour {{client}}, selon le devis {{reference}}. Joindre étude, nomenclature, travaux inclus/exclus, planning, échéancier, garanties et procès-verbal de réception. Définir accès au site, sécurité, travaux préalables, réserves et distinction réception/mise en service. Montant {{amount}} TND.','تركيب منظومة {{project}} للحريف {{client}} حسب العرض {{reference}} بقيمة {{amount}} دينار. ترفق الدراسة والمعدات والأشغال والرزنامة والدفع والضمان ومحضر الاستلام. تحديد الدخول للموقع والسلامة والأشغال الأولية والتحفظات والتشغيل.','PV installation {{project}} for {{client}} under quote {{reference}}, amount {{amount}} TND. Attach study, equipment list, scope, schedule, payments, warranties and acceptance record. Define access, safety, prerequisites, reservations and commissioning.'],
 installment:['Facilité de paiement pour {{client}}, dossier {{reference}}, montant {{amount}} TND. Annexer l’échéancier exact, l’acompte, les échéances et moyens de règlement. Définir les conditions de démarrage, paiements partiels/anticipés, rééchelonnement, frais approuvés et résolution des impayés.','تسهيل دفع للحريف {{client}} للملف {{reference}} بقيمة {{amount}} دينار. يرفق جدول الأقساط والتسبقة ووسائل الدفع. تحديد بداية الأشغال والدفع الجزئي والمسبق وإعادة الجدولة والمصاريف المعتمدة والاستخلاص.','Payment facility for {{client}}, reference {{reference}}, amount {{amount}} TND. Attach deposit and installment schedule with payment methods. Define start conditions, partial/early payments, rescheduling, agreed fees and arrears handling.'],
 maintenance:['Maintenance de {{project}} pour {{client}}. Préciser période, fréquence, prestations, délais d’intervention, exclusions, pièces, prix, facturation et renouvellement. Annexer l’état initial et les garanties ; distinguer maintenance et garantie fabricant.','صيانة {{project}} للحريف {{client}}. تحديد المدة والزيارات والخدمات وآجال التدخل والاستثناءات والقطع والثمن والفوترة والتجديد. ترفق الحالة الأولية والضمانات مع فصل الصيانة عن ضمان المصنع.','Maintenance of {{project}} for {{client}}. Define term, visit frequency, services, response times, exclusions, parts, price, billing and renewal. Attach initial condition and warranties; separate service coverage from manufacturer warranty.'],
 employment:['Contrat de travail de {{employee}}, référence {{reference}}, date {{date}}. Compléter fonction, agence, durée, convention, classification, rémunération, horaires, congés et conditions de fin de contrat selon les règles applicables. Joindre fiche de poste et avenants.','عقد شغل للموظف {{employee}} مرجع {{reference}} بتاريخ {{date}}. استكمال الوظيفة والوكالة والمدة والاتفاقية والتصنيف والأجر والتوقيت والعطل ونهاية العقد حسب القواعد المعتمدة.','Employment contract for {{employee}}, reference {{reference}}, dated {{date}}. Complete role, branch, term, convention, classification, pay, working hours, leave and termination rules. Attach job description and amendments.'],
 subcontract:['Sous-traitance pour {{project}}, référence {{reference}}. Identifier les parties ; définir prestation, matériel fourni, planning, sécurité, qualité, réception, prix, justificatifs et paiement. Distinguer le prestataire d’un salarié de la société.','مناولة للمشروع {{project}} مرجع {{reference}}. تعريف الأطراف والخدمة والمعدات والرزنامة والسلامة والجودة والاستلام والثمن والإثبات والدفع. فصل المتعهد عن موظفي الشركة.','Subcontracting for {{project}}, reference {{reference}}. Identify parties and define service, supplied equipment, schedule, safety, quality, acceptance, price, evidence and payment. Keep contractor status distinct from employment.'],
 amendment:['Avenant au contrat {{reference}}, daté {{date}}. Identifier le contrat initial, le motif et chaque clause modifiée ; préciser effets sur prix, matériel, délai, échéancier ou salaire. Les autres clauses demeurent applicables. Joindre les annexes révisées et recueillir les signatures.','ملحق للعقد {{reference}} بتاريخ {{date}}. تحديد العقد الأصلي والسبب والبنود المعدلة وأثرها على الثمن والمعدات والآجال والأقساط أو الأجر. باقي البنود سارية. ترفق الملاحق المعدلة والتوقيعات.','Amendment to contract {{reference}}, dated {{date}}. Identify original contract, reason and changed clauses, including price, equipment, schedule, installments or salary. Other clauses remain effective. Attach revised annexes and signatures.'],
 termination:['Résiliation du contrat {{reference}}, datée {{date}}. Décrire motif, date d’effet, travaux et matériel déjà fournis, acomptes, créances, restitution, remboursement et obligations restantes. La clôture financière doit être rapprochée des factures et paiements.','فسخ العقد {{reference}} بتاريخ {{date}}. تحديد السبب والسريان والأشغال والمعدات المقدمة والتسبقات والديون والإرجاع والتسديد والالتزامات الباقية. مطابقة التسوية المالية للفواتير والدفعات.','Termination of contract {{reference}}, dated {{date}}. Define reason, effective date, delivered work/equipment, deposits, receivables, returns, refunds and remaining obligations. Reconcile financial settlement against invoices and payments.'],
 };
 for(const [type,clauses] of Object.entries(texts))for(const [i,language] of ['fr','ar','en'].entries()){if(existing.some(r=>r.kind==='contractTemplates'&&r.data.type===type&&r.data.language===language))continue;batch.push(insert(ctx,'contractTemplates',{name:`${type} · ${language} · à finaliser`,type,language,version:'1',terms:clauses[i],status:'draft'}));}if(batch.length)await db().batch(batch);return {ok:true,count:batch.length};
}
