import {validate} from './domain';
export function demoEntries(){const stamp=new Date().toISOString().slice(0,10);const future=new Date(Date.now()+7*86400000).toISOString().slice(0,10);const raw:Array<[string,string,Record<string,any>]>=[
['agencies','demo-agency-1',{name:'Agence Sfax — exemple',code:'SFX-EX',address:'Sfax',manager:'Direction',status:'active'}],
['warehouses','demo-warehouse-1',{name:'Dépôt principal — exemple',code:'DEP-SFX-EX',agencyId:'demo-agency-1',address:'Sfax',status:'active'}],
['warehouses','demo-warehouse-2',{name:'Dépôt secondaire — exemple',code:'DEP-2-EX',agencyId:'demo-agency-1',address:'Sfax',status:'active'}],
['parks','demo-park-1',{name:'Parc Sfax — exemple',agencyId:'demo-agency-1',manager:'Direction',status:'active'}],
['clients','demo-client-1',{name:'Résidence Les Oliviers',phone:'+216 20 000 001',type:'individual',address:'Sfax — données fictives',creditLimit:18000000,status:'active'}],
['clients','demo-client-2',{name:'Atelier Méditerranée',phone:'+216 20 000 002',type:'business',address:'Sousse — données fictives',creditLimit:60000000,status:'active'}],
['clients','demo-client-3',{name:'Ferme El Amal',phone:'+216 20 000 003',type:'farmer',address:'Kairouan — données fictives',status:'active'}],
['sites','demo-site-1',{name:'Villa — Les Oliviers',clientId:'demo-client-1',address:'Sfax',stegRef:'EXEMPLE-001',connection:'singlePhase',status:'active'}],
['suppliers','demo-supplier-1',{name:'Distribution Solaire — exemple',phone:'+216 70 000 000',leadDays:7,status:'active'}],
['employees','demo-employee-1',{name:'Amine — exemple',position:'Chef d’équipe',phone:'+216 20 000 010',salary:1600000,startDate:stamp,skills:'Installation / maintenance',status:'active'}],
['employees','demo-employee-2',{name:'Sara — exemple',position:'Commerciale',salary:1400000,startDate:stamp,status:'active'}],
['vehicles','demo-vehicle-1',{name:'Utilitaire installation — exemple',registration:'EX-001',parkId:'demo-park-1',driverId:'demo-employee-1',agencyId:'demo-agency-1',odometer:24500,serviceKm:30000,insuranceDate:future,status:'active'}],
['projects','demo-project-1',{name:'Villa Les Oliviers · 6 kWc',clientId:'demo-client-1',siteId:'demo-site-1',regime:'outsideProsol',capacity:6,manager:'Amine',dueDate:future,budget:11000000,salePrice:15000000,progress:65,status:'installation'}],
['projects','demo-project-2',{name:'Atelier Méditerranée · 25 kWc',clientId:'demo-client-2',regime:'industrial',capacity:25,dueDate:future,budget:37000000,salePrice:47000000,progress:30,status:'administration',blocker:'Validation du dossier technique'}],
['projects','demo-project-3',{name:'Pompage El Amal · 15 kWc',clientId:'demo-client-3',regime:'pumping',capacity:15,dueDate:future,budget:22000000,salePrice:29000000,progress:15,status:'study'}],
['products','demo-product-1',{name:'Panneau photovoltaïque 550 W',sku:'PV-550-EX',category:'panel',unit:'piece',purchasePrice:290000,salePrice:380000,minStock:10,warrantyMonths:144,status:'active'}],
['products','demo-product-2',{name:'Onduleur hybride 6 kW',sku:'HYB-6-EX',category:'inverter',unit:'piece',purchasePrice:3000000,salePrice:3950000,minStock:3,warrantyMonths:60,status:'active'}],
['products','demo-product-3',{name:'Câble solaire 6 mm²',sku:'CB-6-EX',category:'cable',unit:'meter',purchasePrice:2400,salePrice:3800,minStock:100,status:'active'}],
['movements','demo-movement-1',{name:'Réception panneaux — exemple',productId:'demo-product-1',direction:'stockIn',quantity:32,warehouse:'demo-warehouse-1',date:stamp,reason:'Stock initial fictif',status:'posted'}],
['movements','demo-movement-2',{name:'Réception onduleurs — exemple',productId:'demo-product-2',direction:'stockIn',quantity:2,warehouse:'demo-warehouse-1',date:stamp,reason:'Stock initial fictif',status:'posted'}],
['movements','demo-movement-3',{name:'Réception câbles — exemple',productId:'demo-product-3',direction:'stockIn',quantity:240,warehouse:'demo-warehouse-1',date:stamp,reason:'Stock initial fictif',status:'posted'}],
['quotes','demo-quote-1',{name:'DEV-EX-001',clientId:'demo-client-1',projectId:'demo-project-1',date:stamp,validUntil:future,status:'accepted',lines:[{description:'Installation photovoltaïque 6 kWc — exemple',quantity:1,price:12605042,tax:19}],stamp:0}],
['invoices','demo-invoice-1',{name:'FAC-EX-001',clientId:'demo-client-1',projectId:'demo-project-1',date:stamp,dueDate:future,invoiceType:'invoice',status:'issued',lines:[{description:'Installation photovoltaïque 6 kWc — exemple',quantity:1,price:12605042,tax:19}]}],
['installments','demo-installment-1',{name:'Échéance 1 — FAC-EX-001',clientId:'demo-client-1',projectId:'demo-project-1',invoiceId:'demo-invoice-1',dueDate:stamp,amount:5000000,status:'open'}],
['installments','demo-installment-2',{name:'Échéance 2 — FAC-EX-001',clientId:'demo-client-1',projectId:'demo-project-1',invoiceId:'demo-invoice-1',dueDate:future,amount:10000000,status:'open'}],
['payments','demo-payment-1',{name:'Acompte — exemple',clientId:'demo-client-1',projectId:'demo-project-1',installmentId:'demo-installment-1',direction:'incoming',date:stamp,amount:3000000,method:'transfer',account:'Banque — exemple',status:'cleared'}],
['planning','demo-planning-1',{name:'Pose des panneaux · Les Oliviers',projectId:'demo-project-1',employeeId:'demo-employee-1',date:future,time:'08:30',hours:6,type:'installation',team:'Équipe installation',status:'confirmed'}],
['dossiers','demo-dossier-1',{name:'Dossier atelier — exemple',clientId:'demo-client-2',projectId:'demo-project-2',regime:'industrial',district:'Sousse',nextDate:stamp,missing:'Schéma unifilaire à contrôler',status:'complement'}],
['tickets','demo-ticket-1',{name:'Contrôle de l’onduleur — exemple',clientId:'demo-client-1',projectId:'demo-project-1',priority:'normal',coverage:'toConfirm',dueDate:future,assigned:'Amine',status:'scheduled'}],
['expenses','demo-expense-1',{name:'Transport chantier — exemple',projectId:'demo-project-1',date:stamp,amount:160000,category:'transport',method:'cash',status:'paid'}],
['leads','demo-lead-1',{name:'Maison à La Marsa — exemple',phone:'+216 20 000 050',source:'referral',owner:'Sara',budget:18000000,nextDate:future,status:'visit'}],
];return raw.map(([kind,id,data])=>({kind,id,data:validate(kind,{...(kind!=='agencies'?{agencyId:'demo-agency-1'}:{}),...data})}));}
