import {journalTotals,annualTax,quantity} from './business-domain';
import type {Field} from './modules';
import {byKey} from './modules';
export type Entry={id:string;kind:string;data:Record<string,any>;revision:number;createdAt:string;updatedAt:string;demo:number;archived:number};
export type Line={description:string;quantity:number;price:number;tax:number;productId?:string};
export function toMillimes(value:unknown):number{const s=String(value??'0').trim().replace(',','.');if(!/^\d+(\.\d{1,3})?$/.test(s))throw new Error('invalid_amount');const [whole,decimal='']=s.split('.');const n=Number(whole)*1000+Number(decimal.padEnd(3,'0'));if(!Number.isSafeInteger(n)||n>1e12)throw new Error('invalid_amount');return n;}
export function totals(lines:Line[],discount=0,stamp=0){let ht=0,tax=0;for(const line of lines){if(!line.description.trim()||!Number.isFinite(line.quantity)||line.quantity<=0||!Number.isSafeInteger(line.price)||line.price<0||!Number.isFinite(line.tax)||line.tax<0||line.tax>100)throw new Error('invalid_line');ht+=Math.round(line.price*line.quantity);}if(!Number.isSafeInteger(discount)||discount<0||discount>ht)throw new Error('invalid_discount');for(const line of lines){const n=Math.round(line.price*line.quantity);tax+=Math.round((ht?n*(ht-discount)/ht:0)*line.tax/100);}const total=ht-discount+tax+stamp;if(!Number.isSafeInteger(total)||total>1e12||stamp<0)throw new Error('invalid_total');return {subtotal:ht,tax,total};}
export function payroll(data:Record<string,any>){const gross=(data.base||0)+(data.bonus||0)+(data.allowances||0);const deductions=(data.cnssDeduction||0)+(data.unemploymentDeduction||0)+(data.incomeTax||0)+(data.solidarity||0)+(data.advanceDeduction||0)+(data.otherDeduction||0);return {gross,deductions,net:gross-deductions,employerCost:gross+(data.employerCharges||0)};}
export function monthlyDates(first:string,count:number){const [year,month,day]=first.split('-').map(Number);return Array.from({length:count},(_,i)=>{const target=new Date(Date.UTC(year,month-1+i,1));const last=new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate();return `${target.getUTCFullYear()}-${String(target.getUTCMonth()+1).padStart(2,'0')}-${String(Math.min(day,last)).padStart(2,'0')}`;});}
export function plan(amount:number,count:number,first:string){if(!Number.isSafeInteger(amount)||amount<=0||!Number.isInteger(count)||count<1||count>120)throw new Error('invalid_plan');const dates=monthlyDates(first,count),base=Math.floor(amount/count),remainder=amount%count;if(base<1)throw new Error('invalid_plan');return dates.map((date,i)=>({dueDate:date,amount:base+(i<remainder?1:0)}));}
export function fieldsValue(fields:Field[],input:Record<string,any>):Record<string,any>{const data:Record<string,any>={};for(const field of fields){let v=input[field.key];if(v===undefined||v===null||v===''){if(field.required)throw new Error('required:'+field.key);continue;}if(field.type==='rows'){if(!Array.isArray(v)||v.length>100||(field.required&&!v.length))throw new Error('required:'+field.key);data[field.key]=v.map(row=>fieldsValue(field.columns??[],row));continue;}if(field.type==='number'||field.type==='money'){if(typeof v!=='number'||!Number.isFinite(v)||(v<0&&(field.min===undefined||field.min>=0))||(field.min!==undefined&&v<(field.type==='money'?Math.round(field.min*1000):field.min))||(field.max!==undefined&&v>field.max))throw new Error('invalid:'+field.key);if(field.type==='money'&&!Number.isSafeInteger(v))throw new Error('invalid_amount');data[field.key]=v;}else{if(typeof v!=='string'||v.length>12000)throw new Error('invalid:'+field.key);v=v.trim();if(field.required&&!v)throw new Error('required:'+field.key);if(field.type==='select'&&!field.options?.includes(v))throw new Error('invalid:'+field.key);if(field.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||new Date(v+'T12:00:00Z').toISOString().slice(0,10)!==v))throw new Error('invalid_date');if(field.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))throw new Error('invalid_email');data[field.key]=v;}}return data;}
export function validate(kind:string,input:Record<string,any>){const mod=byKey[kind];if(!mod)throw new Error('invalid_module');const data=fieldsValue(mod.fields,input);
data.status=input.status??mod.states[0];if(!mod.states.includes(data.status))throw new Error('invalid_status');if(kind==='quotes'||kind==='invoices'){if(!Array.isArray(input.lines)||!input.lines.length||input.lines.length>100)throw new Error('required_lines');data.lines=input.lines.map((l:Line)=>({description:String(l.description??'').slice(0,250),quantity:l.quantity,price:l.price,tax:l.tax,...(l.productId?{productId:l.productId}:{})}));Object.assign(data,totals(data.lines,data.discount||0,data.stamp||0));if(kind==='invoices'&&data.invoiceType==='creditNote'&&!data.originalId)throw new Error('original_invoice_required');}
if(['orders','salesOrders'].includes(kind)){data.items.forEach((r:any)=>{if(quantity(r.quantity)<=0)throw new Error('invalid_quantity')});const lines=data.items.map((r:any)=>({description:r.productId,quantity:r.quantity,price:r.price||0,tax:r.tax||0}));Object.assign(data,totals(lines,data.discount||0,data.stamp||0));data.amount=data.total;}
if(kind==='journalEntries')Object.assign(data,journalTotals(data.rows,data.status==='posted'));
if(kind==='payrollPolicies'){annualTax(0,data.brackets);if(!data.monthlyHours||!data.overtimeMultiplier)throw new Error('payroll_policy_required');}
if(kind==='roles'&&data.rules.some((r:any)=>!byKey[r.module]||['users','roles'].includes(r.module)))throw new Error('invalid_permission');
if(kind==='bankProfiles'&&(!data.width||!data.height||data.positions.some((r:any)=>r.x===undefined||r.y===undefined||r.x+(data.offsetX??0)<0||r.y+(data.offsetY??0)<0||r.x+(data.offsetX??0)+r.width>data.width||r.y+(data.offsetY??0)+r.fontSize*25.4/72*1.2>data.height||!r.width||!r.fontSize)))throw new Error('invalid_print_profile');
if(['orders','salesOrders','receipts','deliveryNotes','exitNotes','transferOrders','transits','inventories'].includes(kind)){if(new Set(data.items.map((r:any)=>r.productId)).size!==data.items.length)throw new Error('duplicate_product');data.items.forEach((r:any)=>quantity(r.quantity));}
if(kind==='payroll'){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(data.period))throw new Error('invalid_period');Object.assign(data,payroll(data));if(data.net<0)throw new Error('negative_net');}
if(data.endDate&&data.startDate&&data.endDate<data.startDate)throw new Error('invalid_date_range');if(kind==='missions'&&data.endKm!==undefined&&data.startKm!==undefined&&data.endKm<data.startKm)throw new Error('invalid_odometer');if(kind==='missions'&&data.time&&data.returnTime&&data.returnTime<=data.time)throw new Error('invalid_time_range');if(kind==='effects'&&data.ceiling&&data.amount>data.ceiling)throw new Error('cheque_ceiling');if(kind==='effects'&&data.instrument==='bill'&&!data.dueDate)throw new Error('required:dueDate');if(kind==='effects'&&data.instrument==='cheque'&&!data.validUntil)throw new Error('required:validUntil');if(kind==='payments'&&data.installmentId&&data.direction!=='incoming')throw new Error('invalid_allocation');if(kind==='advances'&&(data.repaid||0)>data.amount)throw new Error('overpaid');return data;}
export const isLocked=(e:Entry)=> (e.kind==='vatReturns'&&e.data.status!=='draft')||(e.kind==='transferOrders'&&!!e.data.lastShipmentAt)||(e.kind==='salesOrders'&&!!e.data.lastDeliveryAt)||e.kind==='messages'||e.kind==='vehicleKeys'||e.kind==='eInvoices'||(e.kind==='minutes'&&e.data.status==='finalized')||(e.kind==='maintenanceJobs'&&e.data.status==='completed')||(e.kind==='withholdings'&&e.data.status!=='draft')||e.kind==='movements'||(e.kind==='contractTemplates'&&e.data.status==='approved')||(e.kind==='orders'&&['partial','received'].includes(e.data.status))||(e.kind==='commissions'&&e.data.status==='paid')||(['receipts','deliveryNotes','exitNotes','clientTransfers','inventories','journalEntries'].includes(e.kind)&&e.data.status==='posted')||(e.kind==='transits'&&e.data.status!=='draft')||(e.kind==='fiscalPeriods'&&e.data.status==='closed')||(e.kind==='payrollPolicies'&&e.data.status==='validated')||(e.kind==='missions'&&e.data.status==='completed')||(e.kind==='invoices'&&e.data.status!=='draft')||(e.kind==='contracts'&&e.data.status==='signed')||(e.kind==='payroll'&&e.data.status==='validated')||(e.kind==='payments'&&e.data.status==='cleared')||e.kind==='installments';
