import tejOperations from './fiscal/tej-operations.json' with {type:'json'};
import type {Module,Field,Words} from './modules';
const w=(fr:string,ar=fr,en=fr):Words=>[fr,ar,en];
const f=(key:string,label:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,label:w(label),type,...extra});
const link=(key:string,label:string,target:string,required=true)=>f(key,label,'link',{target,required});
const select=(key:string,label:string,options:string[],required=true)=>f(key,label,'select',{options,required});
const rows=(key:string,label:string,columns:Field[],required=true)=>f(key,label,'rows',{columns,required});
const date=f('date','Date','date',{required:true}),notes=f('notes','Notes','textarea');
const money=(key:string,label:string,required=false)=>f(key,label,'money',{required});
const num=(key:string,label:string,min=0,max?:number)=>f(key,label,'number',{min,max});
const mod=(key:string,title:string,group:number,fields:Field[],states:string[],columns=['name']):Module=>({key,title:w(title),singular:w(title),group,icon:group===8?'LayoutDashboard':group===9?'Receipt':'ClipboardCheck',fields:[f('name','Désignation','text',{required:true}),...fields,notes],states,columns});
const items=[link('productId','Article','products'),f('quantity','Quantité','number',{required:true,min:.001}),money('price','Prix HT'),num('tax','TVA %',0,100),f('serials','Identifiants unitaires / séries (un par ligne)','textarea')];
export const enterpriseModules:Module[]=[
 mod('bi','BI — aide à la décision',8,[],['active']),
 mod('salesOrders','Bons de commande clients',0,[link('clientId','Client','clients'),link('projectId','Projet','projects',false),date,f('dueDate','Livraison prévue','date'),rows('items','Articles commandés',items),money('discount','Remise HT'),money('stamp','Timbre'),f('conditions','Conditions','textarea')],['draft','confirmed','cancelled'],['name','clientId','date','total']),
 mod('clientTransfers','Transferts de dossiers clients',0,[link('clientId','Client','clients'),link('toAgencyId','Agence destinataire','agencies'),date,f('reason','Motif','textarea',{required:true}),select('includeOpen','Dossiers opérationnels ouverts',['no','yes'])],['draft','posted'],['name','clientId','toAgencyId','date']),
 mod('exitNotes','Bons de sortie',3,[link('warehouse','Dépôt','warehouses'),link('employeeId','Remis à','employees',false),link('projectId','Projet','projects',false),date,f('reason','Motif','textarea',{required:true}),rows('items','Articles sortis',items)],['draft','posted'],['name','warehouse','date']),
 mod('transferOrders','Bons de commande inter-dépôts',3,[link('from','Dépôt expéditeur','warehouses'),link('to','Dépôt destinataire','warehouses'),date,rows('items','Articles demandés',items)],['draft','approved','cancelled'],['name','from','to','date']),
 mod('vehicleKeys','Remise des clés de véhicules',5,[link('vehicleId','Véhicule','vehicles'),link('employeeId','Détenteur des clés','employees'),date,num('startKm','Compteur départ'),f('conditionOut','État / accessoires au départ','textarea'),f('expectedReturn','Retour attendu','date'),f('purpose','Mission / motif','textarea',{required:true})],['draft','held','returned'],['name','vehicleId','employeeId','status']),
 mod('vehicleMaintenance','Plans d’entretien véhicules',5,[link('vehicleId','Véhicule','vehicles'),select('type','Entretien',['oilChange','timingBelt','timingChain','brakes','tyres','battery','inspection','insurance','other']),num('lastKm','Dernier entretien (km)'),f('lastDate','Dernier entretien','date'),num('intervalKm','Intervalle kilométrique'),num('intervalMonths','Intervalle en mois',0,120),num('nextKm','Prochaine échéance (km)'),f('nextDate','Prochaine échéance','date'),money('estimatedCost','Budget prévisionnel'),f('provider','Prestataire'),f('manufacturerRule','Préconisation constructeur','textarea',{required:true})],['active','inactive'],['name','vehicleId','type','nextKm','nextDate']),
 mod('maintenanceJobs','Interventions véhicules',5,[link('vehicleId','Véhicule','vehicles'),link('planId','Plan d’entretien','vehicleMaintenance',false),date,num('odometer','Compteur (km)'),money('amount','Coût',true),f('provider','Prestataire'),f('work','Travaux / pièces remplacées','textarea',{required:true}),num('nextKm','Prochaine échéance (km)'),f('nextDate','Prochaine échéance','date')],['draft','completed'],['name','vehicleId','date','amount']),
 mod('qr','QR & lecteur de stock',3,[],['active']),
 mod('withholdings','Retenues à la source — TEJ',9,[link('paymentId','Paiement','payments'),link('invoiceId','Facture associée','invoices',false),select('direction','Sens',['issued','received']),date,f('reference','Référence du certificat','text',{required:true}),select('operation','Acte certificat',['add','modify','cancel']),f('beneficiaryName','Nom / raison sociale','text',{required:true}),select('identifierType','Type identifiant',['MatriculeFiscal','CIN','Passeport','CarteSejour','AutreIdentifiantFiscal']),f('identifier','Identifiant bénéficiaire','text',{required:true}),select('category','Catégorie',['PM','PP']),select('resident','Résident',['1','0']),f('birthDate','Naissance (CIN / passeport / séjour)','date'),f('country','Pays ISO (ex. TN)'),f('address','Adresse','text',{required:true}),f('email','E-mail bénéficiaire','email',{required:true}),f('phone','Téléphone','text',{required:true}),rows('operations','Opérations TEJ',[select('code','Code opération TEJ',tejOperations.map(o=>o.code)),f('invoiceYear','Année facturation','text',{required:true}),select('cnpc','Convention non double imposition',['0','1']),select('charge','Prise en charge',['0','1']),money('base','Montant HT',true),num('vatRate','TVA %',0,100),num('rate','Retenue IR/IS %',0,100),num('vatWithholdingRate','Retenue TVA %',0,100)])],['draft','validated','submitted'],['name','reference','date','withheld','net']),
 mod('vat','TVA — rapprochement',9,[],['active']),
 mod('vatAdjustments','Ajustements de TVA',9,[date,select('direction','Effet sur TVA à payer',['increase','decrease']),money('amount','TVA ajustée',true),f('reason','Justification fiscale / exclusion / régularisation','textarea',{required:true}),f('reference','Pièce comptable')],['draft','approved'],['name','date','direction','amount']),
 mod('vatReturns','Clôtures et déclarations TVA',9,[f('startDate','Début de période','date',{required:true}),f('endDate','Fin de période','date',{required:true}),money('previousCredit','Crédit reporté antérieur'),f('reference','Référence dépôt')],['draft','validated','submitted'],['name','startDate','endDate','status']),
 mod('eInvoices','Facturation électronique — El Fatoora',9,[link('invoiceId','Facture / avoir','invoices'),f('providerReference','Référence TTN'),f('schemaVersion','Version XSD officielle'),f('validationReport','Rapport de validation','textarea'),f('rejectionReason','Motif de rejet','textarea')],['draft','prepared','signed','submitted','accepted','rejected'],['name','invoiceId','providerReference','status']),
 mod('cashForecast','Cash-flow prévisionnel',8,[date,f('dueDate','Date prévue','date',{required:true}),select('direction','Sens',['incoming','outgoing']),money('amount','Montant',true),num('probability','Probabilité %',0,100),select('scenario','Scénario',['base','optimistic','pessimistic']),f('sourceId','Référence source (ne pas doubler une échéance)'),f('category','Catégorie / budget')],['planned','cancelled'],['name','dueDate','direction','amount']),
 mod('minutes','PV — procès-verbaux de réunion',0,[date,f('time','Heure / durée'),f('location','Lieu','text',{required:true}),select('type','Nature',['management','generalAssembly','board','project','stocktake']),f('chair','Président de séance','text',{required:true}),f('secretary','Secrétaire','text',{required:true}),rows('attendees','Participants',[f('name','Nom','text',{required:true}),f('capacity','Qualité'),select('present','Présence',['present','absent','represented']),f('proxy','Mandataire')]),f('agenda','Ordre du jour','textarea',{required:true}),f('discussion','Déroulement des débats','textarea',{required:true}),rows('resolutions','Résolutions et suivi',[f('text','Résolution','textarea',{required:true}),num('for','Pour'),num('against','Contre'),num('abstentions','Abstentions'),link('employeeId','Responsable','employees',false),f('dueDate','Échéance','date')]),f('quorum','Quorum et règles statutaires'),f('signatureFileId','Identifiant PV signé')],['draft','finalized'],['name','date','chair']),
 mod('notifications','Notifications personnelles',10,[f('recipientEmail','Destinataire','email',{required:true}),f('message','Message','textarea',{required:true}),f('sourceId','Dossier associé'),select('priority','Priorité',['normal','urgent'])],['unread','read'],['name','recipientEmail','status']),
 mod('conversations','Chat employés',10,[rows('members','Participants (e-mails de connexion)',[f('email','E-mail','email',{required:true})])],['active','closed'],['name','status']),
 mod('messages','Messages du chat',10,[link('conversationId','Conversation','conversations'),f('message','Message','textarea',{required:true})],['sent'],['name','conversationId']),
];
export const specialViews=new Set(['bi','qr','vat','conversations','messages','notifications']);
export function extendEnterprise(modules:Module[]){
 modules.push(...enterpriseModules);
 const get=(key:string)=>modules.find(m=>m.key===key)!;
 get('deliveryNotes').fields.push(link('salesOrderId','Bon de commande client','salesOrders',false));
 get('transits').title=w('Transferts & BL inter-dépôts','التحويل والتسليم بين المستودعات','Transfers & inter-warehouse deliveries');
 get('transits').fields.push(link('transferOrderId','Commande inter-dépôts','transferOrders',false));
 get('users').fields.find(f=>f.key==='branches')!.required=false;
 get('users').fields.push(rows('warehouses','Dépôts assignés',[link('warehouseId','Dépôt','warehouses')],false));
 get('users').fields.find(f=>f.key==='email')!.label=w('E-mail de connexion');
 const rule=get('roles').fields.find(f=>f.key==='rules')!;
 rule.columns![0].options=modules.filter(m=>!['users','roles'].includes(m.key)).map(m=>m.key);
 rule.columns!.push(...['add','edit','delete'].map(k=>select(k,({add:'Ajouter',edit:'Modifier',delete:'Supprimer / archiver'} as any)[k],['allow','deny'],false)),select('scope','Périmètre',['all','agencies','warehouses','both'],false));
 get('vehicleCosts').fields.find(f=>f.key==='type')!.options!.push('oilChange','timingBelt','timingChain','brakes');
}
