import {extendModules} from './advanced-modules';
export type Lang = 'fr'|'ar'|'en';
export type Words = [string,string,string];
export const w = (fr:string,ar:string,en:string):Words => [fr,ar,en];
export const text = (v:Words,l:Lang)=>v[l==='fr'?0:l==='ar'?1:2];
export type Field = { key:string; label:Words; type?:'text'|'money'|'number'|'date'|'email'|'textarea'|'select'|'link'|'rows'; columns?:Field[]; required?:boolean; options?:string[]; target?:string; min?:number; max?:number };
export type Module = { key:string; title:Words; singular:Words; group:number; icon:string; fields:Field[]; states:string[]; columns:string[] };
const f=(key:string,fr:string,ar:string,en:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,label:w(fr,ar,en),type,...extra});
const name=f('name','Désignation','التسمية','Name','text',{required:true});
const client=f('clientId','Client','الحريف','Customer','link',{target:'clients',required:true});
const project=f('projectId','Projet','المشروع','Project','link',{target:'projects'});
const employee=f('employeeId','Employé','الموظف','Employee','link',{target:'employees',required:true});
const date=f('date','Date','التاريخ','Date','date',{required:true});
const due=f('dueDate','Échéance','تاريخ الاستحقاق','Due date','date',{required:true});
const amount=f('amount','Montant (TND)','المبلغ (دينار)','Amount (TND)','money',{required:true,min:0.001});
const notes=f('notes','Notes','ملاحظات','Notes','textarea');
const ref=f('reference','Référence','المرجع','Reference');
const supplier=f('supplierId','Fournisseur','المورّد','Supplier','link',{target:'suppliers',required:true});
const M=(key:string,title:Words,singular:Words,group:number,icon:string,fields:Field[],states:string[],columns:string[]):Module=>({key,title,singular,group,icon,fields,states,columns});
export const modules:Module[]=[
M('clients',w('Clients','الحرفاء','Customers'),w('client','حريف','customer'),0,'Users',[name,f('type','Type de client','نوع الحريف','Customer type','select',{options:['individual','business','farmer','reseller']}),f('phone','Téléphone','الهاتف','Phone','text',{required:true}),f('email','E-mail','البريد الإلكتروني','Email','email'),f('address','Adresse','العنوان','Address'),f('taxId','CIN / matricule fiscal','بطاقة التعريف / المعرّف الجبائي','ID / tax number'),f('contact','Contact décisionnaire','المسؤول','Decision maker'),f('creditLimit','Plafond d’encours (TND)','سقف الدين (دينار)','Credit limit (TND)','money'),notes],['active','inactive'],['name','phone','type','creditLimit']),
M('leads',w('Prospects','الفرص التجارية','Leads'),w('prospect','فرصة','lead'),0,'Target',[name,f('phone','Téléphone','الهاتف','Phone'),f('source','Origine','المصدر','Source','select',{options:['phone','website','facebook','whatsapp','referral','showroom']}),f('owner','Commercial responsable','مسؤول المبيعات','Sales representative'),f('budget','Budget (TND)','الميزانية (دينار)','Budget (TND)','money'),f('nextDate','Prochain contact','الاتصال القادم','Next contact','date'),f('lostReason','Motif de perte','سبب خسارة الفرصة','Loss reason'),notes],['new','contacted','visit','proposal','won','lost'],['name','source','owner','nextDate']),
M('sites',w('Sites clients','مواقع الحرفاء','Customer sites'),w('site','موقع','site'),0,'MapPin',[name,client,f('address','Adresse du site','عنوان الموقع','Site address','text',{required:true}),f('gps','Coordonnées GPS','إحداثيات الموقع','GPS coordinates'),f('ownerName','Propriétaire','المالك','Property owner'),f('occupant','Occupant','الشاغل','Occupant'),f('stegSubscriber','Abonné STEG','المشترك بالستاغ','STEG subscriber'),f('stegRef','Référence STEG','مرجع الستاغ','STEG reference'),f('district','District STEG','إقليم الستاغ','STEG district'),f('connection','Raccordement','الربط','Connection','select',{options:['singlePhase','threePhase','mediumVoltage','offGrid']}),notes],['active','inactive'],['name','clientId','address','stegRef']),
M('visits',w('Visites techniques','الزيارات الفنية','Site surveys'),w('visite','زيارة','survey'),1,'ClipboardCheck',[name,client,f('siteId','Site','الموقع','Site','link',{target:'sites',required:true}),date,f('technician','Technicien','الفني','Technician'),f('roof','Type / état de toiture','نوع وحالة السطح','Roof type / condition'),f('surface','Surface utile (m²)','المساحة المفيدة (م²)','Usable area (m²)','number'),f('tilt','Inclinaison (°)','الميل (درجة)','Tilt (°)','number',{min:0,max:90}),f('azimuth','Azimut (°)','السمت (درجة)','Azimuth (°)','number',{min:-180,max:360}),f('shade','Ombrages / obstacles','الظلال والعوائق','Shading / obstacles','textarea'),f('electrical','Tableau / terre / protections','اللوحة والتأريض والحماية','Panel / grounding / protection','textarea'),f('access','Accès / étanchéité / sécurité','الوصول والعزل والسلامة','Access / waterproofing / safety','textarea'),notes],['planned','completed','conditional','infeasible'],['name','clientId','date','technician']),
M('studies',w('Études solaires','الدراسات الشمسية','Solar studies'),w('étude','دراسة','study'),1,'Sun',[name,client,project,f('capacity','Puissance panneaux (kWc)','قدرة الألواح (كيلوواط ذروة)','PV capacity (kWp)','number',{required:true,min:0.1}),f('inverter','Puissance onduleur (kW)','قدرة العاكس (كيلوواط)','Inverter power (kW)','number'),f('battery','Batterie utile (kWh)','البطارية المفيدة (كيلوواط ساعة)','Usable battery (kWh)','number'),f('annualUse','Consommation annuelle (kWh)','الاستهلاك السنوي','Annual consumption (kWh)','number'),f('yield','Productible spécifique estimé (kWh/kWc/an)','الإنتاج النوعي التقديري','Estimated specific yield (kWh/kWp/year)','number'),f('selfUse','Autoconsommation estimée (%)','الاستهلاك الذاتي التقديري (%)','Estimated self-consumption (%)','number',{min:0,max:100}),f('tariff','Coût évité par kWh (TND)','تكلفة الكيلوواط ساعة المتجنّبة','Avoided cost per kWh (TND)','money'),f('investment','Investissement (TND)','الاستثمار (دينار)','Investment (TND)','money'),f('criticalLoads','Circuits secourus / autonomie','الدوائر الاحتياطية والاستقلالية','Backed-up loads / autonomy','textarea'),f('assumptions','Source et hypothèses','المصدر والفرضيات','Source and assumptions','textarea',{required:true}),notes],['draft','review','validated'],['name','clientId','capacity','annualUse']),
M('projects',w('Projets & chantiers','المشاريع والأشغال','Projects & installations'),w('projet','مشروع','project'),1,'PanelsTopLeft',[name,client,f('siteId','Site','الموقع','Site','link',{target:'sites'}),f('regime','Régime du projet','نظام المشروع','Project scheme','select',{options:['prosol','economic','outsideProsol','industrial','offGrid','pumping','extension']}),f('capacity','Puissance (kWc)','القدرة (كيلوواط ذروة)','Capacity (kWp)','number'),f('manager','Responsable','المسؤول','Project manager'),f('startDate','Début prévu','البداية المتوقعة','Planned start','date'),f('dueDate','Livraison prévue','التسليم المتوقع','Target completion','date'),f('budget','Budget de revient (TND)','ميزانية التكلفة (دينار)','Cost budget (TND)','money'),f('salePrice','Vente prévue (TND)','البيع المتوقع (دينار)','Expected sale (TND)','money'),f('progress','Avancement (%)','التقدم (%)','Progress (%)','number',{min:0,max:100}),f('blocker','Point bloquant','سبب التعطيل','Blocker','textarea'),notes],['study','administration','approved','procurement','scheduled','installation','reception','commissioned','suspended','cancelled'],['name','clientId','capacity','dueDate']),
M('quotes',w('Devis','عروض الأسعار','Quotes'),w('devis','عرض أسعار','quote'),0,'FileText',[name,client,project,date,f('validUntil','Valable jusqu’au','صالح إلى','Valid until','date'),f('discount','Remise globale (TND)','التخفيض الجملي (دينار)','Total discount (TND)','money'),f('stamp','Timbre (TND)','الطابع (دينار)','Stamp duty (TND)','money'),f('conditions','Conditions / exclusions','الشروط والاستثناءات','Terms / exclusions','textarea'),notes],['draft','sent','accepted','rejected','expired'],['name','clientId','date','total']),
M('invoices',w('Factures & avoirs','الفواتير والإشعارات الدائنة','Invoices & credit notes'),w('facture','فاتورة','invoice'),2,'Receipt',[name,client,project,date,due,f('invoiceType','Type','النوع','Type','select',{options:['invoice','creditNote']}),f('originalId','Facture d’origine (avoir)','الفاتورة الأصلية','Original invoice','link',{target:'invoices'}),f('payee','Entité facturée / payeur','الجهة المفوترة والدافع','Invoiced entity / payer'),f('discount','Remise (TND)','التخفيض (دينار)','Discount (TND)','money'),f('stamp','Timbre (TND)','الطابع (دينار)','Stamp duty (TND)','money'),notes],['draft','issued','cancelled'],['name','clientId','date','total']),
M('installments',w('Facilités & échéances','التسهيلات والأقساط','Installments'),w('échéance','قسط','installment'),2,'CalendarClock',[name,client,project,f('invoiceId','Facture','الفاتورة','Invoice','link',{target:'invoices',required:true}),due,amount,notes],['open'],['name','clientId','dueDate','amount']),
M('payments',w('Encaissements & règlements','المقبوضات والمدفوعات','Payments'),w('paiement','دفعة','payment'),2,'Wallet',[name,f('direction','Sens du règlement','اتجاه الدفع','Direction','select',{required:true,options:['incoming','outgoing']}),f('clientId','Client','الحريف','Customer','link',{target:'clients'}),f('supplierId','Fournisseur','المورّد','Supplier','link',{target:'suppliers'}),f('employeeId','Employé','الموظف','Employee','link',{target:'employees'}),project,f('installmentId','Échéance client','قسط الحريف','Customer installment','link',{target:'installments'}),date,amount,f('method','Mode de règlement','وسيلة الدفع','Payment method','select',{options:['cash','transfer','cheque','bill','card','bankFunding']}),f('account','Caisse / compte bancaire','الصندوق أو الحساب البنكي','Cash / bank account'),ref,notes],['pending','cleared','rejected','cancelled'],['name','direction','date','amount']),
M('effects',w('Traites & chèques','الكمبيالات والشيكات','Bills & cheques'),w('effet','ورقة دفع','instrument'),2,'Landmark',[name,f('instrument','Instrument','وسيلة الدفع','Instrument','select',{required:true,options:['cheque','bill']}),f('direction','Reçu / émis','وارد أو صادر','Received / issued','select',{options:['incoming','outgoing']}),f('clientId','Client','الحريف','Customer','link',{target:'clients'}),f('supplierId','Fournisseur','المورّد','Supplier','link',{target:'suppliers'}),f('paymentId','Règlement associé','الدفعة المرتبطة','Linked payment','link',{target:'payments'}),f('number','Numéro de l’effet','رقم الورقة','Instrument number','text',{required:true}),f('bank','Banque','البنك','Bank'),f('account','RIB / compte','الحساب البنكي','Bank account'),f('beneficiary','Bénéficiaire','المستفيد','Beneficiary','text',{required:true}),f('drawer','Tireur / émetteur','الساحب','Drawer'),f('drawee','Tiré / débiteur','المسحوب عليه','Drawee'),date,f('dueDate','Échéance de la traite','استحقاق الكمبيالة','Bill maturity','date'),f('validUntil','Validité du chèque','صلاحية الشيك','Cheque validity','date'),amount,f('ceiling','Plafond de la formule (TND)','سقف ورقة الشيك','Cheque ceiling (TND)','money'),f('verification','Vérification / réservation','التحقق والحجز','Verification / reservation','textarea'),f('replacementId','Effet remplacé','الورقة المستبدلة','Replaced instrument','link',{target:'effects'}),notes],['prepared','signed','portfolio','deposited','discounted','cleared','rejected','cancelled','replaced'],['name','instrument','beneficiary','amount']),
M('contracts',w('Contrats & avenants','العقود والملاحق','Contracts & amendments'),w('contrat','عقد','contract'),0,'FileSignature',[name,f('type','Type de contrat','نوع العقد','Contract type','select',{options:['sale','installation','installment','maintenance','employment','subcontract','amendment','termination']}),f('clientId','Client','الحريف','Customer','link',{target:'clients'}),f('employeeId','Employé','الموظف','Employee','link',{target:'employees'}),project,date,f('endDate','Fin / renouvellement','النهاية والتجديد','End / renewal','date'),f('amount','Valeur (TND)','القيمة (دينار)','Value (TND)','money'),f('terms','Clauses et conditions validées','البنود والشروط المعتمدة','Approved clauses and terms','textarea',{required:true}),notes],['draft','review','signed','expired','terminated'],['name','type','date','endDate']),
M('suppliers',w('Fournisseurs','المورّدون','Suppliers'),w('fournisseur','مورّد','supplier'),3,'Truck',[name,f('phone','Téléphone','الهاتف','Phone'),f('email','E-mail','البريد الإلكتروني','Email','email'),f('taxId','Matricule fiscal','المعرّف الجبائي','Tax number'),f('address','Adresse','العنوان','Address'),f('bank','Banque / RIB','البنك والحساب','Bank / account'),f('leadDays','Délai habituel (jours)','الأجل المعتاد (أيام)','Typical lead time (days)','number'),notes],['active','inactive'],['name','phone','email','leadDays']),
M('orders',w('Achats & approvisionnement','الشراء والتزويد','Purchasing'),w('achat','شراء','purchase'),3,'ShoppingCart',[name,supplier,project,date,f('dueDate','Livraison attendue','التسليم المتوقع','Expected delivery','date'),amount,f('shipping','Transport / frais (TND)','النقل والمصاريف','Shipping / fees (TND)','money'),f('received','Réception / écarts','الاستلام والفروقات','Receipt / discrepancies','textarea'),notes],['draft','ordered','partial','received','cancelled'],['name','supplierId','dueDate','amount']),
M('products',w('Catalogue & stock','المنتجات والمخزون','Catalog & inventory'),w('produit','منتج','product'),3,'Package',[name,f('sku','Référence article','مرجع المنتج','SKU','text',{required:true}),f('category','Catégorie','الصنف','Category','select',{options:['panel','inverter','battery','structure','cable','protection','accessory','service','tool']}),f('brand','Marque','العلامة','Brand'),f('tracking','Traçabilité','التتبع','Tracking','select',{options:['quantityOnly','serialTracking']}),f('unit','Unité','الوحدة','Unit','select',{options:['piece','meter','hour','kit']}),f('purchasePrice','Coût unitaire (TND)','تكلفة الوحدة','Unit cost (TND)','money'),f('salePrice','Prix de vente (TND)','سعر البيع','Selling price (TND)','money'),f('minStock','Seuil minimum','الحد الأدنى','Minimum stock','number'),f('warrantyMonths','Garantie (mois)','الضمان (أشهر)','Warranty (months)','number'),f('approval','Éligibilité / source / date','الأهلية والمصدر والتاريخ','Eligibility / source / date'),notes],['active','inactive'],['name','sku','stock','salePrice']),
M('movements',w('Mouvements de stock','حركات المخزون','Stock movements'),w('mouvement','حركة','movement'),3,'ArrowLeftRight',[name,f('productId','Produit','المنتج','Product','link',{target:'products',required:true}),f('direction','Mouvement','الحركة','Movement','select',{required:true,options:['stockIn','stockOut']}),f('quantity','Quantité','الكمية','Quantity','number',{required:true,min:0.001}),f('warehouse','Dépôt','المستودع','Warehouse','link',{target:'warehouses',required:true}),f('serials','Numéros de série (un par ligne)','الأرقام التسلسلية: رقم في كل سطر','Serial numbers (one per line)','textarea'),project,date,f('reason','Motif / bon lié','السبب والوثيقة','Reason / linked document','text',{required:true}),notes],['posted'],['name','productId','direction','quantity']),
M('planning',w('Planning des équipes','تخطيط الفرق','Team schedule'),w('intervention','تدخل','appointment'),1,'CalendarDays',[name,project,f('employeeId','Employé','الموظف','Employee','link',{target:'employees'}),date,f('time','Heure de début','ساعة البداية','Start time'),f('hours','Durée (heures)','المدة (ساعات)','Duration (hours)','number',{min:0.1}),f('type','Type d’intervention','نوع التدخل','Appointment type','select',{options:['survey','installation','reception','maintenance','repair']}),f('team','Équipe / véhicule','الفريق والسيارة','Team / vehicle'),notes],['planned','confirmed','completed','postponed','cancelled'],['name','projectId','date','team']),
M('employees',w('Employés','الموظفون','Employees'),w('employé','موظف','employee'),4,'ContactRound',[name,f('position','Poste','الوظيفة','Position','text',{required:true}),f('phone','Téléphone','الهاتف','Phone'),f('email','E-mail','البريد الإلكتروني','Email','email'),f('cnss','Numéro CNSS','رقم الضمان الاجتماعي','CNSS number'),f('bank','RIB','الحساب البنكي','Bank account'),f('startDate','Date d’entrée','تاريخ الانتداب','Start date','date'),f('endDate','Fin de contrat','نهاية العقد','Contract end','date'),f('contractType','Type de contrat','نوع العقد','Contract type'),f('salary','Salaire brut mensuel (TND)','الأجر الخام الشهري','Monthly gross salary (TND)','money'),f('skills','Compétences / habilitations','المهارات والتأهيل','Skills / authorizations','textarea'),notes],['active','leave','departed'],['name','position','phone','salary']),
M('attendance',w('Présence & heures','الحضور والساعات','Attendance & hours'),w('pointage','حضور','time entry'),4,'Clock',[name,employee,project,date,f('hours','Heures normales','الساعات العادية','Regular hours','number',{required:true,min:0,max:24}),f('overtime','Heures supplémentaires','الساعات الإضافية','Overtime hours','number',{min:0,max:24}),f('cost','Coût affecté au projet (TND)','التكلفة المحملة للمشروع','Project cost (TND)','money'),notes],['draft','approved'],['name','employeeId','date','hours']),
M('leave',w('Congés & absences','العطل والغياب','Leave & absences'),w('demande','طلب','request'),4,'CalendarOff',[name,employee,f('startDate','Début','البداية','Start','date',{required:true}),f('endDate','Fin','النهاية','End','date',{required:true}),f('type','Type d’absence','نوع الغياب','Leave type','select',{options:['paidLeave','unpaidLeave','sick','permission','accident']}),f('days','Jours','الأيام','Days','number',{min:0.5}),notes],['requested','approved','rejected'],['name','employeeId','startDate','endDate']),
M('payroll',w('Paie & bulletins','الأجور والبطاقات','Payroll & payslips'),w('bulletin','بطاقة أجر','payslip'),4,'BadgeEuro',[name,employee,f('period','Période (AAAA-MM)','الفترة (سنة-شهر)','Period (YYYY-MM)','text',{required:true}),f('base','Salaire de base (TND)','الأجر الأساسي','Base salary (TND)','money',{required:true}),f('bonus','Primes / heures sup. (TND)','المنح والساعات الإضافية','Bonuses / overtime (TND)','money'),f('allowances','Indemnités (TND)','التعويضات','Allowances (TND)','money'),f('cnssDeduction','Cotisation salariale (TND)','مساهمة الموظف','Employee contribution (TND)','money'),f('incomeTax','IRPP retenu (TND)','الضريبة المقتطعة','Income tax withheld (TND)','money'),f('solidarity','CSS applicable (TND)','المساهمة التضامنية','Applicable solidarity contribution (TND)','money'),f('advanceDeduction','Avances / prêts déduits (TND)','السلف والقروض المخصومة','Advance / loan deductions (TND)','money'),f('otherDeduction','Absences / autres retenues (TND)','الغياب والخصومات الأخرى','Absence / other deductions (TND)','money'),f('employerCharges','Charges patronales (TND)','مساهمات المشغّل','Employer contributions (TND)','money'),f('calculationSource','Base de calcul / contrôle','مرجع الحساب والتحقق','Calculation source / review','textarea',{required:true}),notes],['draft','reviewed','validated'],['name','employeeId','period','net']),
M('advances',w('Avances & prêts','السلف والقروض','Advances & loans'),w('avance','سلفة','advance'),4,'HandCoins',[name,employee,f('type','Type','النوع','Type','select',{options:['salaryAdvance','employeeLoan','missionAdvance']}),project,date,amount,f('dueDate','Remboursement prévu','السداد المتوقع','Expected repayment','date'),f('repaid','Montant remboursé (TND)','المبلغ المسدد','Repaid amount (TND)','money'),notes],['requested','approved','disbursed','settled','cancelled'],['name','employeeId','type','amount']),
M('expenses',w('Dépenses & frais','المصاريف والنفقات','Expenses'),w('dépense','مصروف','expense'),2,'Coins',[name,project,f('employeeId','Employé','الموظف','Employee','link',{target:'employees'}),date,amount,f('category','Catégorie','الصنف','Category','select',{options:['transport','fuel','accommodation','food','rent','advertising','equipment','bankFees','other']}),f('method','Mode de règlement','وسيلة الدفع','Payment method','select',{options:['cash','transfer','cheque','card']}),f('receipt','Référence justificatif','مرجع الإثبات','Receipt reference'),notes],['draft','approved','paid','rejected'],['name','category','date','amount']),
M('tickets',w('SAV & maintenance','الصيانة وخدمة ما بعد البيع','Service & maintenance'),w('ticket','طلب صيانة','ticket'),1,'Wrench',[name,client,project,f('serial','Numéro de série concerné','الرقم التسلسلي','Affected serial number'),f('priority','Priorité','الأولوية','Priority','select',{options:['low','normal','high','urgent']}),f('coverage','Prise en charge','التكفل','Coverage','select',{options:['manufacturerWarranty','installationWarranty','maintenanceContract','paidService','toConfirm']}),f('assigned','Responsable','المسؤول','Assigned to'),f('dueDate','Intervention prévue','التدخل المتوقع','Planned visit','date'),f('cost','Coût SAV (TND)','تكلفة الصيانة','Service cost (TND)','money'),f('diagnosis','Diagnostic / action / résultat','التشخيص والتدخل والنتيجة','Diagnosis / action / outcome','textarea'),notes],['new','diagnosis','scheduled','parts','resolved','closed'],['name','clientId','priority','dueDate']),
M('dossiers',w('Dossiers STEG / ANME','ملفات الستاغ والوكالة','STEG / ANME files'),w('dossier','ملف','file'),1,'FolderCheck',[name,client,project,f('regime','Régime','النظام','Scheme','select',{options:['prosol','economic','outsideProsol','industrial']}),f('district','District / interlocuteur','الإقليم والمسؤول','District / contact'),f('reference','Référence de dépôt','مرجع الإيداع','Submission reference'),f('date','Date de dépôt','تاريخ الإيداع','Submission date','date'),f('nextDate','Prochaine relance','المتابعة القادمة','Next follow-up','date'),f('funding','Financement / subvention','التمويل والدعم','Funding / subsidy','textarea'),f('missing','Pièces manquantes / réserves','الوثائق الناقصة والتحفظات','Missing documents / reservations','textarea'),notes],['incomplete','ready','submitted','complement','approved','refused','reception','commissioned'],['name','projectId','district','nextDate']),
M('reservations',w('Réservations de stock','حجوزات المخزون','Stock reservations'),w('réservation','حجز','reservation'),3,'PackageCheck',[name,project,f('productId','Produit','المنتج','Product','link',{target:'products',required:true}),f('warehouse','Dépôt','المستودع','Warehouse','link',{target:'warehouses',required:true}),f('quantity','Quantité réservée','الكمية المحجوزة','Reserved quantity','number',{required:true,min:0.001}),date,notes],['reserved','released'],['name','projectId','productId','quantity']),
M('kitComponents',w('Composition des kits','مكونات الأطقم','Kit components'),w('composant','مكوّن','component'),3,'Boxes',[name,f('kitId','Produit kit','منتج الطقم','Kit product','link',{target:'products',required:true}),f('componentId','Composant','المكوّن','Component','link',{target:'products',required:true}),f('quantity','Quantité par kit','الكمية لكل طقم','Quantity per kit','number',{required:true,min:0.001}),notes],['active','inactive'],['name','kitId','componentId','quantity']),
M('agencies',w('Agences de vente','وكالات البيع','Sales branches'),w('agence','وكالة','branch'),5,'Building2',[name,f('code','Code agence','رمز الوكالة','Branch code','text',{required:true}),f('address','Adresse','العنوان','Address'),f('manager','Responsable','المسؤول','Manager'),f('phone','Téléphone','الهاتف','Phone'),notes],['active','inactive'],['name','code','manager','address']),
M('warehouses',w('Dépôts & emplacements','المستودعات والأماكن','Warehouses & locations'),w('dépôt','مستودع','warehouse'),5,'Warehouse',[name,f('code','Code dépôt','رمز المستودع','Warehouse code','text',{required:true}),f('address','Adresse','العنوان','Address'),f('manager','Responsable magasin','مسؤول المخزن','Warehouse manager'),f('locations','Zones / emplacements','المناطق والأماكن','Zones / bins','textarea'),notes],['active','inactive'],['name','code','manager','address']),
M('parks',w('Parcs de véhicules','أساطيل السيارات','Vehicle fleets'),w('parc','أسطول','fleet'),5,'ParkingCircle',[name,f('address','Adresse / stationnement','العنوان وموقف السيارات','Address / parking'),f('manager','Responsable parc','مسؤول الأسطول','Fleet manager'),notes],['active','inactive'],['name','manager','address']),
M('vehicles',w('Véhicules','السيارات','Vehicles'),w('véhicule','سيارة','vehicle'),5,'Car',[name,f('registration','Immatriculation','الترقيم','Registration','text',{required:true}),f('parkId','Parc','الأسطول','Fleet','link',{target:'parks',required:true}),f('driverId','Conducteur affecté','السائق المعين','Assigned driver','link',{target:'employees'}),f('type','Type / marque / modèle','النوع والعلامة والطراز','Type / make / model'),f('odometer','Kilométrage actuel','عداد الكيلومترات','Current odometer','number'),f('insuranceDate','Fin assurance','نهاية التأمين','Insurance expiry','date'),f('inspectionDate','Visite technique','الفحص الفني','Inspection due','date'),f('taxDate','Vignette / renouvellement','معلوم الجولان والتجديد','Road tax / renewal','date'),f('serviceKm','Prochain entretien (km)','الصيانة القادمة (كم)','Next service (km)','number'),f('serviceDate','Prochain entretien (date)','تاريخ الصيانة القادمة','Next service date','date'),f('ownership','Propriété / leasing / location','ملكية أو إيجار','Owned / leased / rented'),notes],['active','maintenance','unavailable','inactive'],['name','registration','parkId','odometer']),
M('missions',w('Missions & trajets','المهمات والتنقلات','Vehicle missions'),w('mission','مهمة','mission'),5,'Route',[name,f('vehicleId','Véhicule','السيارة','Vehicle','link',{target:'vehicles',required:true}),employee,project,date,f('time','Départ (HH:MM)','المغادرة','Start (HH:MM)'),f('returnTime','Retour (HH:MM)','العودة','Return (HH:MM)'),f('destination','Destination / trajet','الوجهة والمسار','Destination / route','text',{required:true}),f('startKm','Compteur départ','العداد عند المغادرة','Starting odometer','number'),f('endKm','Compteur retour','العداد عند العودة','Ending odometer','number'),f('cost','Frais de mission (TND)','مصاريف المهمة','Mission cost (TND)','money'),notes],['planned','confirmed','completed','cancelled'],['name','vehicleId','date','destination']),
M('vehicleCosts',w('Carburant & entretien','الوقود وصيانة السيارات','Fuel & maintenance'),w('opération véhicule','عملية سيارة','vehicle operation'),5,'Fuel',[name,f('vehicleId','Véhicule','السيارة','Vehicle','link',{target:'vehicles',required:true}),project,date,f('type','Type d’opération','نوع العملية','Operation type','select',{options:['fuel','service','repair','insurance','inspection','tyres','roadTax','accident']}),amount,f('odometer','Kilométrage','الكيلومترات','Odometer','number'),f('liters','Carburant (litres)','الوقود (لتر)','Fuel (liters)','number'),f('nextDate','Prochaine échéance','الموعد القادم','Next due date','date'),f('provider','Prestataire / station','المزود أو المحطة','Provider / station'),notes],['draft','approved','paid'],['name','vehicleId','type','amount']),
];
extendModules(modules);
for(const m of modules){if(m.key!=='agencies')m.fields.splice(1,0,f('agencyId','Agence','الوكالة','Branch','link',{target:'agencies'}));}
export const byKey=Object.fromEntries(modules.map(m=>[m.key,m]));
export const groups=[w('Commercial','المبيعات','Sales'),w('Opérations solaires','العمليات الشمسية','Solar operations'),w('Finance opérationnelle','المالية التشغيلية','Operational finance'),w('Achats & stock','الشراء والمخزون','Purchasing & inventory'),w('Ressources humaines','الموارد البشرية','Human resources'),w('Agences & parc','الوكالات والأسطول','Branches & fleet'),w('Comptabilité générale','المحاسبة العامة','General accounting'),w('Accès salariés','حسابات الموظفين','Staff access')];
