import type {Entry} from './domain';
import {xmlEscape} from './fiscal';
import {BT_TEMPLATE,MT_TEMPLATE,STEG_SOURCE,stegChecklist} from './technical-domain';
import {legalChecklist,STEG_LEGAL_REFERENCES} from './steg-regulatory';
type FileMeta={id:string;record_id:string;filename:string};
const esc=(s:unknown)=>xmlEscape(String(s??''));
const value=(s:unknown)=>s!==undefined&&s!==null&&s!==''?esc(s):'<strong class="missing">À compléter</strong>';
const rows=(entries:[string,unknown][])=>'<table>'+entries.map(([key,v])=>`<tr><th>${esc(key)}</th><td>${value(v)}</td></tr>`).join('')+'</table>';
const page=(title:string,body:string)=>`<section class="page"><h2>${esc(title)}</h2>${body}</section>`;
const signature=(label:string)=>`<div class="signature">${esc(label)} — nom, qualité, date, signature et cachet : <span>À signer</span></div>`;
export function dossierReadiness(e:Entry,records:Entry[],files:FileMeta[]){
 const p=records.find(r=>r.kind==='projects'&&r.id===e.data.projectId),c=records.find(r=>r.kind==='clients'&&r.id===e.data.clientId),site=records.find(r=>r.kind==='sites'&&r.id===p?.data.siteId),missing:string[]=[];
 for(const [title,v] of [['Régime juridique',p?.data.legalRegime],['Client',c?.data.name],['Identité client (CIN ou matricule fiscal)',c?.data.cin||c?.data.taxId],['Adresse site',site?.data.address],['GPS site',site?.data.gps],['Abonnement STEG',site?.data.stegRef],['Puissance souscrite kVA',site?.data.subscribedKva],['District STEG',site?.data.district],['Installateur qualifié et référence ANME',e.data.installerQualification],['Validation juridique',e.data.legalReviewFileId],['Responsable juridique',e.data.legalReviewer]] as [string,unknown][]){if(!v)missing.push(title);}
 const annexes=e.data.annexes??[];for(const title of e.data.checklist??stegChecklist(e.data.voltage??'BT')){if(!annexes.some((a:any)=>a.title===title&&files.some(f=>f.id===a.fileId)))missing.push(title);}
 return missing;
}
export function renderStegDossier(e:Entry,records:Entry[],files:FileMeta[],company:Record<string,string>){
 const p=records.find(r=>r.id===e.data.projectId)!,c=records.find(r=>r.id===e.data.clientId)!,site=records.find(r=>r.id===p.data.siteId),voltage=e.data.voltage??'BT';
 const plans=records.filter(r=>r.kind==='technicalPlans'&&r.data.dossierId===e.id),plan=plans.find(r=>r.data.status==='reviewed')??plans.find(r=>r.data.snapshot||r.data.studySnapshot),s=plan?.data.snapshot??plan?.data.studySnapshot,d=plan?.data??{};
 const studies=records.filter(r=>r.kind==='studies'&&r.data.projectId===p.id),study=studies.find(r=>r.data.status==='validated')??studies[0];
 const check=records.find(r=>r.id===e.data.checkId),missing=dossierReadiness(e,records,files),template=voltage==='BT'?BT_TEMPLATE:voltage==='MT'?MT_TEMPLATE:STEG_SOURCE;
 const attached=(id:string)=>{const f=files.find(f=>f.id===id);return f?`<a href="/api/files?id=${encodeURIComponent(f.id)}">${esc(f.filename)}</a>`:'<strong class="missing">Pièce absente / inaccessible</strong>';};
 const networkName=voltage==='MT'?'MT / HTA':voltage==='HT'?'HT — étude spécifique':'BT';
 let html=page('1. Bordereau de préparation et contrôle',`<h1>${esc(e.data.name)}</h1><p class="notice">Pack prérempli à partir des fiches liées. Les pièces signées et les formulaires officiels doivent être contrôlés avant dépôt. Ce pack ne constitue ni une approbation STEG ni une déclaration automatique de conformité.</p>${rows([['Réseau',networkName],['Régime juridique',p.data.legalRegime],['Client',c.data.name],['Chantier',p.data.name],['Puissance dossier',String(e.data.capacity??p.data.capacity)+' kWc'],['État logiciel',e.data.status],['Référence dossier',e.data.reference]])}<h3>Informations / pièces manquantes (${missing.length})</h3><ul>${missing.map(v=>`<li>${esc(v)}</li>`).join('')||'<li>Aucune rubrique de la liste de contrôle manquante ; validation finale du signataire requise.</li>'}</ul><p><a href="${template}" rel="noreferrer">Formulaire et dossier type officiels STEG (${networkName})</a></p>`);
 html+=page('2. Demande de raccordement — à signer',`<p>À Monsieur / Madame le Chef du district STEG ${value(site?.data.district??e.data.district)}</p><p>Objet : demande d’approbation du dossier et de raccordement d’une installation photovoltaïque au réseau ${esc(networkName)}.</p><p>Je soussigné(e), ${value(c.data.name)}, sollicite l’examen du dossier de l’installation projetée sur le site ${value(site?.data.address)}, sous l’abonnement STEG ${value(site?.data.stegRef)}, pour une puissance PV de ${value(e.data.capacity??p.data.capacity)} kWc. Le régime de production proposé est ${value(p.data.legalRegime)}.</p><p>Les études et pièces du bordereau annexé sont soumises à votre examen. Les réserves, accords et conditions de raccordement doivent être confirmés par vos services.</p>${rows([['Adresse demandeur',c.data.address],['CIN / matricule fiscal',c.data.cin||c.data.taxId],['Téléphone',c.data.phone],['Email',c.data.email],['District',site?.data.district],['Mandataire / propriétaire',site?.data.ownerName],['Lieu et date',e.data.date]])}${signature('Demandeur / mandataire')}`);
 html+=page('3. Fiche d’identification de l’installation — données à reporter sur le formulaire officiel',rows([['Demandeur',c.data.name],['CIN / matricule fiscal',c.data.cin||c.data.taxId],['Abonné STEG',site?.data.stegSubscriber],['Référence abonnement',site?.data.stegRef],['Adresse installation',site?.data.address],['GPS',site?.data.gps],['Propriétaire',site?.data.ownerName],['Occupant',site?.data.occupant],['Raccordement existant',site?.data.connection],['Tension réseau kV',site?.data.gridKv],['Puissance souscrite kVA',site?.data.subscribedKva],['Puissance PV demandée kWc',e.data.capacity??p.data.capacity],['Installateur',company.name],['Adresse installateur',company.address],['Matricule installateur',company.taxId],['Qualification / agrément ANME',e.data.installerQualification],['Modules',records.find(r=>r.id===d.moduleProductId)?.data.name],['Onduleurs',records.find(r=>r.id===d.inverterProductId)?.data.name]])+signature('Installateur et demandeur'));
 html+=page('4. Mémoire descriptif et étude énergétique',rows([['Implantation',site?.data.address],['GPS',site?.data.gps],['Puissance PV réelle kWc',s?.actualKwc],['Nombre de panneaux',s?.count],['Puissance apparente onduleur kVA',d.inverterKva],['Puissance unitaire W',d.moduleW],['Puissance onduleur AC kW',d.inverterKw],['Surface toiture relevée',s?`${s.roofWidth} × ${s.roofLength} m`:undefined],['Inclinaison °',d.tilt],['Structure',d.support],['Relevé coté',d.surveyFileId?files.find(f=>f.id===d.surveyFileId)?.filename:undefined],['Consommation annuelle kWh',study?.data.annualUse],['Productible spécifique kWh/kWc/an',study?.data.yield],['Production annuelle estimée kWh',study?.data.capacity&&study?.data.yield?Math.round(study.data.capacity*study.data.yield):undefined],['Autoconsommation estimée %',study?.data.selfUse],['Logiciel de simulation',study?.data.simulationTool],['Météo et période',study?.data.weatherSource],['PR',study?.data.performanceRatio],['P50 kWh/an',study?.data.p50],['P90 kWh/an',study?.data.p90],['Rapport simulation',study?.data.simulationFileId?files.find(f=>f.id===study.data.simulationFileId)?.filename:undefined],['Source / hypothèses de l’étude',study?.data.assumptions]])+'<p>Une simulation issue d’un logiciel reconnu, ses pertes et hypothèses, doit être jointe. Les estimations saisies ne remplacent pas cette étude.</p>'+signature('Auteur de l’étude'));
 html+=page('5. Implantation, structure et chaînes électriques',s?`<p>Plan : ${esc(plan!.data.name)} — ${esc(plan!.data.status)}.</p><p><a href="/api/technical?id=${encodeURIComponent(plan!.id)}&format=dxf">Plan CAO DXF (mm), implantation, rails et circuits</a></p>${rows([['Rails total m',s.railMeters],['Ancrages à vérifier',s.anchors],['Matériau',s.support],['Voc panneau à froid V',s.coldVoc],['Vmp panneau à chaud V',s.hotVmp],['Isc à chaud A',s.hotIsc],['Pdc/Pac',s.ratio],['MPPT disponibles',d.mpptCount],['Entrées par MPPT',d.stringsPerMppt],['Modules série min / max',s.minSeries+' / '+s.maxSeries]])}<h3>Répartition des chaînes</h3><table><tr><th>Chaîne</th><th>Modules en série</th><th>Voc froid chaîne V</th><th>Vmp chaud chaîne V</th></tr>${s.series.map((n:number,i:number)=>`<tr><td>${i+1}</td><td>${n}</td><td>${(n*s.coldVoc).toFixed(2)}</td><td>${(n*s.hotVmp).toFixed(2)}</td></tr>`).join('')}</table><ul>${s.warnings.map((w:string)=>`<li>${esc(w)}</li>`).join('')}</ul><p>Note de calcul structure et validation : ${plan!.data.reviewFileId?attached(plan!.data.reviewFileId):'<strong class="missing">À joindre</strong>'}</p>`:'<p class="missing">Plan technique coté, calculs électriques et note structure à compléter. La génération CAO se fait après enregistrement de l’accord STEG, ou les plans d’étude préalables doivent être joints au dossier.</p>');
 html+=page('6. Câbles, protections et schémas',s?`<table><tr><th>Circuit</th><th>Type</th><th>Section mm²</th><th>Trajet m</th><th>Quantité m</th><th>Chute %</th></tr>${s.routes.map((r:any)=>`<tr><td>${esc(r.name)}</td><td>${esc(r.kind)}</td><td>${r.section}</td><td>${r.length.toFixed(3)}</td><td>${r.meters}</td><td>${r.dropPercent.toFixed(3)}</td></tr>`).join('')}</table><p><a href="/api/technical?id=${encodeURIComponent(plan!.id)}&format=unifilar">Schéma unifilaire de principe prérempli — à valider et signer</a></p><p>Les protections AC/DC, mise à la terre, sélectivité, court-circuit et parafoudres doivent être dimensionnés et indiqués dans le schéma unifilaire signé. Les calculs résistifs préliminaires ne les remplacent pas.</p>${rows([['Note protections',e.data.protectionNotes],['Note terre',e.data.earthingNotes]])}${signature('Ingénieur / bureau de contrôle')}`:'<p class="missing">Tracés, sections et schéma unifilaire signés à joindre.</p>');
 html+=page('7. Raccordement et cadre juridique',rows([['Régime juridique',p.data.legalRegime],['Réseau',networkName],['Point de livraison / poste',e.data.deliveryPoint],['Étude raccordement / convention',e.data.connectionStudyReference],['Vérification paiement',check?.data.result],['Date vérification',check?.data.date],['Solde impayé en TND',check?.data.balance!==undefined?(check.data.balance/1000).toFixed(3):undefined],['Référence décision STEG',e.data.reference],['Date accord',e.data.approvalDate],['Validateur juridique',e.data.legalReviewer]])+`<ul>${(e.data.legalChecklist??legalChecklist(voltage,p.data.legalRegime)).map((s:string)=>`<li>${esc(s)}</li>`).join('')}</ul><h3>Références réglementaires vérifiées le 10/10/2026</h3><ul>${STEG_LEGAL_REFERENCES.map(r=>`<li><a href="${r.url}" rel="noreferrer">${esc(r.title)}</a></li>`).join('')}</ul><p>Le responsable doit vérifier l’applicabilité, les avenants et exigences propres au projet. Le choix BT / MT / HT est confirmé par les données du raccordement et la décision STEG.</p>`);
 html+=page('8. Bordereau des annexes et signatures',`<table><tr><th>Pièce attendue</th><th>Annexe sélectionnée</th></tr>${(e.data.checklist??stegChecklist(voltage)).map((title:string)=>{const a=(e.data.annexes??[]).find((a:any)=>a.title===title);return `<tr><td>${esc(title)}</td><td>${a?attached(a.fileId):'<strong class="missing">À joindre</strong>'}</td></tr>`;}).join('')}</table><h3>Autres pièces liées disponibles</h3><ul>${files.map(f=>`<li>${attached(f.id)}</li>`).join('')}</ul>${signature('Demandeur')}${signature('Installateur')}${signature('Ingénieur / bureau de contrôle')}`);
 return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>${esc(e.data.name)}</title><style>body{font:14px Arial;color:#132b43;margin:0;background:#eef2f7}.page{box-sizing:border-box;background:white;max-width:210mm;margin:15px auto;padding:16mm;min-height:277mm}table{border-collapse:collapse;width:100%;margin:15px 0}td,th{border:1px solid #cbd5e1;padding:8px;text-align:left;vertical-align:top}th{background:#f1f5f9}.missing{color:#a33900}.notice{padding:14px;background:#fff5dd}.signature{border-top:1px solid #999;margin-top:28px;padding-top:12px;min-height:60px}.signature span{display:block;color:#777}p,li{line-height:1.6}a{color:#124f93}@page{size:A4;margin:0}@media print{body{background:white}.page{margin:0;max-width:none;break-after:page;min-height:0}.page:last-child{break-after:auto}a{color:inherit;text-decoration:none}}</style></head><body>${html}</body></html>`;
}
