import type {Module,Field,Words} from './modules';
const words=(fr:string,ar:string,en:string):Words=>[fr,ar,en];
const f=(key:string,fr:string,ar:string,en:string,type:Field['type']='text',extra:Partial<Field>={}):Field=>({key,label:words(fr,ar,en),type,...extra});
const num=(key:string,fr:string,ar:string,en:string,min=0,max=100000)=>f(key,fr,ar,en,'number',{min,max});
const link=(key:string,fr:string,ar:string,en:string,target:string,required=false)=>f(key,fr,ar,en,'link',{target,required});
const select=(key:string,fr:string,ar:string,en:string,options:string[])=>f(key,fr,ar,en,'select',{options});
const client=link('clientId','Client','الحريف','Customer','clients',true),project=link('projectId','Chantier','المشروع','Project','projects',true);
const date=f('date','Date','التاريخ','Date','date',{required:true});
const mod=(key:string,fr:string,ar:string,en:string,group:number,fields:Field[],states:string[],columns:string[]):Module=>({key,title:words(fr,ar,en),singular:words(fr,ar,en),group,icon:group===3?'Boxes':group===2?'Receipt':'Wrench',fields:[f('name','Désignation','التسمية','Name','text',{required:true}),...fields,f('notes','Notes','ملاحظات','Notes','textarea')],states,columns});
export function extendTechnical(modules:Module[]){
 const get=(key:string)=>modules.find(m=>m.key===key)!;
 get('sites').fields.find(f=>f.key==='connection')!.options!.push('highVoltage');
 get('sites').fields.push(num('subscribedKva','Puissance souscrite (kVA)','القدرة المتعاقد عليها kVA','Subscribed apparent power (kVA)',0.1,100000),num('gridKv','Tension réseau (kV)','جهد الشبكة','Grid voltage (kV)',0.1,500));
 get('projects').fields.push(num('inverterKva','Puissance apparente onduleurs (kVA)','قدرة العواكس الظاهرية','Total inverter apparent rating (kVA)',0.1,100000),select('legalRegime','Régime juridique confirmé','النظام القانوني','Confirmed legal regime',['onSiteSelfConsumption','remoteSelfConsumption','authorization','concession']));
 get('studies').fields.push(select('simulationTool','Logiciel / source simulation','برنامج المحاكاة','Simulation tool / source',['PVsyst','PVGIS','other']),f('simulationVersion','Version et référence projet','إصدار ومرجع المشروع','Version and project reference'),f('weatherSource','Station / données météo et période','مصدر ومدة بيانات الطقس','Weather data source and period'),num('azimuth','Azimut (° depuis le sud)','السمت من الجنوب','Azimuth (degrees from south)',-180,180),num('tilt','Inclinaison (°)','الميل','Tilt (degrees)',0,90),num('p50','Énergie P50 (kWh/an)','إنتاج P50','P50 energy (kWh/year)',0),num('p90','Énergie P90 (kWh/an)','إنتاج P90','P90 energy (kWh/year)',0),f('simulationFileId','Rapport simulation joint','تقرير المحاكاة','Attached simulation report ID'),f('shadingFileId','Étude ombrages jointe','دراسة الظلال','Attached shading study ID'),f('uncertaintyNotes','Justification des incertitudes P50 / P90','فرضيات عدم اليقين','P50 / P90 uncertainty basis','textarea'),f('lossNotes','Pertes détaillées / hypothèses','الخسائر والفرضيات','Detailed losses / assumptions','textarea'),f('simulationMonthly','Résultats mensuels importés de simulation','نتائج المحاكاة الشهرية','Imported monthly simulation results','rows',{columns:[num('month','Mois (1–12)','الشهر','Month (1–12)',1,12),num('energy','Production (kWh)','الإنتاج','Energy (kWh)',0),num('irradiation','Irradiation plan (kWh/m²)','الإشعاع في مستوى اللوح','Plane irradiation (kWh/m²)',0)]}));
 get('clients').fields.push(num('desiredKwc','Puissance souhaitée (kWc)','القدرة المطلوبة (كيلوواط ذروة)','Requested capacity (kWp)',0.1,100000));
 get('sites').fields.push(num('subscribedKw','Puissance souscrite (kW)','القدرة المتعاقد عليها','Subscribed power (kW)',0.1),f('stegConsentFileId','Justificatif consentement STEG (ID pièce)','وثيقة موافقة الستاغ','STEG consent attachment ID'),f('stegConsentUntil','Consentement valable jusqu’au','الموافقة إلى','Consent valid until','date'));
 get('dossiers').fields.push(link('checkId','Vérification paiement STEG','التحقق من خلاص الستاغ','STEG payment check','stegChecks'),select('voltage','Réseau du dossier','شبكة الملف', 'Dossier network',['BT','MT','HT']),num('capacity','Puissance dossier (kWc)','قدرة الملف','Dossier capacity (kWp)'),f('approvalFileId','Décision STEG jointe (ID)','وثيقة قرار الستاغ','STEG decision attachment ID'),f('approvalDate','Date décision STEG','تاريخ قرار الستاغ','STEG decision date','date'));
 get('dossiers').fields.push(f('installerQualification','Qualification installateur ANME','تأهيل المركّب لدى الوكالة','ANME installer qualification'),f('deliveryPoint','Point de livraison / poste','نقطة التسليم','Delivery point / substation'),f('connectionStudyReference','Référence étude raccordement','مرجع دراسة الربط','Connection study reference'),f('protectionNotes','Protections AC/DC et sélectivité','الحمايات والانتقائية','AC/DC protection and discrimination','textarea'),f('earthingNotes','Terre / mesures et protections','التأريض والقياسات','Earthing measurements and protection','textarea'),f('legalReviewFileId','Validation juridique jointe','وثيقة المصادقة القانونية','Legal review attachment ID'),f('legalReviewer','Responsable validation juridique','مسؤول المصادقة القانونية','Legal reviewer'),f('annexes','Pièces du dossier','وثائق الملف','Dossier annexes','rows',{columns:[f('title','Pièce / rubrique','الوثيقة','Document title','text',{required:true}),f('fileId','Pièce jointe (ID)','رمز الوثيقة','Attachment ID','text',{required:true})]}));
 get('suppliers').fields.push(select('rsEnabled','Retenue fournisseur','اقتطاع المورّد','Supplier withholding',['no','yes']),num('rsRate','Taux IR/IS approuvé %','نسبة الاقتطاع المعتمدة','Approved IR/IS rate %',0,100),num('rsVatRate','Retenue sur TVA %','اقتطاع الأداء %','VAT withholding %',0,100),f('rsCode','Code opération TEJ','رمز عملية TEJ','TEJ operation code'),select('rsCategory','Catégorie fiscale','الصنف الجبائي','Tax category',['PM','PP']),select('rsResident','Résidence fiscale','الإقامة الجبائية','Tax residence',['1','0']),f('rsPolicySource','Fondement / validation comptable','مرجع المصادقة المحاسبية','Accountant-approved policy source','textarea'));
 get('payments').fields.push(link('supplierInvoiceId','Facture fournisseur réglée','فاتورة المورّد','Supplier invoice','supplierInvoices'));
 get('accountingSettings').fields.push(link('supplierWithholding','Retenues fournisseur à reverser','اقتطاع المورّد المستحق','Supplier withholding payable','accounts'));
 const geometry=[num('roofWidth','Largeur toiture (m)','عرض السطح (م)','Roof width (m)',0.1,1000),num('roofLength','Longueur toiture (m)','طول السطح (م)','Roof length (m)',0.1,1000),num('edge','Recul périphérique (m)','الابتعاد عن الحواف','Edge setback (m)',0,20),num('moduleWidth','Largeur panneau (m)','عرض اللوح','Module width (m)',0.1,5),num('moduleLength','Longueur panneau (m)','طول اللوح','Module length (m)',0.1,5),num('moduleW','Puissance panneau (W)','قدرة اللوح (واط)','Module rating (W)',1,2000),num('columns','Panneaux par rangée','ألواح في الصف','Modules per row',1,200),num('gap','Écart entre panneaux (m)','الفراغ بين الألواح','Module gap (m)',0,2),num('rowGap','Passage entre rangées (m)','الممر بين الصفوف','Row walkway (m)',0,20),num('tilt','Inclinaison (°)','الميل','Tilt (degrees)',0,80),num('anchorSpacing','Espacement ancrages mesuré (m)','تباعد المثبتات','Specified anchor spacing (m)',0.1,5),select('support','Structure','الهيكل','Mounting',['aluminum','steel']),f('surveyFileId','Relevé coté joint (ID pièce)','وثيقة الرفع الهندسي','Measured survey attachment ID')];
 const electrical=[num('voc','Voc panneau (V)','جهد الدارة المفتوحة','Module Voc (V)',1,200),num('vmp','Vmp panneau (V)','جهد العمل','Module Vmp (V)',1,200),num('isc','Isc panneau (A)','تيار القصر','Module Isc (A)',0.1,100),num('imp','Imp panneau (A)','تيار العمل','Module Imp (A)',0.1,100),num('betaVoc','Coefficient Voc (%/°C)','معامل Voc','Voc coefficient (%/°C)',-2,0),num('betaVmp','Coefficient Vmp (%/°C)','معامل Vmp','Vmp coefficient (%/°C)',-2,0),num('alphaIsc','Coefficient Isc (%/°C)','معامل Isc','Isc coefficient (%/°C)',0,2),num('tmin','Température module min (°C)','أدنى حرارة اللوح','Minimum module temperature (°C)',-50,30),num('tmax','Température module max (°C)','أقصى حرارة اللوح','Maximum module temperature (°C)',30,100),num('inverterKva','Puissance apparente AC (kVA)','القدرة الظاهرية AC','AC apparent rating (kVA)',0.1),num('inverterKw','Puissance AC totale (kW)','قدرة العواكس AC','Total AC rating (kW)',0.1),num('udcMax','Tension DC max onduleur (V)','أقصى جهد DC','Inverter DC voltage limit (V)',1,2000),num('mpptMin','MPPT min (V)','أدنى MPPT','MPPT minimum (V)',1,2000),num('mpptMax','MPPT max (V)','أقصى MPPT','MPPT maximum (V)',1,2000),num('mpptCount','Nombre MPPT disponibles','عدد MPPT','Available MPPT count',1,1000),num('stringsPerMppt','Entrées par MPPT','مداخل لكل MPPT','Inputs per MPPT',1,20),num('mpptCurrent','Courant MPPT max (A)','أقصى تيار MPPT','MPPT current limit (A)',0.1,1000),num('mpptIsc','Courant de court-circuit MPPT max (A)','أقصى تيار قصر MPPT','MPPT short-circuit limit (A)',0.1,1000)];
 modules.push(
 mod('stegConnectors','Connecteurs STEG','ربط الستاغ','STEG connectors',1,[client,link('siteId','Site','الموقع','Site','sites',true)],['active','inactive'],['name','clientId','siteId']),
 mod('stegChecks','Vérifications STEG','التحقق من الستاغ','STEG checks',1,[client,project,link('siteId','Site','الموقع','Site','sites',true),date,f('reference','Référence abonnement STEG','مرجع الاشتراك','STEG subscription reference','text',{required:true}),select('result','Situation du compte','وضعية الحساب','Account result',['unknown','paid','unpaid']),f('balance','Solde impayé (TND)','الرصيد غير المدفوع','Outstanding balance (TND)','money'),f('proofFileId','Justificatif joint (ID)','وثيقة الإثبات','Evidence attachment ID'),f('validUntil','Valable jusqu’au','صالح إلى','Valid until','date')],['draft','verified'],['name','clientId','reference','result','date']),
 mod('technicalPlans','Plans techniques & CAO','المخططات الفنية','Engineering & CAD',1,[client,project,link('dossierId','Dossier STEG','ملف الستاغ','STEG dossier','dossiers',true),num('capacity','Puissance prévue (kWc)','القدرة المخططة','Design capacity (kWp)',0.1),link('moduleProductId','Modèle panneau','طراز اللوح','Module model','products'),link('inverterProductId','Modèle onduleur','طراز العاكس','Inverter model','products'),...geometry,...electrical,f('obstacles','Obstacles : x,y,largeur,longueur en m / ligne','عوائق: x,y,عرض,طول','Obstacles: x,y,width,length in m per line','textarea'),f('routes','Tracés électriques','مسارات الأسلاك','Cable routes','rows',{columns:[f('name','Circuit','الدائرة','Circuit','text',{required:true}),select('kind','Type','النوع','Type',['dc','ac1','ac3','earth']),link('productId','Article câble','منتج السلك','Cable product','products',true),f('path','Points x,y,z en m / ligne','إحداثيات x,y,z','Measured x,y,z points in m per line','textarea',{required:true}),num('section','Section (mm²)','المقطع','Cross section (mm²)',0.1,1000),num('conductors','Conducteurs / câbles parallèles','عدد الموصلات','Cable/conductor quantity multiplier',1,20),num('current','Courant de calcul (A)','تيار الحساب','Design current (A)',0,10000),num('voltage','Tension (V)','الجهد','Voltage (V)',1,40000),num('ampacity','Courant admissible corrigé Iz (A)','تيار Iz المصحح','Derated ampacity Iz (A)',0.1,10000),num('dropLimit','Chute max (%)','أقصى هبوط %','Maximum voltage drop %',0.01,20),num('resistivity','Résistivité à T° calcul (Ω mm²/m)','المقاومية عند حرارة الحساب','Design-temperature resistivity (ohm mm²/m)',0.001,0.2),num('cosPhi','Facteur de puissance AC','معامل القدرة AC','AC power factor',0.1,1),num('reactance','Réactance AC (Ω/m)','المفاعلة AC','AC linear reactance (ohm/m)',0,0.01),num('waste','Marge coupe (%)','هامش القص %','Cut allowance %',0,100)]})],['draft','generated','reviewed'],['name','projectId','capacity','support','status']),
 mod('cableDrums','Bobines & chutes de câbles','بكرات وفضلات الأسلاك','Cable drums & offcuts',3,[link('productId','Câble','السلك','Cable','products',true),link('warehouse','Dépôt','المستودع','Warehouse','warehouses',true),select('form','Forme','الشكل','Form',['drum','offcut']),f('lot','Lot / référence bobine','دفعة / مرجع البكرة','Lot / drum reference','text',{required:true}),num('initialLength','Longueur disponible mesurée (m)','الطول المقاس','Measured available length (m)',0.001),date],['draft','active'],['name','productId','warehouse','lot','initialLength']),
 mod('cableCuts','Coupes câble chantier','قص أسلاك الورشة','Site cable cuts',3,[project,link('drumId','Bobine / chute','البكرة / الفضلة','Drum / offcut','cableDrums',true),date,num('length','Longueur utile coupée (m)','الطول النافع','Useful cut length (m)',0.001),num('wasteLength','Perte de coupe (m)','خسارة القص','Cut waste (m)',0),f('circuit','Circuit / tracé du plan','دائرة المخطط','Drawing circuit')],['draft','posted'],['name','projectId','drumId','length','date']),
 mod('cableReturns','Retours câble chantier','إرجاع أسلاك الورشة','Site cable returns',3,[link('cutId','Coupe originale','القص الأصلي','Original cut','cableCuts',true),link('warehouse','Dépôt retour','مستودع الإرجاع','Return warehouse','warehouses',true),date,num('length','Longueur intacte retournée (m)','الطول السليم المرجع','Intact returned length (m)',0.001)],['draft','posted'],['name','cutId','warehouse','length','date']),
 mod('supplierInvoices','Factures fournisseurs','فواتير المورّدين','Supplier invoices',2,[link('projectId','Chantier','المشروع','Project','projects'),link('supplierId','Fournisseur','المورّد','Supplier','suppliers',true),link('orderId','Commande achat','طلب الشراء','Purchase order','orders'),date,f('dueDate','Échéance','تاريخ الاستحقاق','Due date','date',{required:true}),f('reference','Numéro facture fournisseur','رقم فاتورة المورّد','Supplier invoice number','text',{required:true}),f('stamp','Timbre (TND)','الطابع','Stamp (TND)','money'),f('items','Lignes facture','سطور الفاتورة','Invoice lines','rows',{required:true,columns:[f('description','Désignation','التسمية','Description','text',{required:true}),link('productId','Article','المنتج','Product','products'),num('quantity','Quantité','الكمية','Quantity',0.001),f('price','Prix HT (TND)','سعر دون أداء','Net unit price (TND)','money',{required:true}),num('tax','TVA (%)','الأداء %','VAT %',0,100)]})],['draft','issued'],['name','supplierId','reference','date','total'])
 );
 get('roles').fields.find(f=>f.key==='rules')!.columns![0].options=modules.filter(m=>!['roles','users'].includes(m.key)).map(m=>m.key);
}
