import type {Entry} from './domain';
import {xmlEscape} from './fiscal';
// A topology draft from the validated design, never an invented protection schedule.
export function renderTechnicalUnifilar(e:Entry){
 const s=e.data.snapshot??e.data.studySnapshot;if(!s)throw new Error('plan_not_generated');
 const esc=(v:unknown)=>xmlEscape(String(v??''));
 const height=Math.max(520,s.series.length*80+160);let mppt=0;
 const groups=s.groups.flatMap((g:any)=>Array.from({length:Math.ceil(g.strings/s.parallel)},(_,i)=>({id:++mppt,modules:g.modules,remaining:Math.min(s.parallel,g.strings-i*s.parallel)})));
 const rows=s.series.map((n:number,i:number)=>{const g=groups.find((g:any)=>g.modules===n&&g.remaining>0)!;g.remaining--;const y=100+i*80;return `<g><rect x="25" y="${y-24}" width="185" height="48"/><text x="35" y="${y-5}">Chaîne ${i+1} : ${n} modules</text><text x="35" y="${y+14}">${(n*s.coldVoc).toFixed(1)} V Voc froid</text><path d="M210 ${y} H280 V${height/2} H370"/><text x="220" y="${y-7}">MPPT ${g.id}</text></g>`;}).join('');
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1020 ${height}" role="img" aria-label="Avant-projet de schéma unifilaire"><style>rect{fill:#fff;stroke:#123852;stroke-width:2}path{fill:none;stroke:#123852;stroke-width:2}text{fill:#123852;font:14px Arial}</style>${rows}<rect x="370" y="${height/2-50}" width="170" height="100"/><text x="385" y="${height/2-18}">Onduleur / ensemble</text><text x="385" y="${height/2+5}">${esc(e.data.inverterKva)} kVA · ${esc(e.data.inverterKw)} kW</text><text x="385" y="${height/2+28}">AC : à confirmer sur site</text><path d="M540 ${height/2} H600 M780 ${height/2} H835"/><rect x="600" y="${height/2-50}" width="180" height="100"/><text x="610" y="${height/2-12}">Coffret AC / protections</text><text x="610" y="${height/2+12}">Calibres : note signée</text><rect x="835" y="${height/2-50}" width="170" height="100"/><text x="845" y="${height/2-12}">Comptage / réseau</text><text x="845" y="${height/2+12}">Raccordement STEG</text><path d="M455 ${height/2+50} V${height-65} H755 m-20 -8 h40 m-32 7 h24 m-16 7 h8"/><text x="465" y="${height-75}">PE / équipotentialité · valeur de terre à mesurer</text></svg>`;
 return `<!doctype html><html lang="fr"><meta charset="utf-8"><title>${esc(e.data.name)} — unifilaire</title><style>body{font:14px Arial;color:#123852;margin:24px}svg{width:100%;max-height:80vh}table{width:100%;border-collapse:collapse}td,th{padding:8px;border:1px solid #ccc;text-align:left}@page{size:A4 landscape}</style><h1>${esc(e.data.name)} — schéma unifilaire de principe</h1><p>AVANT-PROJET : raccordements et affectations MPPT proposés. Protections DC/AC, parafoudres, sectionnement, court-circuit, sélectivité, terre et homologations doivent être validés sur le schéma final signé. Ce dessin ne vaut pas approbation STEG.</p>${svg}<table><tr><th>Circuit</th><th>Section mm²</th><th>Longueur du trajet m</th><th>Conducteurs</th><th>Chute %</th></tr>${s.routes.map((r:any)=>`<tr><td>${esc(r.name)}</td><td>${r.section}</td><td>${r.length.toFixed(3)}</td><td>${r.conductors}</td><td>${r.dropPercent.toFixed(3)}</td></tr>`).join('')}</table></html>`;
}
