import {validate,type Entry} from './domain';
import {technicalDesign,stegChecklist} from './technical-domain';
export const TECHNICAL_EXAMPLES_ID='tn-plans-3d-v1';
export function technicalExamples(prefix=''):Entry[]{
 const entries:Entry[]=[],stamp='2026-10-09T09:00:00.000Z',id=(v:string)=>prefix+TECHNICAL_EXAMPLES_ID+'-'+v;
 const add=(kind:string,key:string,data:Record<string,unknown>,extra:Record<string,unknown>={})=>{const e:Entry={id:id(key),kind,data:{...validate(kind,{notes:'EXEMPLE FICTIF — étude indicative, aucune décision STEG réelle.',...data}),...extra,sampleDataset:TECHNICAL_EXAMPLES_ID},revision:1,demo:1,archived:0,createdAt:stamp,updatedAt:stamp};entries.push(e);return e;};
 const dc=add('products','cable-dc',{name:'Câble solaire 6 mm² · exemple',sku:'EX3D-DC6',category:'cable',unit:'meter',tracking:'quantityOnly',status:'active'}),ac=add('products','cable-ac',{name:'Câble AC 16 mm² · exemple',sku:'EX3D-AC16',category:'cable',unit:'meter',tracking:'quantityOnly',status:'active'}),earth=add('products','cable-earth',{name:'Conducteur terre 16 mm² · exemple',sku:'EX3D-PE16',category:'cable',unit:'meter',tracking:'quantityOnly',status:'active'});
 const specs=[{key:'tunis',city:'Tunis',name:'Villa Les Jasmins',capacity:6,columns:6,width:12,length:12,height:3.2,support:'aluminum',tilt:25,gps:'36.8065,10.1815'},{key:'sousse',city:'Sousse',name:'Atelier du Sahel',capacity:25,columns:10,width:16,length:24,height:7.2,support:'steel',tilt:15,gps:'35.8256,10.6084'},{key:'sfax',city:'Sfax',name:'Hangar des Oliviers',capacity:15,columns:10,width:15,length:18,height:4.5,support:'aluminum',tilt:20,gps:'34.7406,10.7603'}];
 for(const v of specs){
  const agency=add('agencies',v.key+'-agency',{name:v.city+' · exemple 3D',code:'EX3D-'+v.key.toUpperCase(),address:v.city,status:'active'});
  const client=add('clients',v.key+'-client',{name:v.name+' · exemple',phone:'+216 XX XXX XXX',address:v.city+' — adresse fictive',type:v.capacity===6?'individual':'business',agencyId:agency.id,desiredKwc:v.capacity,status:'active'});
  const site=add('sites',v.key+'-site',{name:'Toiture '+v.city+' · exemple',clientId:client.id,agencyId:agency.id,address:v.city+' — exemple',gps:v.gps,connection:'threePhase',subscribedKva:v.capacity+5,gridKv:.4,stegRef:'EXEMPLE-NON-VERIFIE-'+v.key,district:v.city,status:'active'});
  const project=add('projects',v.key+'-project',{name:v.name+' · '+v.capacity+' kWc · exemple',clientId:client.id,siteId:site.id,agencyId:agency.id,capacity:v.capacity,inverterKva:v.capacity,legalRegime:'onSiteSelfConsumption',status:'study'});
  const dossier=add('dossiers',v.key+'-dossier',{name:'Dossier BT '+v.city+' · exemple',clientId:client.id,projectId:project.id,agencyId:agency.id,capacity:v.capacity,voltage:'BT',district:v.city,regime:'outsideProsol',missing:'Pièces réelles, accord STEG et validation ingénieur à joindre',status:'incomplete'},{checklist:stegChecklist('BT')});
  const route=(name:string,kind:string,productId:string,path:string,section:number,conductors:number,current:number,voltage:number)=>({name,kind,productId,path,section,conductors,current,voltage,ampacity:80,dropLimit:2,resistivity:.0225,waste:5,cosPhi:.95,reactance:.00008});
  const h=v.height;
  const plan=add('technicalPlans',v.key+'-plan',{name:'Plan '+v.city+' · '+v.capacity+' kWc · exemple',clientId:client.id,projectId:project.id,dossierId:dossier.id,agencyId:agency.id,capacity:v.capacity,roofWidth:v.width,roofLength:v.length,roofHeight:h,panelClearance:.25,obstacleHeight:1.2,edge:1,moduleWidth:1.1,moduleLength:2.2,moduleW:500,columns:v.columns,gap:.04,rowGap:1.8,tilt:v.tilt,anchorSpacing:1.2,support:v.support,obstacles:`${v.width-2.5},${v.length-2.5},1,1`,voc:50,vmp:40,isc:13,imp:12,betaVoc:-.28,betaVmp:-.32,alphaIsc:.05,tmin:-10,tmax:85,inverterKw:v.capacity,inverterKva:v.capacity,udcMax:1000,mpptMin:120,mpptMax:850,mpptCount:4,stringsPerMppt:2,mpptCurrent:30,mpptIsc:40,routes:[route('DC → coffret toiture','dc',dc.id,`1,1,${h+.3}\n.4,1,${h+.3}\n.4,${v.length-1},${h+.3}\n.4,${v.length-1},1`,6,2,13,600),route('AC → tableau général','ac3',ac.id,`.4,${v.length-1},1\n.4,${v.length-1},.3\n${v.width-1},${v.length-1},.3`,16,5,v.capacity*1000/(Math.sqrt(3)*400),400),route('Terre → barrette','earth',earth.id,`1,1,${h}\n${v.width-1},1,${h}\n${v.width-1},1,0`,16,1,0,230)],status:'draft'});
  plan.data.studySnapshot=technicalDesign(plan.data);plan.data.studyGeneratedAt=stamp;plan.data.studyGeneratedBy='example';
 }
 return entries;
}
