import {xmlEscape as x} from './fiscal';
// Technical candidate against the archived 1.8.9 vocabulary. Qualification
// with TTN's current XSD 1.1, business rules and signature is still required.
const tag=(key:string,value:unknown)=>`<${key}>${x(value)}</${key}>`;
const amt=(code:string,value:number)=>`<Moa amountTypeCode="${code}" currencyCodeList="ISO_4217"><Amount currencyIdentifier="TND">${(value/1000).toFixed(3)}</Amount></Moa>`;
export function teifDraft(invoice:any,company:any,client:any,products:any[]=[]){
 if(invoice.status!=='issued'||!invoice.lines?.length)throw new Error('invalid_invoice');
 if(!/^\d{7}[ABCDEFGHJKLMNPQRSTVWXYZ]([ABDNP][CMNPE]\d{3})?$/.test(company.taxId??'')||!company.name||!company.address)throw new Error('company_tax_id_required');
 const type=/^\d{8}$/.test(client.taxId??'')?'I-02':'I-01';
 if(type==='I-01'&&!/^\d{7}[ABCDEFGHJKLMNPQRSTVWXYZ]([ABDNP][CMNPE]\d{3})?$/.test(client.taxId??'')||!client.address)throw new Error('customer_tax_id_required');
 if(invoice.discount)throw new Error('teif_discount_qualification_required');
 const partner=(code:string,d:any,idType:string)=>`<PartnerDetails functionCode="${code}"><Nad><PartnerIdentifier type="${idType}">${x(d.taxId)}</PartnerIdentifier><PartnerName nameType="Qualification">${x(d.name)}</PartnerName><PartnerAdresses lang="fr"><AdressDescription>${x(d.address)}</AdressDescription><Country codeList="ISO_3166-1">TN</Country></PartnerAdresses></Nad></PartnerDetails>`;
 const tax=(rate:number)=>`<TaxTypeName code="I-1602">TVA</TaxTypeName><TaxDetails><TaxRate>${rate}</TaxRate></TaxDetails>`;
 const lines=invoice.lines.map((l:any,i:number)=>{const base=Math.round(l.price*l.quantity),product=products.find(p=>p.id===l.productId);return `<Lin><ItemIdentifier>${i+1}</ItemIdentifier><LinImd lang="fr">${tag('ItemCode',product?.data.sku??String(i+1))}${tag('ItemDescription',l.description)}</LinImd><LinQty><Quantity measurementUnit="${product?.data.unit==='meter'?'MTR':'PCE'}">${l.quantity}</Quantity></LinQty><LinTax>${tax(l.tax)}</LinTax><LinMoa><MoaDetails>${amt('I-171',l.price)}</MoaDetails><MoaDetails>${amt('I-173',base)}</MoaDetails></LinMoa></Lin>`}).join('');
 const rates=[...new Set<number>(invoice.lines.map((l:any)=>l.tax))];
 const date=invoice.date.slice(8,10)+invoice.date.slice(5,7)+invoice.date.slice(2,4);
 const taxes=rates.map(rate=>{const base=invoice.lines.filter((l:any)=>l.tax===rate).reduce((n:number,l:any)=>n+Math.round(l.price*l.quantity),0);const value=invoice.lines.filter((l:any)=>l.tax===rate).reduce((n:number,l:any)=>n+Math.round(Math.round(l.price*l.quantity)*rate/100),0);return `<InvoiceTaxDetails><Tax>${tax(rate)}</Tax><AmountDetails>${amt('I-176',base)}</AmountDetails><AmountDetails>${amt('I-177',value)}</AmountDetails></InvoiceTaxDetails>`}).join('');
 const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<TEIF version="1.8.9" controlingAgency="TTN"><InvoiceHeader><MessageSenderIdentifier type="I-01">${x(company.taxId)}</MessageSenderIdentifier><MessageRecieverIdentifier type="${type}">${x(client.taxId)}</MessageRecieverIdentifier></InvoiceHeader><InvoiceBody><Bgm>${tag('DocumentIdentifier',invoice.name)}<DocumentType code="${invoice.invoiceType==='creditNote'?'I-12':'I-11'}">${invoice.invoiceType==='creditNote'?'Avoir':'Facture'}</DocumentType></Bgm><Dtm><DateText functionCode="I-31" format="ddMMyy">${date}</DateText></Dtm><PartnerSection>${partner('I-62',company,'I-01')}${partner('I-61',client,type)}</PartnerSection><LinSection>${lines}</LinSection><InvoiceMoa><AmountDetails>${amt('I-176',invoice.subtotal)}</AmountDetails><AmountDetails>${amt('I-177',invoice.tax)}</AmountDetails><AmountDetails>${amt('I-180',invoice.total)}</AmountDetails></InvoiceMoa><InvoiceTax>${taxes}${invoice.stamp?`<InvoiceTaxDetails><Tax><TaxTypeName code="I-1601">Timbre fiscal</TaxTypeName><TaxDetails><TaxRate>0</TaxRate></TaxDetails></Tax><AmountDetails>${amt('I-177',invoice.stamp)}</AmountDetails></InvoiceTaxDetails>`:''}</InvoiceTax></InvoiceBody></TEIF>`;
 return {xml,filename:'TEIF-BROUILLON-'+invoice.name.replace(/[^a-zA-Z0-9-]/g,'-')+'.xml',schemaVersion:'1.8.9 archive',validation:'not_validated',qualificationRequired:true};
}
