import { validate, type Entry } from './domain';
import { automaticPayroll } from './business-domain';
import { retentionAmounts, dashboardReport } from './enterprise-domain';
import type { WorkspaceData } from './client';

export const TUNISIA_DEMO_ID = 'tn-simulation-2025-2026-v1';
export const TUNISIA_DEMO_CUTOFF = '2026-10-09';
const id = (key:string) => `${TUNISIA_DEMO_ID}-${key}`;
const dinars = (n:number) => Math.round(n*1000);
const pad = (n:number) => String(n).padStart(2,'0');
const plusDays = (date:string,n:number) => new Date(Date.parse(date+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
export type TunisiaDemo = {records:Entry[]; company:Record<string,string>; metadata:{id:string;from:string;to:string;fictional:true;counts:Record<string,number>}};

// Fixed seed and cutoff make this historical fixture reproducible, with no future actuals.
export function tunisiaDemo(ownerEmail='direction@solumove.example'):TunisiaDemo {
  const records:Entry[]=[];
  let seed=20251009;
  const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
  const pick=<T,>(xs:T[])=>xs[Math.floor(random()*xs.length)];
  function add(kind:string,key:string,input:Record<string,any>,extra:Record<string,any>={}) {
    const data={...validate(kind,{...input,notes:input.notes??'SIMULATION — données fictives.'}),...extra,sampleDataset:TUNISIA_DEMO_ID};
    const date=input.date??extra.date??(input.period?input.period+'-01':undefined)??'2025-01-01';
    const entry:Entry={id:id(key),kind,data,revision:1,demo:1,archived:0,createdAt:date+'T09:00:00.000Z',updatedAt:date+'T09:00:00.000Z'};
    records.push(entry);return entry;
  }
  const cities=[{name:'Tunis',area:'Charguia II, Ariana',code:'TUN',lat:36.8065,lon:10.1815},{name:'Sousse',area:'Zone industrielle Sidi Abdelhamid',code:'SOS',lat:35.8256,lon:10.6084},{name:'Sfax',area:'Route de Gabès km 4',code:'SFX',lat:34.7406,lon:10.7603}];
  const managers=['Yassine Ben Salem','Meriem Trabelsi','Ahmed Gharbi'];
  const agencies=cities.map((c,i)=>add('agencies','agency-'+i,{name:'SoluMove '+c.name+' · simulation',code:'SIM-'+c.code,address:c.area+', '+c.name,manager:managers[i],phone:'+216 XX XXX '+(101+i),status:'active'}));
  const warehouses=cities.map((c,i)=>add('warehouses','warehouse-'+i,{name:'Dépôt '+c.name+' · simulation',code:'SIM-DEP-'+c.code,agencyId:agencies[i].id,address:c.area,manager:managers[i],locations:'A1–A8 : panneaux\nB1–B4 : onduleurs/batteries\nC1–C6 : câbles et protections',status:'active'}));
  const parks=cities.map((c,i)=>add('parks','park-'+i,{name:'Parc '+c.name+' · simulation',agencyId:agencies[i].id,address:c.area,manager:managers[i],status:'active'}));
  const staff=[['Yassine Ben Salem','Directeur',3200,0],['Ines Mansour','Commerciale',1550,0],['Meriem Trabelsi','Responsable agence',2300,1],['Firas Kacem','Technicien installateur',1450,1],['Ahmed Gharbi','Chef de chantier',2100,2],['Walid Ayari','Magasinier',1200,2],['Sarra Bouazizi','Commerciale',1600,2],['Anis Jaziri','Technicien SAV',1500,0]] as const;
  const employees=staff.map(([name,position,salary,a],i)=>add('employees','employee-'+i,{name:name+' · simulation',position,salary:dinars(salary),agencyId:agencies[a].id,phone:'+216 XX XXX '+(201+i),email:`salarie${i+1}@solumove.example`,cnss:'SIM-CNSS-'+(i+1),bank:'RIB FICTIF — NON UTILISABLE',startDate:'2024-01-01',contractType:'CDI — simulation',skills:position.includes('Technicien')?'Pose PV, contrôle électrique, diagnostic':'Gestion et opérations',openingLeave:3,annualTaxAllowance:0,status:'active'}));
  const roleSpecs=[['Commercial agence',['clients','leads','sites','visits','quotes','salesOrders','projects','invoices','collections'],true,'agencies'],['Magasinier dépôt',['products','receipts','deliveryNotes','inventories','transits','exitNotes','transferOrders','qr'],true,'warehouses'],['Finance lecture',['bi','invoices','payments','journalEntries','vat','withholdings','cashForecast'],false,'all'],['Technicien agence/dépôt',['projects','planning','tickets','missions','vehicleKeys','monitoring','products'],true,'both']] as const;
  const roles=roleSpecs.map(([name,keys,write,scope],i)=>add('roles','role-'+i,{name:name+' · simulation',rules:keys.map(module=>({module,access:write?'write':'read',add:write?'allow':'deny',edit:write?'allow':'deny',delete:'deny',scope})),status:'active'}));
  roles.forEach((role,i)=>add('users','user-'+i,{name:employees[i+1].data.name,email:`compte${i+1}@solumove.example`,employeeId:employees[i+1].id,roleId:role.id,branches:[{agencyId:agencies[i%3].id}],warehouses:[{warehouseId:warehouses[i%3].id}],notes:'Compte fictif INACTIF ; aucune invitation ni connexion créée.',status:'inactive'}));
  const vehicles=['Peugeot Partner 1.6 HDi','Citroën Berlingo','Renault Kangoo','Isuzu D-Max'].map((name,i)=>add('vehicles','vehicle-'+i,{name:name+' · simulation',registration:`SIM-${210+i}-TN-${1001+i}`,agencyId:agencies[i%3].id,parkId:parks[i%3].id,driverId:employees[[7,3,4,5][i]].id,type:name,odometer:30000+i*11000,insuranceDate:'2026-12-31',inspectionDate:i===2?'2026-10-05':'2026-11-20',taxDate:'2027-03-05',serviceKm:40000+i*11000,ownership:i===3?'Leasing — simulation':'Propriété — simulation',status:'active'}));
  const kilometre=vehicles.map(v=>v.data.odometer as number);
  const supplierNames=['Atlas Distribution PV','Sahel Électricité','Sud Énergie Équipements','Carthage Structures','Cap Bon Câblage','Méditerranée Services'];
  const suppliers=supplierNames.map((name,i)=>add('suppliers','supplier-'+i,{name:name+' · simulation',agencyId:agencies[i%3].id,phone:'+216 XX XXX '+(301+i),email:`fournisseur${i+1}@solumove.example`,taxId:'SIM-FISC-'+(i+1),address:cities[i%3].area,leadDays:[7,5,10,12,4,3][i],bank:'Banque tunisienne · RIB fictif',status:'active'}));
  const catalog=[['PV550','Panneau monocristallin 550 W','panel','piece',285,355,24,'serialTracking'],['INV6','Onduleur hybride 6 kW','inverter','piece',2150,2850,3,'serialTracking'],['BAT5','Batterie LiFePO4 5,12 kWh','battery','piece',3250,4250,2,'serialTracking'],['CAB6','Câble solaire 6 mm²','cable','meter',2.7,4.2,150,'quantityOnly'],['STR','Support toiture aluminium par panneau','structure','piece',58,85,24,'quantityOnly'],['PROT','Coffret protection AC/DC','protection','piece',235,340,4,'quantityOnly'],['MC4','Connecteur MC4 paire','accessory','piece',5.5,9,20,'quantityOnly'],['EARTH','Câble terre 16 mm²','cable','meter',5.4,8.2,80,'quantityOnly'],['SPD','Parafoudre DC 1000 V','protection','piece',78,120,6,'quantityOnly'],['TOOL','Pince sertissage MC4','tool','piece',145,210,2,'serialTracking'],['SERVICE','Pose et mise en service par kWc','service','hour',0,310,0,'quantityOnly'],['KIT6','Kit solaire 6,6 kWc','accessory','kit',7500,9800,0,'quantityOnly']] as const;
  const products=catalog.map(([sku,name,category,unit,cost,price,minStock,tracking],i)=>add('products','product-'+i,{name:name+' · simulation',sku:'SIM-TN-'+sku,category,unit,purchasePrice:dinars(cost),salePrice:dinars(price),minStock,tracking,warrantyMonths:category==='panel'?144:60,brand:'Gamme de démonstration',approval:'Aucune homologation affirmée — simulation',status:'active'}));
  [0,1,3,4,5].forEach((p,i)=>add('kitComponents','kit-'+i,{name:'Composant kit 6,6 kWc',kitId:products[11].id,componentId:products[p].id,quantity:[12,1,90,12,1][i],status:'active'}));
  const firstNames=['Amine','Sofiene','Nadia','Hanen','Mehdi','Rim','Lotfi','Aymen','Imen','Hichem','Sana','Bilel'];
  const lastNames=['Ben Youssef','Mansour','Trabelsi','Chaabane','Kacem','Jaziri','Gharbi','Ayari'];
  const clients=Array.from({length:48},(_,i)=>{const a=i%3,type=['individual','business','farmer','reseller'][i%4];const name=type==='individual'?`${firstNames[i%12]} ${lastNames[Math.floor(i/6)%8]}`:type==='business'?`Atelier ${['Les Oliviers','El Wifak','Ennour','El Amal'][i%4]} ${i+1}`:type==='farmer'?`Exploitation agricole ${['El Baraka','Essalem','El Khir'][i%3]} ${i+1}`:`Distribution ${cities[a].name} ${i+1}`;return add('clients','client-'+i,{name:name+' · simulation',agencyId:agencies[a].id,type,phone:'+216 XX XXX '+(401+i),email:`client${i+1}@solumove.example`,address:pick([cities[a].area,`Route de ${['Kairouan','Menzel Chaker','Nabeul'][a]}`,`Quartier résidentiel ${cities[a].name}`]),taxId:'SIM-CLIENT-'+pad(i+1),contact:firstNames[i%12],creditLimit:dinars(type==='individual'?25000:90000),status:'active'});});
  const sites=clients.map((c,i)=>add('sites','site-'+i,{name:`Site ${i+1} · ${cities[i%3].name}`,agencyId:c.data.agencyId,clientId:c.id,address:c.data.address,gps:`${cities[i%3].lat}, ${cities[i%3].lon}`,ownerName:c.data.name,stegSubscriber:c.data.name,stegRef:'SIM-STEG-'+pad(i+1),district:cities[i%3].name,connection:c.data.type==='individual'?'singlePhase':'threePhase',status:'active'}));
  const accountDefs=[['411','Clients','asset'],['401','Fournisseurs','liability'],['707','Ventes installations PV','revenue'],['43671','TVA collectée','liability'],['43666','TVA déductible','asset'],['532','Banque exploitation','asset'],['601','Achats matériels','expense'],['641','Salaires et charges','expense'],['453','Organismes sociaux','liability'],['432','IRPP et CSS à reverser','liability'],['4368','Timbres fiscaux','liability'],['425','Personnel rémunérations dues','liability'],['421','Avances au personnel','asset'],['437','Taxes patronales','liability'],['101','Capital de simulation','equity'],['37','Stock initial','asset'],['625','Frais exploitation','expense'],['434','Retenue reçue à imputer','asset'],['435','Retenue émise à reverser','liability']] as const;
  const accounts=accountDefs.map(([code,name,type])=>add('accounts','account-'+code,{name,code:'SIM-'+code,type,status:'active'}));
  const account=(code:string)=>accounts[accountDefs.findIndex(a=>a[0]===code)].id;
  const journals=['VE','AC','BQ','PA','OD'].map(code=>add('journals','journal-'+code,{name:({VE:'Ventes',AC:'Achats',BQ:'Banque',PA:'Paie',OD:'Opérations diverses'} as any)[code]+' · simulation',code:'SIM-'+code,status:'active'}));
  const journal=(code:string)=>journals.find(j=>j.data.code==='SIM-'+code)!.id;
  const mapping:any={name:'Affectations comptables · simulation',salesJournal:journal('VE'),cashJournal:journal('BQ'),purchaseJournal:journal('AC'),payrollJournal:journal('PA'),status:'active'};
  Object.entries({receivable:'411',payable:'401',sales:'707',vat:'43671',inputVat:'43666',cash:'532',purchases:'601',salary:'641',social:'453',tax:'432',stampTax:'4368',employeePayable:'425',staffAdvances:'421',payrollTax:'437'}).forEach(([k,v])=>mapping[k]=account(v));
  add('accountingSettings','accounting-settings',mapping);
  [2025,2026].forEach(y=>add('fiscalPeriods','fiscal-'+y,{name:'Exercice '+y+' · simulation',startDate:y+'-01-01',endDate:y+'-12-31',status:'open',notes:'Exercice laissé ouvert pour démonstration ; aucun arrêté réel.'}));
  const policies=[2025,2026].map(y=>add('payrollPolicies','policy-'+y,{name:'Hypothèses de paie '+y+' · simulation',startDate:y+'-01-01',endDate:y+'-12-31',source:'SIMULATION : CNSS base 9,18/16,57 + fonds emploi 0,5/0,5 ; barème IRPP 2025. AT 1%, TFP 2%, FOPROLOS 1%, CSS 1%, congé 2j/mois sont hypothèses à contrôler avant utilisation réelle.',employeeRate:9.18,employerRate:16.57,unemploymentEmployee:0.5,unemploymentEmployer:0.5,accidentRate:1,tfpRate:2,foprolosRate:1,professionalRate:10,professionalCap:dinars(2000),cssRate:1,cssThreshold:dinars(5000),overtimeMultiplier:1.25,monthlyHours:208,leavePerMonth:2,leaveCap:24,brackets:[{ceiling:dinars(5000),rate:0},{ceiling:dinars(10000),rate:15},{ceiling:dinars(20000),rate:25},{ceiling:dinars(30000),rate:30},{ceiling:dinars(40000),rate:33},{ceiling:dinars(50000),rate:36},{ceiling:dinars(70000),rate:38},{ceiling:0,rate:40}],status:'validated'}));
  ['installation','maintenance','amendment','employment'].forEach(type=>add('contractTemplates','template-'+type,{name:'Modèle '+type+' · simulation',type,language:'fr',version:'SIM-1',terms:'DOCUMENT FICTIF. Parties : {{client}} / {{employee}}. Projet {{project}}, montant {{amount}} TND. Objet, matériel, planning, garanties, exclusions et échéancier à compléter. Aucune signature réelle.',status:'draft'}));
  ['BIAT','STB','Banque de Tunisie'].forEach((bank,i)=>add('bankProfiles','bank-'+i,{name:bank+' · gabarit fictif non calibré',bank,instrument:'cheque',width:175,height:80,offsetX:0,offsetY:0,positions:[{key:'beneficiary',x:20,y:20,width:120,fontSize:10},{key:'amount',x:130,y:10,width:35,fontSize:10},{key:'words',x:20,y:30,width:145,fontSize:10},{key:'date',x:110,y:55,width:45,fontSize:10}],status:'draft'}));
  function entry(source:Entry|undefined,key:string,date:string,code:string,rows:any[],agencyId?:string) {
    const e=add('journalEntries','journal-entry-'+key,{name:source?.data.name??key,date,journalId:journal(code),reference:source?.id??'SIM-OUVERTURE',agencyId:agencyId??source?.data.agencyId,projectId:source?.data.projectId,rows:rows.filter(r=>r.debit||r.credit),status:'posted'},source?{sourceId:source.id}:{});
    if(source)e.id=source.id+'-accounting';
    if(source)source.data.accountingEntryId=e.id;return e;
  }
  const line=(code:string,debit=0,credit=0,label='Simulation')=>({accountId:account(code),debit,credit,label});
  const pools=new Map<string,string[]>(),balances=new Map<string,number>();let serialSequence=0;
  const key=(w:number,p:number)=>w+'|'+p;
  function move(w:number,p:number,q:number,date:string,label:string,extra:any={}) {
    const k=key(w,p),incoming=q>0,n=Math.abs(q),pool=pools.get(k)??[];
    const serialList=products[p].data.tracking==='serialTracking'?(incoming?Array.from({length:n},()=>`SIM-TN-${catalog[p][0]}-${String(++serialSequence).padStart(6,'0')}`):pool.slice(0,n)):[];
    if(!incoming&&(balances.get(k)??0)<n)throw new Error('demo_insufficient_stock');
    if(!incoming&&products[p].data.tracking==='serialTracking'&&serialList.length!==n)throw new Error('demo_serials');
    const e=add('movements','movement-'+records.length,{name:label,agencyId:agencies[w].id,productId:products[p].id,direction:incoming?'stockIn':'stockOut',quantity:n,warehouse:warehouses[w].id,date,reason:label,projectId:extra.projectId,serials:serialList.join('\n'),status:'posted'},{unitCost:products[p].data.purchasePrice,serialList,...extra});
    pools.set(k,incoming?[...pool,...serialList]:pool.slice(serialList.length));balances.set(k,(balances.get(k)??0)+q);return e;
  }
  function transfer(w:number,to:number,p:number,q:number,date:string,transit:Entry,receive=true) {
    const out=move(w,p,-q,date,'Expédition inter-dépôts',{transferId:transit.id});
    transit.data.items[0].serials=out.data.serialList.join('\n');
    if(receive){const k=key(to,p),serialList=out.data.serialList;add('movements','movement-'+records.length,{name:'Réception transfert inter-dépôts',agencyId:agencies[to].id,productId:products[p].id,direction:'stockIn',quantity:q,warehouse:warehouses[to].id,date,reason:'Réception '+transit.data.name,serials:serialList.join('\n'),status:'posted'},{serialList,unitCost:products[p].data.purchasePrice,transferId:transit.id});pools.set(k,[...(pools.get(k)??[]),...serialList]);balances.set(k,(balances.get(k)??0)+q);transit.data.receivedAt=date+'T16:00:00Z';}
    transit.data.shippedAt=date+'T10:00:00Z';transit.data.destinationAgencyId=agencies[to].id;
  }
  let openingStock=0;
  for(let w=0;w<3;w++)for(const [p,q] of [[0,100],[1,12],[2,4],[3,1200],[4,120],[5,14],[6,100],[7,300],[8,20],[9,3]]){move(w,p,q,'2025-01-01','Stock d’ouverture fictif');openingStock+=q*products[p].data.purchasePrice;}
  entry(undefined,'Bilan ouverture simulé','2025-01-01','OD',[line('532',dinars(180000)),line('37',openingStock),line('101',0,dinars(180000)+openingStock)]);
  const allocations:any[]=[];
  function pay(key:string,input:any,retention=false,debitRows?:any[]) {
    const p=add('payments','payment-'+key,{...input,status:input.status??'cleared'});
    if(p.data.status==='cleared'&&p.data.direction==='incoming'){const rows=p.data.allocations??(p.data.installmentId?[{installmentId:p.data.installmentId,amount:p.data.amount}]:[]);for(const [i,a] of rows.entries())allocations.push({id:p.id+'-'+i,payment_id:p.id,installment_id:a.installmentId,amount:a.amount,owner:'simulation'});}
    let withheld=0;
    if(retention&&p.data.status==='cleared') {
      const operations=[{code:'RS7_000001',invoiceYear:p.data.date.slice(0,4),cnpc:'0',charge:'0',base:Math.floor(p.data.amount/1.19),vatRate:19,rate:1.5,vatWithholdingRate:0}];
      const amounts=retentionAmounts(operations);withheld=amounts.withheld;
      add('withholdings','withholding-'+key,{name:'Certificat RS · '+p.data.name,agencyId:p.data.agencyId,paymentId:p.id,direction:p.data.direction==='incoming'?'received':'issued',date:p.data.date,reference:'SIM-RS-'+key,operation:'add',beneficiaryName:'BENEFICIAIRE FICTIF',identifierType:'MatriculeFiscal',identifier:'0000000A',category:'PM',resident:'1',address:'TUNIS SIMULATION',email:'simulation@solumove.example',phone:'00000000',operations,status:'validated'},{...amounts,fictional:true});
    }
    if(p.data.status==='cleared') {
      const outgoing=p.data.direction==='outgoing';
      const debitCode=p.data.employeeId?'425':p.data.supplierId?'401':'625';
      const rows=outgoing?[...(debitRows??[line(debitCode,p.data.amount)]),line('532',0,p.data.amount-withheld),...(withheld?[line('435',0,withheld)]:[])]:[line('532',p.data.amount-withheld),...(withheld?[line('434',withheld)]:[]),line('411',0,p.data.amount)];
      entry(p,'payment-'+key,p.data.date,'BQ',rows);
    }return p;
  }
  let projectSequence=0;
  for(let y=2025;y<=2026;y++)for(let m=1;m<=(y===2025?12:10);m++) {
    const period=y+'-'+pad(m),first=period+'-01',last=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10),monthEnd=last<TUNISIA_DEMO_CUTOFF?last:TUNISIA_DEMO_CUTOFF,partial=last>TUNISIA_DEMO_CUTOFF;
    for(let w=0;w<3;w++) {
      const items=[0,1,3,4,5].map(p=>({productId:products[p].id,quantity:Math.max(1,[160,18,1800,180,20][[0,1,3,4,5].indexOf(p)]-(balances.get(key(w,p))??0)),price:products[p].data.purchasePrice,tax:19}));
      const order=add('orders','order-'+period+'-'+w,{name:`SIM-BCF-${period}-${cities[w].code}`,agencyId:agencies[w].id,supplierId:suppliers[w].id,date:first,dueDate:period+'-04',items,status:'received'});
      let purchaseTotal=0;
      for(let part=0;part<2;part++) {
        const receiptItems=items.map(i=>({...i,quantity:part===0?Math.ceil(i.quantity*0.6):i.quantity-Math.ceil(i.quantity*0.6)})).filter(i=>i.quantity>0);
        if(!receiptItems.length)continue;
        const date=period+'-'+pad(part===0?2:4);let ht=0,tax=0;
        const receipt=add('receipts','receipt-'+period+'-'+w+'-'+part,{name:`SIM-BR-${period}-${cities[w].code}-${part+1}`,agencyId:agencies[w].id,orderId:order.id,warehouse:warehouses[w].id,date,items:receiptItems,status:'posted'});
        receipt.data.items=receiptItems.map(i=>{const p=products.findIndex(p=>p.id===i.productId),movement=move(w,p,i.quantity,date,receipt.data.name,{sourceId:receipt.id});const base=i.quantity*i.price;ht+=base;tax+=Math.round(base*0.19);return {...i,serials:movement.data.serialList.join('\n')};});
        entry(receipt,'receipt-'+period+'-'+w+'-'+part,date,'AC',[line('601',ht),line('43666',tax),line('401',0,ht+tax)]);purchaseTotal+=ht+tax;
      }
      order.data.receivedItems=order.data.items.map((i:any)=>({productId:i.productId,quantity:i.quantity}));
      const supplierPaymentDate=plusDays(first,6);
      if(supplierPaymentDate<=TUNISIA_DEMO_CUTOFF)pay('supplier-'+period+'-'+w,{name:`Virement fournisseur ${cities[w].code} ${period}`,agencyId:agencies[w].id,supplierId:suppliers[w].id,direction:'outgoing',date:supplierPaymentDate,amount:purchaseTotal,method:'transfer',account:'Banque exploitation · simulation',reference:'SIM-VIR-F-'+period+'-'+w},m%3===0);
      add('leads','lead-'+period+'-'+w,{name:`Prospect ${cities[w].name} ${period}`,agencyId:agencies[w].id,phone:'+216 XX XXX 999',source:pick(['facebook','referral','website','showroom']),owner:employees[w===2?6:1].data.name,budget:dinars(14000+Math.floor(random()*15000)),nextDate:monthEnd,status:partial?'proposal':pick(['won','lost','proposal']),lostReason:'Arbitrage budget — simulation'});
    }
    const count=partial?3:y===2025?6:8;
    for(let n=0;n<count;n++) {
      const sequence=++projectSequence,w=n%3,c=clients.filter(c=>c.data.agencyId===agencies[w].id)[Math.floor(random()*16)],site=sites.find(s=>s.data.clientId===c.id)!,capacity=pick([3.3,5.5,6.6,11,22]),panels=Math.round(capacity/0.55),inverters=Math.ceil(capacity/6),date=period+'-'+pad(Math.min(Number(last.slice(8)),partial?[3,6,9][n]:[5,9,13,17,21,25,27,29][n])),recent=plusDays(date,12)>TUNISIA_DEMO_CUTOFF;
      const p=add('projects','project-'+sequence,{name:`PV ${capacity} kWc · ${c.data.name}`,agencyId:agencies[w].id,clientId:c.id,siteId:site.id,regime:c.data.type==='farmer'?'pumping':c.data.type==='business'?'industrial':'outsideProsol',capacity,manager:employees[[7,3,4][w]].data.name,startDate:date,dueDate:plusDays(date,12),progress:recent?[45,70,90][n%3]:100,status:recent?'installation':'commissioned',budget:dinars(capacity*1450),salePrice:dinars(capacity*2050)});
      add('visits','visit-'+sequence,{name:'Visite technique · '+p.data.name,agencyId:p.data.agencyId,clientId:c.id,siteId:site.id,date,technician:p.data.manager,roof:'Dalle béton / terrasse — hypothèse',surface:Math.round(capacity*9),tilt:30,azimuth:0,shade:'Ombrage limité, scénario fictif',electrical:'Contrôle simulé — aucune mesure réelle',access:'Accès sécurisé à prévoir',status:'completed'});
      add('studies','study-'+sequence,{name:'Étude · '+p.data.name,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,capacity,inverter:inverters*6,annualUse:Math.round(capacity*2050),yield:1700+w*50,selfUse:65,tariff:350,investment:dinars(capacity*2050),latitude:cities[w].lat,longitude:cities[w].lon,tilt:30,azimuth:0,losses:14,assumptions:'Productible annuel supposé 1700–1800 kWh/kWc, tarif 0,350 TND/kWh ; aucune requête PVGIS ni mesure réelle.',status:'review'}, {productionYear:Math.round(capacity*(1700+w*50)),provider:'SIMULATION MANUELLE'});
      const items=[{productId:products[0].id,quantity:panels,price:products[0].data.salePrice,tax:19},{productId:products[1].id,quantity:inverters,price:products[1].data.salePrice,tax:19},{productId:products[3].id,quantity:Math.round(capacity*15),price:products[3].data.salePrice,tax:19},{productId:products[4].id,quantity:panels,price:products[4].data.salePrice,tax:19},{productId:products[5].id,quantity:inverters,price:products[5].data.salePrice,tax:19}];
      const lines=items.map(i=>({productId:i.productId,description:products.find(p=>p.id===i.productId)!.data.name,quantity:i.quantity,price:i.price,tax:i.tax}));lines.push({productId:products[10].id,description:'Installation et essais — simulation',quantity:capacity,price:dinars(310),tax:19});
      const quote=add('quotes','quote-'+sequence,{name:`SIM-DEV-${y}-${String(sequence).padStart(4,'0')}`,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,date,validUntil:plusDays(date,30),lines,stamp:1000,status:'accepted'});
      const saleOrder=add('salesOrders','sales-order-'+sequence,{name:`SIM-BC-${y}-${String(sequence).padStart(4,'0')}`,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,date,dueDate:plusDays(date,12),items,status:'confirmed'});
      const invoice=add('invoices','invoice-'+sequence,{name:`SIM-FAC-${y}-${String(sequence).padStart(4,'0')}`,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,date,dueDate:plusDays(date,45),invoiceType:'invoice',lines,stamp:1000,status:'issued'},{quoteId:quote.id});p.data.salePrice=invoice.data.total;
      entry(invoice,'invoice-'+sequence,date,'VE',[line('411',invoice.data.total),line('707',0,invoice.data.subtotal),line('43671',0,invoice.data.tax),line('4368',0,1000)]);
      const deposit=Math.round(invoice.data.total*0.3),remainder=invoice.data.total-deposit;
      const due1=add('installments','due-'+sequence+'-1',{name:'Acompte · '+invoice.data.name,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,invoiceId:invoice.id,dueDate:date,amount:deposit,status:'open'});
      const due2=add('installments','due-'+sequence+'-2',{name:'Solde · '+invoice.data.name,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,invoiceId:invoice.id,dueDate:plusDays(date,45),amount:remainder,status:'open'});
      pay('deposit-'+sequence,{name:'Acompte · '+invoice.data.name,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,direction:'incoming',installmentId:due1.id,date,amount:deposit,method:pick(['transfer','cash','cheque']),account:'Banque exploitation · simulation'},c.data.type==='business');
      const creditDate=plusDays(date,10);let credit=0;
      if(sequence%17===0&&creditDate<=TUNISIA_DEMO_CUTOFF){const note=add('invoices','credit-'+sequence,{name:'SIM-AV-'+y+'-'+sequence,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,date:creditDate,dueDate:creditDate,invoiceType:'creditNote',originalId:invoice.id,lines:[{description:'Remise commerciale de simulation',quantity:1,price:dinars(180),tax:19}],status:'issued'},{creditApplied:true,creditApplicationDate:creditDate,creditAllocations:[{installmentId:due2.id,amount:dinars(214.2)}]});credit=note.data.total;due2.data.amount-=credit;entry(note,'credit-'+sequence,creditDate,'VE',[line('707',note.data.subtotal),line('43671',note.data.tax),line('411',0,note.data.total)]);}
      const clearedDate=plusDays(date,35);
      if(clearedDate<=TUNISIA_DEMO_CUTOFF&&sequence%11!==0){const amount=sequence%13===0?Math.round((remainder-credit)*0.5):remainder-credit;pay('balance-'+sequence,{name:'Solde · '+invoice.data.name,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,direction:'incoming',allocations:[{installmentId:due2.id,amount}],date:clearedDate,amount,method:'transfer',account:'Banque exploitation · simulation'},c.data.type==='business');}
      else if(!recent){add('collections','collection-'+sequence,{name:'Relance · '+invoice.data.name,agencyId:p.data.agencyId,clientId:c.id,invoiceId:invoice.id,date:monthEnd,dueDate:plusDays(date,45),stage:sequence%22===0?'dispute':'reminder',message:'Relance fictive — aucune communication envoyée',fees:0,status:'open'});const effectPayment=pay('pending-'+sequence,{name:'Chèque non encaissé · '+invoice.data.name,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,direction:'incoming',date:monthEnd,amount:remainder-credit,method:'cheque',status:sequence%22===0?'rejected':'pending'});add('effects','effect-'+sequence,{name:'Chèque simulé · '+invoice.data.name,agencyId:p.data.agencyId,instrument:'cheque',direction:'incoming',clientId:c.id,paymentId:effectPayment.id,number:'SIM-CHQ-'+sequence,bank:pick(['BIAT','STB','Banque de Tunisie']),beneficiary:'SoluMove Solar — simulation',date:monthEnd,validUntil:plusDays(monthEnd,90),amount:remainder-credit,verification:'Numéro, banque et document fictifs, aucune impression payable.',status:sequence%22===0?'rejected':'portfolio'});}
      const delivery=add('deliveryNotes','delivery-'+sequence,{name:`SIM-BL-${y}-${sequence}`,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,salesOrderId:saleOrder.id,warehouse:warehouses[w].id,date,items,status:'posted'});
      delivery.data.items=items.map(i=>{const index=products.findIndex(p=>p.id===i.productId),movement=move(w,index,-i.quantity,date,delivery.data.name,{projectId:p.id,sourceId:delivery.id});return {...i,serials:movement.data.serialList.join('\n')};});saleOrder.data.lastDeliveryAt=date+'T15:00:00Z';saleOrder.data.deliveredItems=items.map(i=>({productId:i.productId,quantity:i.quantity}));
      add('planning','planning-'+sequence,{name:'Pose · '+p.data.name,agencyId:p.data.agencyId,projectId:p.id,employeeId:employees[[7,3,4][w]].id,date,time:'08:00',hours:8,type:'installation',team:'Équipe '+cities[w].name,status:'completed'});
      add('attendance','attendance-project-'+sequence,{name:'Pointage chantier · '+p.data.name,agencyId:p.data.agencyId,employeeId:employees[[7,3,4][w]].id,projectId:p.id,date,hours:8,overtime:sequence%5===0?2:0,cost:dinars(75+capacity*5),status:'approved'});
      add('contracts','contract-'+sequence,{name:'SIM-CTR-'+y+'-'+sequence,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,type:'installation',date,amount:invoice.data.total,terms:'Convention fictive de fourniture et pose PV ; devis lié, acompte 30 %, solde 70 %, accès toiture et essais. Non signée, sans force contractuelle.',templateId:id('template-installation'),version:'SIM-1',status:'review'});
      add('dossiers','dossier-'+sequence,{name:'Dossier technique · '+p.data.name,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,regime:c.data.type==='business'?'industrial':'outsideProsol',district:cities[w].name,reference:'SIM-DOS-'+sequence,date,nextDate:plusDays(date,14),funding:'Simulation sans promesse de financement, subvention ou agrément.',missing:recent?'Contrôle final fictif':'',status:recent?'complement':'commissioned'});
      if(sequence%8===0)add('tickets','ticket-'+sequence,{name:'Contrôle de production · '+p.data.name,agencyId:p.data.agencyId,clientId:c.id,projectId:p.id,priority:sequence%16===0?'high':'normal',coverage:'toConfirm',assigned:p.data.manager,dueDate:monthEnd,cost:dinars(95),diagnosis:'Contrôle simulé : connectivité et nettoyage à vérifier.',status:recent?'scheduled':'closed'});
      const v=n%4,startKm=kilometre[v],endKm=startKm+60+Math.floor(random()*180);kilometre[v]=endKm;vehicles[v].data.odometer=endKm;
      add('missions','mission-'+sequence,{name:'Livraison · '+p.data.name,agencyId:p.data.agencyId,vehicleId:vehicles[v].id,employeeId:employees[[7,3,4,5][v]].id,projectId:p.id,date,time:'07:30',returnTime:'17:30',destination:c.data.address,startKm,endKm,cost:dinars(35),status:'completed'});
      add('vehicleKeys','keys-'+sequence,{name:'Remise clés · '+vehicles[v].data.name,agencyId:vehicles[v].data.agencyId,vehicleId:vehicles[v].id,employeeId:employees[[7,3,4,5][v]].id,date,startKm,conditionOut:'Contrôle visuel simulé',expectedReturn:date,purpose:p.data.name,status:'returned'},{returnedAt:date+'T17:30:00Z',endKm,members:[]});
      const liters=Math.round((endKm-startKm)*0.078*10)/10;
      const fuel=add('vehicleCosts','fuel-'+sequence,{name:'Gasoil · '+vehicles[v].data.name,agencyId:p.data.agencyId,vehicleId:vehicles[v].id,projectId:p.id,date,type:'fuel',amount:Math.round(liters*dinars(2.205)),liters,odometer:endKm,provider:'Station-service fictive',status:'paid'});
      pay('fuel-'+sequence,{name:fuel.data.name,agencyId:p.data.agencyId,direction:'outgoing',date,amount:fuel.data.amount,method:'card'},false).data.sourceId=fuel.id;
    }
    if(!partial)for(let w=0;w<3;w++) {
      const to=(w+1)%3,transferOrder=add('transferOrders','transfer-order-'+period+'-'+w,{name:'SIM-BCT-'+period+'-'+w,agencyId:agencies[w].id,from:warehouses[w].id,to:warehouses[to].id,date:period+'-28',items:[{productId:products[1].id,quantity:1,price:products[1].data.purchasePrice,tax:19}],status:'approved'},{lastShipmentAt:period+'-28T10:00:00Z'});
      const transit=add('transits','transit-'+period+'-'+w,{name:'SIM-BLT-'+period+'-'+w,agencyId:agencies[w].id,from:warehouses[w].id,to:warehouses[to].id,date:period+'-28',transferOrderId:transferOrder.id,items:[{productId:products[1].id,quantity:1,price:products[1].data.purchasePrice,tax:19}],status:'received'});transfer(w,to,1,1,period+'-28',transit);
      const exit=add('exitNotes','exit-'+period+'-'+w,{name:'SIM-BS-'+period+'-'+w,agencyId:agencies[w].id,warehouse:warehouses[w].id,employeeId:employees[[7,3,4][w]].id,date:period+'-28',reason:'Consommables SAV de démonstration',items:[{productId:products[3].id,quantity:5,price:products[3].data.purchasePrice,tax:19}],status:'posted'});move(w,3,-5,period+'-28',exit.data.name,{sourceId:exit.id});
      add('inventories','inventory-'+period+'-'+w,{name:'SIM-INV-'+period+'-'+w,agencyId:agencies[w].id,warehouse:warehouses[w].id,date:monthEnd,items:[0,1,2,3,4,5,6,7,8,9].map(p=>({productId:products[p].id,quantity:balances.get(key(w,p))??0,serials:(pools.get(key(w,p))??[]).join('\n')})),status:'posted'},{adjustments:[],countedAt:monthEnd+'T17:00:00Z'});
    }
    for(let w=0;w<3;w++)for(const [category,amount] of [['rent',1050+w*180],['advertising',380+w*75]] as const){const e=add('expenses','expense-'+period+'-'+w+'-'+category,{name:`${category==='rent'?'Loyer':'Campagne commerciale'} ${cities[w].name} ${period}`,agencyId:agencies[w].id,date:first,category,amount:dinars(amount),method:'transfer',receipt:'SIM-JUST-'+period+'-'+w+'-'+category,status:'paid'});pay('expense-'+period+'-'+w+'-'+category,{name:e.data.name,agencyId:e.data.agencyId,direction:'outgoing',date:first,amount:e.data.amount,method:'transfer'}).data.sourceId=e.id;}
    if(!partial)for(const i of [1,6]) {
      const invoice=records.filter(r=>r.kind==='invoices'&&r.data.invoiceType==='invoice'&&r.data.date.startsWith(period)&&r.data.agencyId===employees[i].data.agencyId).at(-1)!;
      const dueIds=records.filter(r=>r.kind==='installments'&&r.data.invoiceId===invoice.id).map(r=>r.id);
      const collected=allocations.filter(a=>dueIds.includes(a.installment_id)).reduce((n,a)=>n+a.amount,0);
      add('commissions','commission-'+period+'-'+i,{name:'Commission encaissée · '+invoice.data.name,agencyId:employees[i].data.agencyId,employeeId:employees[i].id,invoiceId:invoice.id,basis:'collected',rate:0.75,period,amount:Math.round(collected*0.0075),status:'approved'});
    }
    for(let i=0;i<employees.length;i++) {
      const employee=employees[i],periodEmployee={...employee,data:{...employee.data,salary:Math.round(employee.data.salary*(y===2026?1.04:1)),...(partial?{endDate:monthEnd}:{})}};
      if((m===7||m===8)&&!partial)add('leave','leave-'+period+'-'+i,{name:'Congé annuel · '+employee.data.name,agencyId:employee.data.agencyId,employeeId:employee.id,startDate:period+'-10',endDate:period+'-14',type:'paidLeave',days:5,status:'approved'},{annualLeaveLimit:24});
      add('attendance','attendance-office-'+period+'-'+i,{name:'Pointage sélectionné · '+employee.data.name,agencyId:employee.data.agencyId,employeeId:employee.id,date:period+'-03',hours:8,overtime:0,status:'approved'});
      const calculated=automaticPayroll(periodEmployee,period,policies[y-2025],records,{allowances:dinars(partial?35:120)});
      const salary=add('payroll','payroll-'+period+'-'+i,{...calculated,status:partial?'draft':'validated',notes:partial?'Estimation du 1er au 9 octobre : aucun paiement réalisé.':'Paie mensuelle de simulation.'},{...calculated,status:partial?'draft':'validated'});
      if(!partial)for(const commissionId of calculated.commissionIds)records.find(r=>r.id===commissionId)!.data.status='paid';
      if(!partial){entry(salary,'salary-'+period+'-'+i,last,'PA',[line('641',salary.data.employerCost),line('425',0,salary.data.net),line('453',0,salary.data.cnssDeduction+salary.data.unemploymentDeduction+salary.data.employerSocial),line('432',0,salary.data.incomeTax+salary.data.solidarity),line('437',0,salary.data.employerTaxes)]);pay('salary-'+period+'-'+i,{name:salary.data.name,agencyId:employee.data.agencyId,employeeId:employee.id,direction:'outgoing',date:last,amount:salary.data.net,method:'transfer',account:'Banque exploitation · simulation'});}
    }
    if(!partial&&m%3===0)for(let v=0;v<4;v++){const date=period+'-20',odometer=records.filter(r=>r.kind==='missions'&&r.data.vehicleId===vehicles[v].id&&r.data.date<=date).reduce((n,r)=>Math.max(n,r.data.endKm),30000+v*11000);const job=add('maintenanceJobs','service-'+period+'-'+v,{name:'Vidange et filtres · '+vehicles[v].data.name,agencyId:vehicles[v].data.agencyId,vehicleId:vehicles[v].id,date,odometer,amount:dinars(240+v*25),provider:'Garage fictif '+cities[v%3].name,work:'Vidange moteur et filtres — scénario de maintenance',nextKm:odometer+10000,nextDate:plusDays(date,180),status:'completed'});vehicles[v].data.serviceKm=odometer+10000;vehicles[v].data.serviceDate=plusDays(date,180);pay('service-'+period+'-'+v,{name:job.data.name,agencyId:job.data.agencyId,direction:'outgoing',date,amount:job.data.amount,method:'card'}).data.sourceId=job.id;}
    const recentProjects=records.filter(r=>r.kind==='projects'&&r.data.status==='commissioned'&&r.data.startDate<=first).slice(-6);
    if(!partial)recentProjects.forEach((p,i)=>{const seasonal=[0.55,0.65,0.9,1.05,1.2,1.3,1.35,1.25,1.05,0.85,0.6,0.5][m-1],expected=Math.round(p.data.capacity*145*seasonal),low=i===0&&m%4===0;add('monitoring','monitoring-'+period+'-'+i,{name:'Production mensuelle · '+p.data.name,agencyId:p.data.agencyId,projectId:p.id,date:last,production:Math.round(expected*(low?0.58:0.93+random()*0.09)),expected,connection:'connected',source:'manual',observedAt:last+'T18:00:00Z',notes:'Données énergétiques entièrement simulées, non mesurées.',status:'recorded'});});
    add('minutes','minutes-'+period,{name:'PV comité de gestion · '+period,agencyId:agencies[0].id,date:monthEnd,time:'15:00',location:'Siège Tunis · simulation',type:'management',chair:managers[0],secretary:'Ines Mansour',attendees:managers.map(name=>({name,capacity:'Responsable agence',present:'present'})),agenda:'Ventes, encours clients, approvisionnement, qualité installation et trésorerie.',discussion:'Réunion fictive : suivi des marges, retards de paiement, stocks et maintenance du parc.',resolutions:[{text:'Prioriser les relances et préparer les approvisionnements du mois suivant.',for:3,against:0,abstentions:0,employeeId:employees[1].id,dueDate:plusDays(monthEnd,7)}],quorum:'3 membres représentés sur 3',status:'draft'});
    if(!partial){const report=dashboardReport({records,allocations,stock:[],events:[],company:{},files:[],serials:[]} as WorkspaceData,{from:first,to:last});add('vatReturns','vat-return-'+period,{name:'TVA mensuelle · '+period,startDate:first,endDate:last,previousCredit:0,notes:'Simulation non déposée ; seuls ventes et achats à TVA 19% sont illustrés.',status:'draft'},{snapshot:{outputVat:report.kpis.outputVat,inputVat:report.kpis.inputVat,net:report.kpis.vatDue},fictional:true});}
  }
  // Illustrative fiscal/social settlements. Future due dates remain forecasts,
  // never cleared payments; these are not statutory filing/deadline assertions.
  for(let y=2025;y<=2026;y++)for(let m=1;m<=12;m++) {
    const period=y+'-'+pad(m),payroll=records.filter(r=>r.kind==='payroll'&&r.data.period===period&&r.data.status==='validated');if(!payroll.length)continue;
    const next=plusDays(new Date(Date.UTC(y,m,1)).toISOString().slice(0,10),19);
    const tax=payroll.reduce((n,r)=>n+r.data.incomeTax+r.data.solidarity,0),employerTax=payroll.reduce((n,r)=>n+r.data.employerTaxes,0);
    if(next<=TUNISIA_DEMO_CUTOFF)pay('tax-salary-'+period,{name:'Règlement fiscal paie · '+period,direction:'outgoing',date:next,amount:tax+employerTax,method:'transfer',notes:'Échéance hypothétique de simulation.'},false,[line('432',tax),line('437',employerTax)]);
    else add('cashForecast','tax-salary-'+period,{name:'Fiscalité paie à payer · '+period,date:TUNISIA_DEMO_CUTOFF,dueDate:next,direction:'outgoing',amount:tax+employerTax,probability:100,scenario:'base',category:'Fiscalité paie prévue',status:'planned'});
    if(m%3===0){const quarter=records.filter(r=>r.kind==='payroll'&&r.data.status==='validated'&&r.data.period>=y+'-'+pad(m-2)&&r.data.period<=period),social=quarter.reduce((n,r)=>n+r.data.cnssDeduction+r.data.unemploymentDeduction+r.data.employerSocial,0),due=plusDays(new Date(Date.UTC(y,m,1)).toISOString().slice(0,10),14);
      if(due<=TUNISIA_DEMO_CUTOFF)pay('social-'+period,{name:'Cotisations sociales trimestre · '+period,direction:'outgoing',date:due,amount:social,method:'transfer',notes:'Échéance hypothétique de simulation.'},false,[line('453',social)]);
      else add('cashForecast','social-'+period,{name:'Cotisations sociales à payer · '+period,date:TUNISIA_DEMO_CUTOFF,dueDate:due,direction:'outgoing',amount:social,probability:100,scenario:'base',category:'Charges sociales prévues',status:'planned'});
    }
  }
  employees.forEach(e=>e.data.salary=Math.round(e.data.salary*1.04));
  vehicles.forEach((v,i)=>['oilChange','timingBelt','tyres'].forEach((type,j)=>add('vehicleMaintenance','maintenance-plan-'+i+'-'+j,{name:`${type==='oilChange'?'Vidange':type==='timingBelt'?'Distribution':'Pneus'} · ${v.data.name}`,agencyId:v.data.agencyId,vehicleId:v.id,type,lastKm:v.data.odometer-4000,lastDate:'2026-09-20',intervalKm:j===0?10000:j===1?80000:40000,intervalMonths:j===0?6:j===1?60:24,nextKm:j===0?v.data.serviceKm:v.data.odometer+(j===1?30000:12000),nextDate:j===0?v.data.serviceDate:'2027-06-01',estimatedCost:dinars(j===0?280:j===1?950:650),provider:'Garage de simulation',manufacturerRule:'Intervalle indicatif fictif : consulter le carnet constructeur réel.',status:'active'})));
  const held=add('vehicleKeys','keys-held',{name:'Clés actuellement confiées · simulation',agencyId:vehicles[0].data.agencyId,vehicleId:vehicles[0].id,employeeId:employees[7].id,date:TUNISIA_DEMO_CUTOFF,startKm:vehicles[0].data.odometer,purpose:'Mission SAV fictive du jour',expectedReturn:TUNISIA_DEMO_CUTOFF,conditionOut:'Bon état — simulation',status:'held'},{handedAt:TUNISIA_DEMO_CUTOFF+'T08:00:00Z'});vehicles[0].data.keyHolderId=employees[7].id;vehicles[0].data.keyRecordId=held.id;
  const transit=add('transits','transit-current',{name:'Transfert en cours Tunis → Sousse · simulation',agencyId:agencies[0].id,from:warehouses[0].id,to:warehouses[1].id,date:TUNISIA_DEMO_CUTOFF,items:[{productId:products[1].id,quantity:1,price:products[1].data.purchasePrice,tax:19}],status:'shipped'});transfer(0,1,1,1,TUNISIA_DEMO_CUTOFF,transit,false);
  const transferClient=clients[0],oldAgency=transferClient.data.agencyId;transferClient.data.agencyId=agencies[1].id;
  add('clientTransfers','client-transfer',{name:'Transfert dossier Tunis → Sousse · simulation',agencyId:oldAgency,clientId:transferClient.id,toAgencyId:agencies[1].id,date:TUNISIA_DEMO_CUTOFF,reason:'Déménagement du contact et suivi commercial — simulation',includeOpen:'no',status:'posted'},{fromAgencyId:oldAgency,destinationAgencyId:agencies[1].id,transferredAt:TUNISIA_DEMO_CUTOFF+'T10:00:00Z'});
  add('reservations','reservation-current',{name:'Réservation chantier du jour · simulation',agencyId:agencies[2].id,productId:products[0].id,warehouse:warehouses[2].id,quantity:12,date:TUNISIA_DEMO_CUTOFF,projectId:records.filter(r=>r.kind==='projects').at(-1)!.id,status:'reserved'});
  add('advances','advance',{name:'Avance salarié · simulation',agencyId:employees[3].data.agencyId,employeeId:employees[3].id,type:'salaryAdvance',date:'2026-10-05',amount:dinars(250),repaid:0,dueDate:'2026-10-31',status:'approved'});
  const latestInvoice=records.filter(r=>r.kind==='invoices'&&r.data.invoiceType==='invoice').at(-1)!;
  const parent=records.find(r=>r.kind==='contracts'&&r.data.type==='installation')!;
  add('contracts','amendment',{name:'Avenant garantie · simulation',agencyId:parent.data.agencyId,clientId:parent.data.clientId,projectId:parent.data.projectId,parentId:parent.id,type:'amendment',date:'2026-10-08',terms:'Extension fictive du programme de visites SAV ; avenant non signé.',version:'SIM-2',status:'review'});
  const partialOrder=add('orders','partial-order',{name:'SIM-BCF-2026-10-PARTIEL',agencyId:agencies[2].id,supplierId:suppliers[2].id,date:'2026-10-07',dueDate:'2026-10-15',items:[{productId:products[0].id,quantity:20,price:products[0].data.purchasePrice,tax:19}],status:'partial'},{receivedItems:[{productId:products[0].id,quantity:12}]});
  const partialReceipt=add('receipts','partial-receipt',{name:'SIM-BR-2026-10-PARTIEL',agencyId:agencies[2].id,orderId:partialOrder.id,warehouse:warehouses[2].id,date:'2026-10-08',items:[{productId:products[0].id,quantity:12,price:products[0].data.purchasePrice,tax:19}],status:'posted'});
  const partialMovement=move(2,0,12,'2026-10-08',partialReceipt.data.name,{sourceId:partialReceipt.id});partialReceipt.data.items[0].serials=partialMovement.data.serialList.join('\n');
  const partialHt=products[0].data.purchasePrice*12;entry(partialReceipt,'partial-receipt','2026-10-08','AC',[line('601',partialHt),line('43666',Math.round(partialHt*0.19)),line('401',0,partialHt+Math.round(partialHt*0.19))]);
  // Illustrate a single bank transfer allocated to two invoices of the same client.
  for(const client of clients) {
    const unpaid=records.filter(r=>r.kind==='installments'&&r.data.clientId===client.id&&r.data.dueDate<TUNISIA_DEMO_CUTOFF).map(r=>({r,left:r.data.amount-allocations.filter(a=>a.installment_id===r.id).reduce((n,a)=>n+a.amount,0)})).filter(r=>r.left>0);
    if(unpaid.length>=2){const rows=unpaid.slice(0,2).map(({r,left})=>({installmentId:r.id,amount:Math.max(1,Math.round(left*0.4))}));pay('multi-invoice',{name:'Virement réparti sur deux factures · simulation',agencyId:client.data.agencyId,clientId:client.id,direction:'incoming',date:TUNISIA_DEMO_CUTOFF,amount:rows.reduce((n,a)=>n+a.amount,0),allocations:rows,method:'transfer',reference:'SIM-MULTI-2026-10-09'});break;}
  }
  add('eInvoices','einvoice',{name:'El Fatoora · '+latestInvoice.data.name,agencyId:latestInvoice.data.agencyId,invoiceId:latestInvoice.id,schemaVersion:'Brouillon de simulation',validationReport:'Aucune signature, qualification TTN, transmission ou acceptation.',status:'draft'},{fictional:true});
  add('vatAdjustments','vat-adjustment',{name:'Ajustement TVA à vérifier · simulation',date:'2026-10-08',direction:'increase',amount:dinars(95),reason:'Hypothèse de TVA non déductible à examiner ; pas encore approuvée.',status:'draft'});
  [0,1,2].forEach(w=>['base','optimistic','pessimistic'].forEach((scenario,s)=>add('cashForecast','forecast-'+w+'-'+scenario,{name:'Achats novembre · '+cities[w].name+' · '+scenario,agencyId:agencies[w].id,date:TUNISIA_DEMO_CUTOFF,dueDate:'2026-11-05',direction:'outgoing',amount:dinars([24000,22000,27000][s]),probability:100,scenario,category:'Approvisionnement prévu — pas une dépense réalisée',status:'planned'})));
  for(let i=0;i<8;i++)add('notifications','notification-'+i,{name:['Relances clients','Contrôle stock','Échéance entretien','Dossier technique à compléter'][i%4],agencyId:agencies[i%3].id,recipientEmail:ownerEmail,message:'Notification de démonstration au 9 octobre 2026. Consulter les rapports et opérations correspondants.',priority:i%4===0?'urgent':'normal',status:i<4?'unread':'read'},{date:TUNISIA_DEMO_CUTOFF,readAt:i>=4?TUNISIA_DEMO_CUTOFF+'T09:00:00Z':undefined});
  const conversation=add('conversations','conversation',{name:'Coordination agences · simulation',members:[{email:ownerEmail},{email:employees[1].data.email},{email:employees[3].data.email}],status:'active'});
  ['Bonjour, point stock et commandes du jour ?','Le dépôt Tunis a expédié un onduleur vers Sousse.','Priorité aux relances clients et au contrôle des dossiers en attente.'].forEach((message,i)=>add('messages','message-'+i,{name:'Message de simulation',conversationId:conversation.id,message,status:'sent'},{members:conversation.data.members,senderEmail:i===0?ownerEmail:employees[i===1?1:3].data.email,date:TUNISIA_DEMO_CUTOFF,sentAt:TUNISIA_DEMO_CUTOFF+'T'+pad(9+i)+':00:00Z'}));
  const counts=Object.fromEntries([...new Set(records.map(r=>r.kind))].map(kind=>[kind,records.filter(r=>r.kind===kind).length]));
  return {records,company:{name:'SoluMove Solar · SOCIÉTÉ FICTIVE',address:'Charguia II, Ariana — simulation',phone:'+216 XX XXX XXX',taxId:'SIMULATION NON DECLARABLE',tejTaxId:'0000000A',category:'PM',bank:'Banque exploitation · compte fictif'},metadata:{id:TUNISIA_DEMO_ID,from:'2025-01-01',to:TUNISIA_DEMO_CUTOFF,fictional:true,counts}};
}

// Recursively map nested IDs (invoice rows, roles, allocations, journal lines, chat).
export function scopeTunisiaDemo(demo:TunisiaDemo,owner:string):TunisiaDemo {
  const map=(value:any):any=>typeof value==='string'&&value.startsWith(TUNISIA_DEMO_ID+'-')?owner+'-'+value:Array.isArray(value)?value.map(map):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,map(v)])):value;
  return {...demo,records:demo.records.map(r=>({...r,id:owner+'-'+r.id,data:map(r.data)}))};
}
