import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const records=sqliteTable('records',{id:text('id').primaryKey(),owner:text('owner').notNull(),kind:text('kind').notNull(),data:text('data').notNull(),revision:integer('revision').notNull().default(1),demo:integer('demo').notNull().default(0),archived:integer('archived').notNull().default(0),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull() },t=>[index('idx_records_owner_kind').on(t.owner,t.kind)]);
export const allocations=sqliteTable('allocations',{id:text('id').primaryKey(),paymentId:text('payment_id').notNull().references(()=>records.id),installmentId:text('installment_id').notNull().references(()=>records.id),owner:text('owner').notNull(),amount:integer('amount').notNull()},t=>[uniqueIndex('uq_allocation_payment_installment').on(t.paymentId,t.installmentId),index('idx_allocation_installment').on(t.installmentId)]);
export const stock=sqliteTable('stock_balances',{owner:text('owner').notNull(),productId:text('product_id').notNull().references(()=>records.id),warehouse:text('warehouse').notNull(),quantity:integer('quantity').notNull().default(0)},t=>[uniqueIndex('uq_stock_owner_product_warehouse').on(t.owner,t.productId,t.warehouse)]);
export const events=sqliteTable('events',{id:text('id').primaryKey(),owner:text('owner').notNull(),recordId:text('record_id').notNull(),action:text('action').notNull(),createdAt:text('created_at').notNull(),detail:text('detail').notNull()},t=>[index('idx_events_owner_date').on(t.owner,t.createdAt)]);
export const company=sqliteTable('company',{owner:text('owner').primaryKey(),data:text('data').notNull()});
export const files=sqliteTable('files',{id:text('id').primaryKey(),owner:text('owner').notNull(),recordId:text('record_id').notNull().references(()=>records.id),filename:text('filename').notNull(),contentType:text('content_type').notNull(),size:integer('size').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_files_owner_record').on(t.owner,t.recordId)]);
export const serialLocations=sqliteTable('serial_locations',{id:text('id').primaryKey(),owner:text('owner').notNull(),serial:text('serial').notNull(),productId:text('product_id').notNull().references(()=>records.id),warehouse:text('warehouse'),projectId:text('project_id'),lastMovement:text('last_movement').notNull()},t=>[uniqueIndex('uq_serial_owner_serial').on(t.owner,t.serial)]);

export const operationGuards=sqliteTable('operation_guards',{id:text('id').primaryKey(),owner:text('owner').notNull(),recordId:text('record_id').notNull(),revision:integer('revision').notNull()});

export const stockGuards=sqliteTable('stock_guards',{id:text('id').primaryKey(),owner:text('owner').notNull(),productId:text('product_id').notNull(),warehouse:text('warehouse').notNull(),quantity:integer('quantity').notNull()});
