import {env} from 'cloudflare:workers';
import {Buffer} from 'node:buffer';
import {access,db,failure,assertAdmin,assertModule,visible,assertOrigin} from '@/lib/solar/server';
import * as business from '@/lib/solar/business-server';
import {byKey} from '@/lib/solar/modules';
import {validate} from '@/lib/solar/domain';
import {profitability,leaveBalance} from '@/lib/solar/business-domain';
const checksum=async(bytes:ArrayBuffer|Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as BufferSource))).map(b=>b.toString(16).padStart(2,'0')).join('');
export async function GET(request:Request){try{const ctx=await access(),url=new URL(request.url);
 if(url.searchParams.has('backup')){assertAdmin(ctx);const [rs,fs,ev,co]=await db().batch([db().prepare('SELECT * FROM records WHERE owner=? ORDER BY created_at,rowid').bind(ctx.owner),db().prepare('SELECT * FROM files WHERE owner=?').bind(ctx.owner),db().prepare('SELECT * FROM events WHERE owner=?').bind(ctx.owner),db().prepare('SELECT data FROM company WHERE owner=?').bind(ctx.owner)]);const files:any[]=[];let bytes=0;for(const f of fs.results as any[]){bytes+=f.size;if(bytes>2*1024*1024)throw new Error('backup_too_large');const object=await env.BUCKET?.get(`${ctx.owner}/${f.id}`);if(!object)throw new Error('backup_attachment_missing');const content=await object.arrayBuffer();files.push({...f,sha256:await checksum(content),bytes:Buffer.from(content).toString('base64')});}const content=JSON.stringify({format:'solumove-backup',version:1,createdAt:new Date().toISOString(),records:rs.results,files,events:ev.results,company:(co.results[0] as any)?.data??'{}'});if(Buffer.byteLength(content)>3400000)throw new Error('backup_too_large');return new Response(content,{headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});}
 const records=(await business.all(ctx.owner)).filter(r=>visible(ctx,r)),allocations=(await db().prepare('SELECT * FROM allocations WHERE owner=?').bind(ctx.owner).all()).results.filter((a:any)=>records.some(r=>r.id===a.payment_id)&&records.some(r=>r.id===a.installment_id));
 const start=url.searchParams.get('start')??'0000-01-01',end=url.searchParams.get('end')??'9999-12-31',agency=url.searchParams.get('agency');
 const entries=records.filter(r=>r.kind==='journalEntries'&&r.data.status==='posted'&&r.data.date>=start&&r.data.date<=end&&(!agency||r.data.agencyId===agency));const balances=new Map<string,any>(),ledger:any[]=[];for(const e of entries.sort((a,b)=>a.data.date.localeCompare(b.data.date))){for(const row of e.data.rows){const previous=balances.get(row.accountId)??{accountId:row.accountId,debit:0,credit:0};previous.debit+=row.debit??0;previous.credit+=row.credit??0;previous.balance=previous.debit-previous.credit;balances.set(row.accountId,previous);ledger.push({entryId:e.id,date:e.data.date,reference:e.data.reference,agencyId:e.data.agencyId,...row,runningBalance:previous.balance});}}
 const scheduledIds=new Set(records.filter(r=>r.kind==='installments').map(r=>r.data.invoiceId));const unscheduled=records.filter(r=>r.kind==='invoices'&&r.data.status==='issued'&&r.data.invoiceType!=='creditNote'&&!scheduledIds.has(r.id)).map(r=>({id:r.id,clientId:r.data.clientId,invoiceId:r.id,dueDate:r.data.dueDate,amount:r.data.total,paid:0,outstanding:r.data.total}));
 const due=records.filter(r=>r.kind==='installments'&&r.data.status!=='restructured').map(r=>{const paid=allocations.filter((a:any)=>a.installment_id===r.id).reduce((n:number,a:any)=>n+a.amount,0);return {id:r.id,clientId:r.data.clientId,invoiceId:r.data.invoiceId,dueDate:r.data.dueDate,amount:r.data.amount,paid,outstanding:r.data.amount-paid};}).filter(r=>r.outstanding>0).concat(unscheduled),today=new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Tunis'}),alerts:any[]=[];
 for(const d of due)if(d.dueDate<=today)alerts.push({kind:'overdue',recordId:d.id,label:'Échéance impayée',date:d.dueDate,amount:d.outstanding});
 for(const r of records){if(r.kind==='monitoring'&&(r.data.connection==='disconnected'||r.data.expected>0&&r.data.production<r.data.expected*0.7))alerts.push({kind:'monitoring',recordId:r.id,label:r.data.connection==='disconnected'?'Connexion inconnue':'Production faible'});for(const key of ['dueDate','nextDate','endDate','validUntil','insuranceDate','inspectionDate','serviceDate','taxDate'])if(r.kind!=='installments'&&r.data[key]&&r.data[key]<=today&&!['closed','resolved','paid','cleared','cancelled','received','rejected'].includes(r.data.status))alerts.push({kind:'deadline',recordId:r.id,label:r.data.name,date:r.data[key]});}
 const stock=(await db().prepare('SELECT * FROM stock_balances WHERE owner=?').bind(ctx.owner).all()).results.filter((s:any)=>records.some(r=>r.id===s.warehouse));for(const product of records.filter(r=>r.kind==='products'&&r.data.minStock)){const available=stock.filter((s:any)=>s.product_id===product.id).reduce((n:number,s:any)=>n+s.quantity/1000,0)-records.filter(r=>r.kind==='reservations'&&r.data.productId===product.id&&r.data.status==='reserved').reduce((n,r)=>n+r.data.quantity,0);if(available<product.data.minStock)alerts.push({kind:'stock',recordId:product.id,label:product.data.name,available});}
 const leaves=records.filter(r=>r.kind==='employees').map(e=>{const p=records.find(r=>r.kind==='payrollPolicies'&&r.data.status==='validated'&&r.data.startDate<=today&&r.data.endDate>=today);return p?{employeeId:e.id,...leaveBalance(e,p,records,today)}:null;}).filter(Boolean);
 return Response.json({entries,ledger,balance:Array.from(balances.values()),profitability:profitability(records,allocations).filter(r=>!agency||r.agencyId===agency),dues:due,alerts,leaves},{headers:{'Cache-Control':'no-store'}});
 }catch(e){return failure(e);}}
export async function POST(request:Request){try{const ctx=await access();assertOrigin(request);const raw=await request.text();if(Buffer.byteLength(raw)>3500000)throw new Error('request_too_large');const b=JSON.parse(raw);const action=b.action;
 if(action==='syncSolarEdge'){assertAdmin(ctx);return Response.json(await business.syncSolarEdge(ctx,b.projectId));}
 if(action==='setupTemplates'){assertAdmin(ctx);return Response.json(await business.setupTemplates(ctx));}
 if(action==='setupPayroll'){assertAdmin(ctx);return Response.json(await business.setupPayroll(ctx));}
 if(action==='settleInvoices')return Response.json(await business.settleInvoices(ctx,b));
 if(action==='calculatePayroll')return Response.json(await business.calculatePayroll(ctx,b));
 if(action==='import'){
  assertModule(ctx,b.kind,true);if(!Array.isArray(b.rows)||!b.rows.length||b.rows.length>100||!['clients','products','suppliers','employees','monitoring'].includes(b.kind))throw new Error('invalid_import');const statements=[];const available=await business.all(ctx.owner);for(const input of b.rows){const resolved={...input};for(const f of byKey[b.kind].fields)if(f.type==='link'&&resolved[f.key]&&!available.some(r=>r.id===resolved[f.key]&&r.kind===f.target)){const matches=available.filter(r=>r.kind===f.target&&r.data.name===resolved[f.key]&&visible(ctx,r));if(matches.length!==1)throw new Error('ambiguous_import_reference');resolved[f.key]=matches[0].id;}const data=validate(b.kind,resolved);await business.validateBusinessSave(ctx,b.kind,data);await business.referenceRows(ctx,b.kind,data);if(!visible(ctx,{id:'',kind:b.kind,data}))throw new Error('forbidden_branch');statements.push(business.insert(ctx,b.kind,data));}if(!b.commit)return Response.json({valid:true,count:statements.length});await db().batch(statements);return Response.json({ok:true,count:statements.length});
 }
 if(action==='restore'){
  assertAdmin(ctx);const backup=b.backup;if(backup?.format!=='solumove-backup'||backup.version!==1||!Array.isArray(backup.records)||backup.records.length>5000||!Array.isArray(backup.files)||backup.files.length>500)throw new Error('invalid_backup');if(await db().prepare('SELECT id FROM records WHERE owner=? LIMIT 1').bind(ctx.owner).first())throw new Error('restore_requires_empty_workspace');
  // Restore into an empty workspace only, remapping all global IDs and references.
  const ids=new Map<string,string>();for(const r of backup.records){if(typeof r.id!=='string'||ids.has(r.id)||(!byKey[r.kind]&&r.kind!=='plan_lock'))throw new Error('invalid_backup');ids.set(r.id,crypto.randomUUID());}for(const f of backup.files){if(typeof f.id!=='string'||ids.has(f.id)||!ids.has(f.record_id)||typeof f.bytes!=='string')throw new Error('invalid_backup');ids.set(f.id,crypto.randomUUID());}
  const remap=(value:any):any=>typeof value==='string'?(ids.get(value)??value):Array.isArray(value)?value.map(remap):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).map(([k,v])=>[k,remap(v)])):value;
  const records=backup.records.map((r:any)=>({...r,id:ids.get(r.id),data:remap(JSON.parse(r.data))}));
  for(const r of records){if(!r.data||!Number.isInteger(r.revision)||r.revision<1||![0,1].includes(r.archived)||![0,1].includes(r.demo)||typeof r.created_at!=='string'||typeof r.updated_at!=='string')throw new Error('invalid_backup');if(byKey[r.kind]){const input=r.data;if(r.kind==='orders'&&!input.items)continue;validate(r.kind,input);}}
  for(const r of records.filter((r:any)=>r.kind==='contracts'&&r.data.signatureMethod==='uploaded_signed_document'))if(!backup.files.some((f:any)=>ids.get(f.id)===r.data.signatureFileId)||!/^([a-f0-9]{64})$/.test(r.data.signatureHash??''))throw new Error('invalid_backup');
  // Closed periods must follow their historical entries; other records keep original insertion order.
  records.sort((a:any,b:any)=>Number(a.kind==='fiscalPeriods'&&a.data.status==='closed')-Number(b.kind==='fiscalPeriods'&&b.data.status==='closed'));
  const uploaded:string[]=[],batch:D1PreparedStatement[]=[];try{for(const f of backup.files){if(!env.BUCKET)throw new Error('storage_unavailable');const id=ids.get(f.id)!,bytes=Buffer.from(f.bytes,'base64');if(bytes.length!==f.size||bytes.length>10*1024*1024)throw new Error('invalid_backup');const hash=await checksum(bytes),signed=records.filter((r:any)=>r.kind==='contracts'&&r.data.signatureMethod==='uploaded_signed_document'&&r.data.signatureFileId===id);if(f.sha256&&f.sha256!==hash||signed.some((r:any)=>r.data.signatureHash!==hash))throw new Error('backup_checksum_mismatch');const key=`${ctx.owner}/${id}`;await env.BUCKET.put(key,bytes);uploaded.push(key);}
   for(const r of records)batch.push(db().prepare('INSERT INTO records(id,owner,kind,data,revision,demo,archived,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(r.id,ctx.owner,r.kind,JSON.stringify(r.kind==='accounts'?{...r.data,status:'active'}:r.data),r.revision,r.demo,r.archived,r.created_at,r.updated_at));
   for(const r of records.filter((r:any)=>r.kind==='accounts'&&r.data.status!=='active'))batch.push(db().prepare('UPDATE records SET data=? WHERE id=? AND owner=?').bind(JSON.stringify(r.data),r.id,ctx.owner));
   for(const f of backup.files)batch.push(db().prepare('INSERT INTO files(id,owner,record_id,filename,content_type,size,created_at) VALUES(?,?,?,?,?,?,?)').bind(ids.get(f.id),ctx.owner,ids.get(f.record_id),f.filename,f.content_type,f.size,f.created_at));
   if(!Array.isArray(backup.events)||backup.events.length>20000)throw new Error('invalid_backup');batch.push(db().prepare('DELETE FROM events WHERE owner=?').bind(ctx.owner));for(const e of backup.events){if(typeof e.record_id!=='string'||typeof e.detail!=='string'||typeof e.action!=='string'||typeof e.created_at!=='string')throw new Error('invalid_backup');batch.push(db().prepare('INSERT INTO events(id,owner,record_id,action,created_at,detail) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),ctx.owner,ids.get(e.record_id)??e.record_id,e.action,e.created_at,JSON.stringify(remap(JSON.parse(e.detail)))));}
   const company=JSON.parse(backup.company??'{}');batch.push(db().prepare('INSERT INTO company(owner,data) VALUES(?,?) ON CONFLICT(owner) DO UPDATE SET data=excluded.data').bind(ctx.owner,JSON.stringify(company)));await db().batch(batch);
  }catch(e){for(const key of uploaded)await env.BUCKET?.delete(key);throw e;}return Response.json({ok:true,count:records.length});
 }
 if(action==='setupAccounting'){
  assertAdmin(ctx);const codes=[['411','Clients','asset'],['401','Fournisseurs','liability'],['425','Salaires à payer','liability'],['421','Avances salariés','asset'],['447','Timbre fiscal','liability'],['635','Taxes employeur','liability'],['532','Banque / caisse','asset'],['701','Ventes','revenue'],['4457','TVA collectée','liability'],['4456','TVA déductible','asset'],['607','Achats','expense'],['641','Coût salarial','expense'],['431','Organismes sociaux','liability'],['442','Retenues fiscales','liability']];const journalCodes=[['VE','Ventes'],['TR','Trésorerie'],['AC','Achats'],['PA','Paie']];const entries=await business.all(ctx.owner),batch:D1PreparedStatement[]=[],ids:Record<string,string>={};for(const [code,name,type] of codes){const existing=entries.find(e=>e.kind==='accounts'&&e.data.code===code);const id=existing?.id??crypto.randomUUID();ids[code]=id;if(!existing)batch.push(business.insert(ctx,'accounts',{name,code,type,status:'active'},id));}for(const [code,name] of journalCodes){const existing=entries.find(e=>e.kind==='journals'&&e.data.code===code);const id=existing?.id??crypto.randomUUID();ids[code]=id;if(!existing)batch.push(business.insert(ctx,'journals',{name,code,status:'active'},id));}if(!entries.some(e=>e.kind==='accountingSettings'&&e.data.status==='active'))batch.push(business.insert(ctx,'accountingSettings',{name:'Liaisons à contrôler',salesJournal:ids.VE,cashJournal:ids.TR,purchaseJournal:ids.AC,payrollJournal:ids.PA,receivable:ids['411'],payable:ids['401'],sales:ids['701'],vat:ids['4457'],inputVat:ids['4456'],cash:ids['532'],purchases:ids['607'],salary:ids['641'],social:ids['431'],tax:ids['442'],employeePayable:ids['425'],staffAdvances:ids['421'],stampTax:ids['447'],payrollTax:ids['635'],status:'active'}));if(batch.length)await db().batch(batch);return Response.json({ok:true});
 }
 const e=await business.record(ctx,b.id,undefined,true);if(b.revision!==e.revision)throw new Error('conflict');
 const actions:Record<string,string[]>={postStock:['receipts','deliveryNotes','inventories','transits'],receiveTransit:['transits'],postJournal:['journalEntries'],reverseJournal:['journalEntries'],closePeriod:['fiscalPeriods'],reschedule:['invoices'],rejectEffect:['effects'],approvePayroll:['payroll'],signContract:['contracts'],makeContract:['quotes','invoices','contracts','projects'],accountSource:['invoices','payments','receipts','payroll'],calculateStudy:['studies'],monitoringTicket:['monitoring']};if(!actions[action]?.includes(e.kind))throw new Error('invalid_action');
 const result=action==='postStock'?await business.postStock(ctx,e):action==='receiveTransit'?await business.postStock(ctx,e,true):action==='postJournal'?await business.postJournal(ctx,e):action==='reverseJournal'?await business.reverseJournal(ctx,e,b):action==='closePeriod'?await business.closePeriod(ctx,e):action==='reschedule'?await business.reschedule(ctx,e,b):action==='rejectEffect'?await business.rejectEffect(ctx,e,b.reason):action==='approvePayroll'?await business.approvePayroll(ctx,e):action==='signContract'?await business.signContract(ctx,e,b):action==='makeContract'?await business.makeContract(ctx,e,b):action==='accountSource'?await business.accountSource(ctx,e):action==='calculateStudy'?await business.calculateStudy(ctx,e):await business.monitoringTicket(ctx,e);
 return Response.json(result);
 }catch(e){return failure(e);}}
