import assert from 'node:assert/strict';
import {agendaItems,agendaConflicts,agendaICS,validateAgenda,validDate,assignees} from '../lib/solar/agenda-domain';
import {visibleNavigation,sectionOf,moduleMatches,navigationSections,workspaceHash} from '../lib/solar/navigation';
import {modules,byKey} from '../lib/solar/modules';
import {inScope,allows} from '../lib/solar/permissions';
import type {Entry} from '../lib/solar/domain';
const entry=(id:string,kind:string,data:any)=>({id,kind,data,revision:1} as Entry);
const monthly=entry('monthly','agendaEvents',{name:'دراسة الطاقة الشمسية، '.repeat(15),date:'2026-01-31',endDate:'2026-01-31',time:'09:00',endTime:'10:00',employeeId:'A',participants:[{employeeId:'B'}],repeat:'monthly',repeatInterval:1,repeatUntil:'2026-04-30',status:'planned',reminderMinutes:30});
assert.deepEqual(agendaItems([monthly],'2026-01-01','2026-03-31').map(e=>e.date),['2026-01-31','2026-02-28','2026-03-31']);
monthly.data.excludedDates='2026-02-28';assert.equal(agendaItems([monthly],'2026-02-01','2026-02-28').length,0);
const recurring=entry('week','agendaEvents',{...monthly.data,date:'2026-10-05',endDate:'2026-10-05',repeat:'weekly',repeatInterval:2,repeatUntil:'2026-11-02',excludedDates:''});
assert.deepEqual(agendaItems([recurring],'2026-10-01','2026-11-03').map(e=>e.date),['2026-10-05','2026-10-19','2026-11-02']);
const meetings=[entry('a','agendaEvents',{name:'A',date:'2026-10-10',time:'09:00',endTime:'10:00',employeeId:'A',status:'planned'}),entry('b','agendaEvents',{name:'B',date:'2026-10-10',time:'09:30',endTime:'10:30',employeeId:'A',status:'planned'}),entry('c','agendaEvents',{name:'C',date:'2026-10-10',time:'10:30',endTime:'11:00',employeeId:'A',status:'planned'}),entry('d','agendaEvents',{name:'Other employee',date:'2026-10-10',time:'09:00',endTime:'10:00',employeeId:'B',status:'planned'})];
assert.equal(agendaConflicts(agendaItems(meetings,'2026-10-10','2026-10-10').reverse()).length,1);
const leave=entry('leave','leave',{name:'Congé',startDate:'2026-10-10',endDate:'2026-10-11',employeeId:'A',status:'requested'});assert.equal(agendaConflicts(agendaItems([meetings[0],leave],'2026-10-10','2026-10-11')).length,0);leave.data.status='approved';assert.equal(agendaConflicts(agendaItems([meetings[0],leave],'2026-10-10','2026-10-11')).length,1);
const end=agendaItems([entry('overnight','planning',{name:'Intervention',date:'2026-10-10',time:'23:30',hours:2,employeeId:'A',status:'planned'})],'2026-10-10','2026-10-11')[0];assert.equal(end.endDate,'2026-10-11');
assert.equal(agendaItems([entry('legacy','planning',{name:'Legacy',date:'2026-10-10',time:'soon',hours:1})],'2026-10-10','2026-10-10').length,0);
assert.throws(()=>agendaItems([], '2026-01-01','2026-12-31'),/invalid_agenda_period/);assert.equal(validDate('2026-02-29'),false);
assert.throws(()=>validateAgenda({date:'2026-10-10',endDate:'2026-10-10',time:'09:00',endTime:'08:00'},'agendaEvents'),/invalid_agenda_range/);
assert.throws(()=>validateAgenda({date:'2026-10-10',time:'25:00',hours:1},'planning'),/invalid_agenda_time/);
assert.throws(()=>validateAgenda({dueDate:'2026-10-10',status:'done',checklist:[{label:'Inspect',done:'no'}]},'tasks'),/task_checklist_incomplete/);
assert.throws(()=>validateAgenda({...recurring.data,repeatUntil:'2028-01-01'},'agendaEvents'),/invalid_agenda_recurrence/);
assert.throws(()=>validateAgenda({...recurring.data,participants:[{employeeId:'A'},{employeeId:'A'}]},'agendaEvents'),/duplicate_participant/);
const ics=agendaICS(agendaItems([monthly],'2026-03-01','2026-03-31'));assert.match(ics,/TZID=Africa\/Tunis:20260331T090000/);assert.match(ics,/TRIGGER:-PT30M/);assert.ok(ics.split('\r\n').every(line=>Buffer.byteLength(line)<=75));assert.ok(!ics.includes('\nSUMMARY:'+monthly.data.name));
const ctx={admin:false,actor:'staff',email:'staff@example.com',employeeId:'A',branches:[],rules:[{module:'tasks',access:'read',add:'allow',edit:'deny',delete:'allow',scope:'self'}]};assert.equal(inScope(ctx,entry('own','tasks',{employeeId:'A'})),true);assert.equal(inScope(ctx,entry('other','tasks',{employeeId:'B'})),false);assert.equal(allows(ctx,'tasks','add'),true);assert.equal(allows(ctx,'tasks','edit'),false);assert.equal(allows(ctx,'tasks','delete'),true);
assert.equal(assignees({employeeId:'A',participants:[{employeeId:'A'},{employeeId:'B'}]}).length,2);
assert.ok(visibleNavigation(['tasks']).some(m=>m.key==='agenda'));assert.ok(!visibleNavigation(['tasks']).some(m=>m.key==='users'));
assert.equal(visibleNavigation().length,modules.length-1);assert.ok(modules.every(m=>navigationSections.some(s=>s.key===sectionOf(m))));assert.ok(moduleMatches(byKey.agenda,'reunions')===false);assert.ok(moduleMatches(byKey.agendaEvents,'reunions'));
assert.equal(workspaceHash('agenda','record',{employeeId:undefined,projectId:undefined}),'#module=agenda&record=record');assert.equal(new URLSearchParams(workspaceHash('agenda',undefined,{employeeId:'employee A'}).slice(1)).get('employeeId'),'employee A');
console.log('PASS: agenda recurrence/month end/exceptions, overlap/leave/overnight handling, Unicode ICS alarms, self scopes and permission-aware navigation coverage.');
