import assert from 'node:assert/strict';
import {annualTax,automaticPayroll,journalTotals,leaveBalance,profitability,solarSizing} from '../lib/solar/business-domain.ts';
import {importCsv,parseCsv} from '../lib/solar/csv.ts';
import {validate,type Entry} from '../lib/solar/domain.ts';
const e=(id:string,kind:string,data:any):Entry=>({id,kind,data,revision:1,archived:0,demo:0,createdAt:'',updatedAt:''});
const policy=e('policy','payrollPolicies',{status:'validated',startDate:'2026-01-01',endDate:'2026-12-31',source:'Test',employeeRate:9.18,employerRate:16.57,unemploymentEmployee:.5,unemploymentEmployer:.5,accidentRate:.4,tfpRate:1,foprolosRate:1,professionalRate:10,professionalCap:2000000,cssRate:.5,cssThreshold:5000000,monthlyHours:208,overtimeMultiplier:1.25,leavePerMonth:1,leaveCap:12,brackets:[{ceiling:5000000,rate:0},{ceiling:10000000,rate:15},{ceiling:20000000,rate:25},{ceiling:0,rate:30}]});
assert.equal(annualTax(15000000,policy.data.brackets),2000000);
assert.throws(()=>annualTax(1,[{ceiling:5000000,rate:0}]));
assert.throws(()=>journalTotals([{accountId:'a',debit:100},{accountId:'b',credit:99}]));
const employee=e('employee','employees',{name:'Test',salary:1000000,startDate:'2026-10-16',agencyId:'agency'});
let p=automaticPayroll(employee,'2026-10',policy,[]);assert.equal(p.paidDays,16);assert.equal(p.base,516129);
p=automaticPayroll(employee,'2026-10',policy,[e('leave','leave',{employeeId:employee.id,type:'unpaidLeave',status:'approved',startDate:'2026-10-20',endDate:'2026-10-22'}),e('attendance','attendance',{employeeId:employee.id,status:'approved',date:'2026-10-25',overtime:8}),e('commission','commissions',{employeeId:employee.id,status:'approved',period:'2026-10',amount:50000})]);assert.equal(p.unpaidDays,3);assert.equal(p.base,419355);assert.equal(p.overtime,48077);assert.equal(p.gross,517432);assert.equal(p.net+p.deductions,p.gross);assert.equal(p.employerCost,p.gross+p.employerCharges);
assert.throws(()=>automaticPayroll(employee,'2026-10',{...policy,data:{...policy.data,status:'draft'}},[]));
const balance=leaveBalance(e('e','employees',{startDate:'2026-01-01',openingLeave:2}),policy,[e('l','leave',{employeeId:'e',status:'approved',type:'paidLeave',startDate:'2026-06-01',days:3})],'2026-06-30');assert.equal(balance.balance,5);
const margins=profitability([e('p','projects',{name:'Project'}),e('i','invoices',{projectId:'p',status:'issued',subtotal:100000,discount:10000}),e('m','movements',{projectId:'p',direction:'stockOut',quantity:2,unitCost:10000}),e('t','movements',{projectId:'p',transferId:'transit',direction:'stockOut',quantity:2,unitCost:10000})],[]);assert.equal(margins[0].margin,70000);
assert.equal(solarSizing({capacity:3,loadKw:2,autonomyHours:4,usableBatteryPercent:80}).batteryRequired,10);assert.throws(()=>solarSizing({capacity:3,loadKw:2,autonomyHours:4,usableBatteryPercent:0}));
assert.deepEqual(parseCsv('name;notes\r\n"Test; client";"Deux lignes\navec ""citation"""'),[{name:'Test; client',notes:'Deux lignes\navec "citation"'}]);assert.throws(()=>parseCsv('name;name\na;b'));assert.throws(()=>parseCsv('name;phone\n"Non fermé;20000000'));
assert.throws(()=>parseCsv('name; name\na;b'));assert.throws(()=>parseCsv('name;notes\nTest;"quoted"extra'));
assert.equal(importCsv('products','name;sku;salePrice\nPanneau;PV-1;123,456')[0].salePrice,123456);assert.throws(()=>importCsv('clients','name;unknown\nTest;A'));
assert.throws(()=>validate('bankProfiles',{name:'Bad',bank:'B',instrument:'cheque',width:100,height:50,positions:[{key:'beneficiary',x:90,y:10,width:20,fontSize:10}],status:'draft'}));
console.log('PASS: progressive tax, month prorata/unpaid leave/overtime/commissions, contribution snapshots, leave accrual, project margin, solar sizing, CSV quoting and bank paper bounds.');
