import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),wr=createRequire(require.resolve('wrangler'));
const {Miniflare,createFetchMock}=wr('miniflare');const fetchMock=createFetchMock();fetchMock.disableNetConnect();fetchMock.get('https://re.jrc.ec.europa.eu').intercept({path:p=>p.startsWith('/api/v5_3/PVcalc?'),method:'GET'}).reply(200,{outputs:{monthly:{fixed:Array.from({length:12},(_,i)=>({month:i+1,E_m:100+i}))},totals:{fixed:{E_y:1266}}}});fetchMock.get('https://monitoringapi.solaredge.com').intercept({path:p=>p.startsWith('/site/123/overview?'),method:'GET'}).reply(200,{overview:{lastUpdateTime:'2026-10-08 10:00:00',lastDayData:{energy:12500}}});
const root=path.resolve('dist/server');
async function jsFiles(folder){let result=[];for(const e of await fs.readdir(folder,{withFileTypes:true})){const p=path.join(folder,e.name);if(e.isDirectory())result.push(...await jsFiles(p));else if(/\.(js|mjs)$/.test(e.name))result.push(p);}return result;}
const js=await jsFiles(root);js.sort((a,b)=>a===path.join(root,'index.js')?-1:b===path.join(root,'index.js')?1:0);
const mf=new Miniflare({fetchMock,bindings:{SOLAREDGE_API_KEY:'test-key-only'},modules:js.map(p=>({type:'ESModule',path:p})),modulesRoot:root,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],assets:{directory:path.resolve('dist/client'),binding:'ASSETS',routerConfig:{has_user_worker:true,invoke_user_worker_ahead_of_assets:true}},cf:false});
try{
 const db=await mf.getD1Database('DB');
 for(const file of (await fs.readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort()){
  const source=await fs.readFile(path.join('drizzle',file),'utf8');
  for(const statement of source.split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(statement).run();
 }
 const owner='business-test';
 async function request(endpoint,body,who=owner,email='owner@example.com'){
  const response=await mf.dispatchFetch('https://solar.local'+endpoint,{method:body?'POST':'GET',headers:{'oai-authenticated-user-id':who,'oai-authenticated-user-email':email,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
  const raw=await response.text();let data;try{data=JSON.parse(raw)}catch{throw new Error(response.status+' '+raw.slice(0,300))}return [response.status,data];
 }
 const workspace=(body,who,email)=>request('/api/workspace',body,who,email),business=(body)=>request('/api/business',body);
 const ok=([code,data])=>{assert.equal(code,200,JSON.stringify(data));return data};
 async function snapshot(){return ok(await workspace());}
 async function get(id){return (await snapshot()).records.find(r=>r.id===id);}
 async function save(kind,data,old){return ok(await workspace({action:'save',kind,data,id:old?.id,revision:old?.revision,requestId:crypto.randomUUID()})).id;}
 async function action(name,id,extra={}){const e=await get(id);return business({action:name,id,revision:e.revision,...extra});}
 async function change(id,fields){const old=await get(id);return save(old.kind,{...old.data,...fields},old);}
 async function fail(promise,error){let result;try{result=await promise}catch(e){if(error)assert.ok(e.message.includes(error),e.message);return;}const [status,d]=result;assert.ok(status>=400,JSON.stringify(d));if(error)assert.equal(d.error,error);}
 const a=await save('agencies',{name:'Tunis',code:'TUN',status:'active'}),a2=await save('agencies',{name:'Sousse',code:'SOU',status:'active'});
 const warehouse=await save('warehouses',{name:'Dépôt A',code:'A',agencyId:a,status:'active'}),wh2=await save('warehouses',{name:'Dépôt B',code:'B',agencyId:a,status:'active'});
 const client=await save('clients',{name:'Client test',phone:'20000000',type:'individual',status:'active'}),supplier=await save('suppliers',{name:'Fournisseur test',status:'active'});
 const product=await save('products',{name:'Panneau',sku:'TEST-PV',category:'panel',tracking:'quantityOnly',unit:'piece',purchasePrice:10000,salePrice:15000,status:'active'});
 const order=await save('orders',{name:'Achat 10',amount:1,supplierId:supplier,date:'2026-10-01',items:[{productId:product,quantity:10,price:10000,tax:19}],agencyId:a,status:'ordered'});
 const receipt=(n)=>save('receipts',{name:'Réception '+n,orderId:order,warehouse,date:'2026-10-02',items:[{productId:product,quantity:n}],status:'draft'});
 const r1=await receipt(3);ok(await action('postStock',r1));assert.equal((await get(order)).data.status,'partial');await fail(action('postStock',r1),'already_posted');
 const rBad=await receipt(8);await fail(action('postStock',rBad),'overreceipt');assert.equal((await get(rBad)).data.status,'draft');ok(await workspace({action:'archive',id:rBad,revision:(await get(rBad)).revision}));
 const r2=await receipt(7);ok(await action('postStock',r2));assert.equal((await get(order)).data.status,'received');
 const stock=async(w)=>((await snapshot()).stock.find(s=>s.product_id===product&&s.warehouse===w)?.quantity??0);
 assert.equal(await stock(warehouse),10000);
 const transit=await save('transits',{name:'Transit 2',from:warehouse,to:wh2,date:'2026-10-03',items:[{productId:product,quantity:2}],status:'draft'});ok(await action('postStock',transit));assert.equal(await stock(warehouse),8000);assert.equal(await stock(wh2),0);ok(await action('receiveTransit',transit));assert.equal(await stock(wh2),2000);await fail(action('receiveTransit',transit),'invalid_status');
 const delivery=await save('deliveryNotes',{name:'Livraison 1',clientId:client,warehouse,date:'2026-10-04',items:[{productId:product,quantity:1}],status:'draft'});ok(await action('postStock',delivery));assert.equal(await stock(warehouse),7000);
 const inventory=await save('inventories',{name:'Inventaire',warehouse,date:'2026-10-05',items:[{productId:product,quantity:6}],status:'draft'});ok(await action('postStock',inventory));assert.equal(await stock(warehouse),6000);
 ok(await business({action:'setupAccounting'}));let entries=(await snapshot()).records;const ac=code=>entries.find(r=>r.kind==='accounts'&&r.data.code===code).id,journal=entries.find(r=>r.kind==='journals').id;
 const je=await save('journalEntries',{name:'Écriture test',date:'2026-10-05',agencyId:a,journalId:journal,reference:'PIECE',rows:[{accountId:ac('532'),debit:10000},{accountId:ac('701'),credit:9000}],status:'draft'});await fail(action('postJournal',je),'unbalanced_entry');await change(je,{rows:[{accountId:ac('532'),debit:10000},{accountId:ac('701'),credit:10000}]});ok(await action('postJournal',je));await fail(change(je,{reference:'MODIFICATION'}),'use_business_action');ok(await action('reverseJournal',je,{date:'2026-10-06',reason:'Correction'}));
 const period=await save('fiscalPeriods',{name:'Début octobre',startDate:'2026-10-01',endDate:'2026-10-07',status:'open'});
 async function invoice(name,agencyId=a){const id=await save('invoices',{name,clientId:client,agencyId,date:'2026-10-08',dueDate:'2026-10-10',invoiceType:'invoice',status:'draft',lines:[{description:'Test',quantity:1,price:100000,tax:0}],stamp:1000});await change(id,{status:'issued'});return id;}
 const inv1=await invoice('Facture A'),inv2=await invoice('Facture B');ok(await action('accountSource',inv1));let report=ok(await business());assert.equal(report.balance.reduce((n,r)=>n+r.debit-r.credit,0),0);
 const settlement={action:'settleInvoices',requestId:crypto.randomUUID(),data:{name:'Règlement multiple',clientId:client,direction:'incoming',date:'2026-10-08',amount:151000,method:'transfer',agencyId:a,status:'cleared'},invoices:[{invoiceId:inv1,amount:101000},{invoiceId:inv2,amount:50000}]};const payment=ok(await business(settlement)).id;ok(await business(settlement));await fail(business({...settlement,data:{...settlement.data,amount:151001}}),'conflict');
 ok(await action('accountSource',payment));ok(await action('reschedule',inv2,{firstDate:'2026-11-30',count:3,reason:'Accord client'}));report=ok(await business());assert.equal(report.dues.reduce((n,r)=>n+r.outstanding,0),51000);assert.equal(report.dues.length,3);
 ok(await workspace({action:'cancelPayment',id:payment,revision:(await get(payment)).revision,reason:'Virement rejeté'}));report=ok(await business());assert.equal(report.dues.reduce((n,r)=>n+r.outstanding,0),202000);assert.equal((await snapshot()).records.filter(r=>r.kind==='journalEntries'&&r.data.originalId===(payment+'-accounting')).length,1);
 ok(await business({action:'setupPayroll'}));let policy=(await snapshot()).records.find(r=>r.kind==='payrollPolicies');
 const employee=await save('employees',{name:'Salarié',position:'Technicien',salary:1000000,startDate:'2026-01-01',agencyId:a,status:'active'});await fail(business({action:'calculatePayroll',employeeId:employee,period:'2026-10'}),'payroll_policy_required');await change(policy.id,{status:'validated',source:'Paramètres test contrôlés'});
 const leave=await save('leave',{name:'Congé',employeeId:employee,type:'paidLeave',startDate:'2026-10-01',endDate:'2026-10-02',days:2,status:'approved'});await fail(save('leave',{name:'Chevauchement',employeeId:employee,type:'paidLeave',startDate:'2026-10-02',endDate:'2026-10-03',days:2,status:'approved'}));
 const commission=await save('commissions',{name:'Commission',employeeId:employee,invoiceId:inv1,basis:'invoiced',rate:5,period:'2026-10',status:'approved'});
 const pay=ok(await business({action:'calculatePayroll',employeeId:employee,period:'2026-10'}));assert.equal(pay.data.commissions,5050);assert.equal(pay.data.cnssDeduction,Math.round(pay.data.gross*.0918));assert.equal(pay.data.policySnapshot.status,'validated');ok(await action('approvePayroll',pay.id));assert.equal((await get(commission)).data.status,'paid');ok(await action('accountSource',pay.id));
 const role=await save('roles',{name:'Lecteur agence Tunis',rules:[{module:'invoices',access:'read'},{module:'agencies',access:'read'},{module:'clients',access:'read'}],status:'active'});
 await save('users',{name:'Employé accès',email:'staff@example.com',roleId:role,branches:[{agencyId:a}],status:'active'});const hiddenInvoice=await invoice('Facture Sousse',a2);const staff=ok(await workspace(undefined,'staff-id','staff@example.com'));assert.equal(staff.access.admin,false);assert.ok(staff.records.some(r=>r.id===inv1));assert.ok(!staff.records.some(r=>r.id===hiddenInvoice));assert.ok(!staff.records.some(r=>r.kind==='payroll'));await fail(workspace({action:'save',kind:'clients',data:{name:'Forbidden'}},'staff-id','staff@example.com'),'forbidden');
 ok(await business({action:'setupTemplates'}));let template=(await snapshot()).records.find(r=>r.kind==='contractTemplates'&&r.data.type==='sale'&&r.data.language==='fr');await change(template.id,{status:'approved'});const contract=ok(await action('makeContract',inv1,{templateId:template.id})).id;assert.ok((await get(contract)).data.terms.includes('Client test'));
 const fd=new FormData();fd.set('recordId',contract);fd.set('file',new File(['Document signé test'],'contrat-signe.pdf',{type:'application/pdf'}));const uploadRequest=new Request('https://solar.local/api/files',{method:'POST',body:fd});const uploaded=await mf.dispatchFetch(uploadRequest.url,{method:'POST',headers:{...Object.fromEntries(uploadRequest.headers),'oai-authenticated-user-id':owner,'oai-authenticated-user-email':'owner@example.com'},body:await uploadRequest.arrayBuffer()});assert.equal(uploaded.status,200,await uploaded.clone().text());const file=await uploaded.json();ok(await action('signContract',contract,{signedBy:'Client test',fileId:file.id}));assert.equal((await get(contract)).data.signatureHash.length,64);await fail(change(contract,{terms:'Altéré'}),'use_signature_action');
 const bank=await save('bankProfiles',{name:'Profil test',bank:'Banque test',instrument:'cheque',width:175,height:80,positions:[{key:'beneficiary',x:30,y:20,width:90,fontSize:10}],status:'draft'});await fail(save('bankProfiles',{name:'Hors papier',bank:'Banque test',instrument:'cheque',width:100,height:50,positions:[{key:'beneficiary',x:99,y:20,width:20,fontSize:10}],status:'draft'}));
 ok(await action('closePeriod',period));await fail(action('reverseJournal',inv1+'-accounting',{date:'2026-10-06',reason:'Période fermée'}),'period_closed');
 const project=await save('projects',{name:'Installation test',clientId:client,agencyId:a,regime:'outsideProsol',status:'commissioned',solarEdgeSiteId:'123'});
 const study=await save('studies',{name:'Étude API',clientId:client,projectId:project,agencyId:a,capacity:3,assumptions:'Hypothèses validées test',latitude:36.8,longitude:10.2,losses:14,tilt:30,azimuth:0,loadKw:2,autonomyHours:4,usableBatteryPercent:80,status:'draft'});ok(await action('calculateStudy',study));assert.equal((await get(study)).data.productionYear,1266);assert.equal((await get(study)).data.batteryRequired,10);assert.equal((await get(study)).data.assumptions,'Hypothèses validées test');
 const reading=ok(await business({action:'syncSolarEdge',projectId:project})).id;assert.equal((await get(reading)).data.production,12.5);
 const low=await save('monitoring',{name:'Relevé faible',projectId:project,agencyId:a,date:'2026-10-08',observedAt:'2026-10-08 10:00:00',production:2,expected:10,connection:'connected',source:'manual',status:'recorded'});const ticket=ok(await action('monitoringTicket',low)).id;assert.equal(ok(await action('monitoringTicket',low)).id,ticket);
 await change(ac('701'),{status:'inactive'});
 const importRows=[{name:'Import test',phone:'20000000',type:'business',status:'active'}];assert.equal(ok(await business({action:'import',kind:'clients',rows:importRows,commit:false})).count,1);assert.ok(!(await snapshot()).records.some(r=>r.data.name==='Import test'));ok(await business({action:'import',kind:'clients',rows:importRows,commit:true}));
 const rejectionPayment=ok(await business({...settlement,requestId:crypto.randomUUID(),data:{...settlement.data,amount:25000},invoices:[{invoiceId:inv1,amount:25000}]})).id;
 const effect=await save('effects',{name:'Traite rejet test',instrument:'bill',number:'TRAITE-TEST',bank:'Banque test',beneficiary:'SoluMove',date:'2026-10-08',dueDate:'2026-11-08',amount:25000,paymentId:rejectionPayment,agencyId:a,status:'deposited'});ok(await action('rejectEffect',effect,{reason:'Banque : rejet'}));assert.equal((await get(rejectionPayment)).data.status,'cancelled');
 const livePayment=ok(await business({...settlement,requestId:crypto.randomUUID(),data:{...settlement.data,amount:50000},invoices:[{invoiceId:inv1,amount:25000},{invoiceId:inv2,amount:25000}]})).id;assert.equal((await snapshot()).allocations.filter(r=>r.payment_id===livePayment).reduce((n,r)=>n+r.amount,0),50000);
 await fail(business({...settlement,requestId:crypto.randomUUID(),data:{...settlement.data,amount:1000000},invoices:[{invoiceId:inv1,amount:1000000}]}),'overpayment');
 const deniedFile=await request('/api/files?id='+file.id,undefined,'staff-id','staff@example.com');assert.equal(deniedFile[0],403);
 const wh3=await save('warehouses',{name:'Dépôt Sousse',code:'SOU-D',agencyId:a2,status:'active'});const destinationRole=await save('roles',{name:'Réception Sousse',rules:[{module:'transits',access:'write'},{module:'movements',access:'write'},{module:'warehouses',access:'read'},{module:'products',access:'read'}],status:'active'});await save('users',{name:'Réceptionnaire',email:'receiver@example.com',roleId:destinationRole,branches:[{agencyId:a2}],status:'active'});
 const crossTransit=await save('transits',{name:'Inter-agences',from:wh2,to:wh3,date:'2026-10-09',items:[{productId:product,quantity:1}],status:'draft'});const destinationSnapshot=ok(await workspace(undefined,'receiver','receiver@example.com'));assert.ok(destinationSnapshot.records.some(r=>r.id===crossTransit));assert.ok(!destinationSnapshot.records.some(r=>r.id===wh2));await fail(request('/api/business',{action:'postStock',id:crossTransit,revision:(await get(crossTransit)).revision},'receiver','receiver@example.com'),'forbidden_branch');ok(await action('postStock',crossTransit));ok(await request('/api/business',{action:'receiveTransit',id:crossTransit,revision:(await get(crossTransit)).revision},'receiver','receiver@example.com'));assert.equal(await stock(wh3),1000);
 const racePayment=ok(await business({...settlement,requestId:crypto.randomUUID(),data:{...settlement.data,date:'2026-11-08',amount:10000},invoices:[{invoiceId:inv1,amount:10000}]})).id;const raceRevision=(await get(racePayment)).revision;
 const raceResults=await Promise.all([business({action:'accountSource',id:racePayment,revision:raceRevision}),workspace({action:'cancelPayment',id:racePayment,revision:raceRevision,reason:'Concurrent cancellation test'})]);assert.ok(raceResults.every(([status,d])=>status===200||status===400&&d.error==='conflict'),JSON.stringify(raceResults));if((await get(racePayment)).data.status==='cleared')ok(await workspace({action:'cancelPayment',id:racePayment,revision:(await get(racePayment)).revision,reason:'Retry after conflict'}));const raceJournal=(await snapshot()).records.find(r=>r.kind==='journalEntries'&&r.data.sourceId===racePayment&&!r.data.originalId);if(raceJournal)assert.ok((await snapshot()).records.some(r=>r.data.originalId===raceJournal.id));
 const backup=ok(await request('/api/business?backup=1'));assert.equal(backup.files.length,1);const corrupt=structuredClone(backup);const damaged=Buffer.from(corrupt.files[0].bytes,'base64');damaged[0]^=1;corrupt.files[0].bytes=damaged.toString('base64');await fail(request('/api/business',{action:'restore',backup:corrupt},'restored-owner','restore@example.com'),'backup_checksum_mismatch');assert.equal(ok(await workspace(undefined,'restored-owner','restore@example.com')).records.length,0);const restored=ok(await request('/api/business',{action:'restore',backup},'restored-owner','restore@example.com'));assert.equal(restored.count,backup.records.length);const copy=ok(await workspace(undefined,'restored-owner','restore@example.com'));assert.equal(copy.records.filter(r=>r.kind==='journalEntries').length,(await snapshot()).records.filter(r=>r.kind==='journalEntries').length);assert.equal(copy.stock.find(s=>s.product_id===copy.records.find(r=>r.kind==='products'&&r.data.sku==='TEST-PV').id&&s.warehouse===copy.records.find(r=>r.kind==='warehouses'&&r.data.name==='Dépôt A').id).quantity,6000);const restoredBackup=ok(await request('/api/business?backup=1',undefined,'restored-owner','restore@example.com'));assert.equal(restoredBackup.events.length,backup.events.length);assert.equal(copy.files.length,1);assert.equal(copy.allocations.reduce((n,r)=>n+r.amount,0),50000);assert.equal(restoredBackup.records.find(r=>r.kind==='contracts'&&JSON.parse(r.data).status==='signed')&&copy.records.find(r=>r.kind==='contracts'&&r.data.status==='signed').data.signatureHash,(await get(contract)).data.signatureHash);await fail(request('/api/business',{action:'restore',backup},'restored-owner','restore@example.com'),'restore_requires_empty_workspace');
 console.log('PASS: partial/overflow receipts, delivery/inventory/transit, journals/reversal/closing, multi-invoice idempotent settlement, rescheduling/cancellation conservation, automatic payroll/commissions, branch permissions, contract signature hash, bank calibration bounds, mocked PVGIS/SolarEdge, idempotent monitoring ticket, imports, effect rejection and complete backup/restore including live allocations.');
}finally{await mf.dispose()}
