import assert from 'node:assert/strict';
import {tejXML,validateTej} from '../lib/solar/fiscal';
import {retentionAmounts,dashboardReport,effectiveWithholdings,appendStockQR} from '../lib/solar/enterprise-domain';
import {allows,inScope} from '../lib/solar/permissions';
import {validate,type Entry} from '../lib/solar/domain';
const ctx={admin:false,actor:'actor',email:'staff@example.com',branches:['A'],warehouses:['W'],rules:[{module:'exitNotes',access:'read',add:'allow',edit:'deny',delete:'deny',scope:'warehouses'},{module:'clients',access:'write',scope:'agencies'},{module:'messages',access:'read',add:'allow',scope:'all'},{module:'notifications',access:'read',scope:'all'}]};
assert.equal(allows(ctx,'exitNotes','add'),true);assert.equal(allows(ctx,'exitNotes','edit'),false);assert.equal(allows(ctx,'exitNotes','delete'),false);
assert.equal(inScope(ctx,{id:'1',kind:'exitNotes',data:{warehouse:'W',agencyId:'B'}}),true);assert.equal(inScope(ctx,{id:'1',kind:'exitNotes',data:{warehouse:'OTHER',agencyId:'A'}}),false);
assert.equal(inScope(ctx,{id:'c',kind:'clients',data:{agencyId:'A'}}),true);assert.equal(inScope(ctx,{id:'c',kind:'clients',data:{agencyId:'B'}}),false);
assert.equal(inScope(ctx,{id:'m',kind:'messages',data:{members:[{email:'other@example.com'}]}}),false);assert.equal(inScope(ctx,{id:'m',kind:'messages',data:{members:[{email:'staff@example.com'}]}}),true);
assert.equal(inScope({...ctx,admin:true},{id:'n',kind:'notifications',data:{recipientEmail:'other@example.com'}}),false);
const operation={code:'RS7_000001',invoiceYear:'2026',cnpc:'0',charge:'0',base:1000000,vatRate:19,rate:1.5,vatWithholdingRate:25};
const a=retentionAmounts([operation]);assert.equal(a.total,1190000);assert.equal(a.incomeWithheld,17850);assert.equal(a.vatWithheld,47500);assert.equal(a.net,1124650);
assert.throws(()=>retentionAmounts([{...operation,base:5000000000000000,vatRate:0,rate:0,vatWithholdingRate:0},{...operation,base:5000000000000000,vatRate:0,rate:0,vatWithholdingRate:0}]));
assert.throws(()=>retentionAmounts([{...operation,rate:100,vatWithholdingRate:100}]));
const d={identifierType:'MatriculeFiscal',identifier:'0001238L',category:'PM',resident:'1',beneficiaryName:'Entreprise',address:'Tunis',email:'test@example.com',phone:'20000000',date:'2026-10-09',reference:'RS-001',operation:'add',operations:[operation]};
const xml=tejXML({taxId:'0001238L'},'2026-10','0',[d]);assert.equal(xml.filename,'0001238L-2026-10-0.xml');assert.equal((await validateTej(xml.xml)).valid,true);
assert.equal((await validateTej(tejXML({taxId:'0001238L'},'2026-10','1',[{...d,operation:'cancel'}]).xml)).valid,true);
await assert.rejects(()=>validateTej(xml.xml.replace('<TotalMontantTTC>1190000</TotalMontantTTC>','')));
assert.throws(()=>tejXML({taxId:'0001238L'},'2026-10','0',[{...d,beneficiaryName:'Societe & Co'}]));
assert.throws(()=>tejXML({taxId:'invalid'},'2026-10','0',[d]));assert.throws(()=>tejXML({taxId:'0001238L'},'2026-09','0',[d]));
const make=(id:string,kind:string,data:any)=>({id,kind,data,revision:1,createdAt:'2026-10-01',updatedAt:'2026-10-01',archived:0,demo:0}) as Entry;
assert.equal(effectiveWithholdings([make('T1','withholdings',{direction:'issued',reference:'R',operation:'add',status:'validated',withheld:100}),make('T2','withholdings',{direction:'issued',reference:'R',operation:'modify',status:'validated',withheld:80})])[0].data.withheld,80);
assert.equal(effectiveWithholdings([make('T1','withholdings',{direction:'issued',reference:'R',operation:'add',status:'validated'}),make('T3','withholdings',{direction:'issued',reference:'R',operation:'cancel',status:'validated'})]).length,0);
const qrProducts=[make('Q','products',{tracking:'serialTracking',purchasePrice:10000})];const qrRows=appendStockQR([],'SOLU1|Q|SM-001',qrProducts);assert.equal(qrRows[0].quantity,1);assert.equal(appendStockQR(qrRows,'SOLU1|Q|SM-002',qrProducts)[0].quantity,2);assert.throws(()=>appendStockQR(qrRows,'SOLU1|Q|SM-001',qrProducts));
const report=dashboardReport({records:[make('A','agencies',{name:'Tunis'}),make('W','warehouses',{agencyId:'A'}),make('P','products',{purchasePrice:10000}),make('I','invoices',{agencyId:'A',date:'2026-10-09',status:'issued',invoiceType:'invoice',subtotal:100000,tax:19000}),make('C','invoices',{agencyId:'A',date:'2026-10-09',status:'issued',invoiceType:'creditNote',subtotal:20000,tax:3800}),make('D','installments',{agencyId:'A',invoiceId:'I',status:'open',amount:100000,dueDate:'2026-11-01'}),make('F','cashForecast',{agencyId:'A',status:'planned',scenario:'base',direction:'incoming',amount:50000,probability:80,sourceId:'D',dueDate:'2026-11-01'})],allocations:[{installment_id:'D',amount:20000}],stock:[{warehouse:'W',product_id:'P',quantity:2000}],files:[],serials:[],events:[],company:{}},{from:'2026-01-01',to:'2026-12-31',opening:10000,warehouse:'W'});
assert.equal(report.kpis.sales,80000);assert.equal(report.kpis.outputVat,15200);assert.equal(report.kpis.receivables,80000);assert.equal(report.kpis.stockValue,20000);assert.equal(report.cash.length,1);assert.equal(report.cash[0].balance,50000);
const order=validate('salesOrders',{name:'BC',clientId:'C',date:'2026-10-09',items:[{productId:'P',quantity:2,price:10000,tax:19}],status:'confirmed'});assert.equal(order.total,23800);
console.log('PASS: granular permissions, warehouse isolation, chat privacy, exact withholding calculations, official TEJ XSD exports and rejection, credit-net BI, stock valuation and forecast deduplication.');
