import {validateBusinessSave,cancelPayment} from '@/lib/solar/business-server';
import {db,access,can,assertModule,assertRecord,assertAdmin,visible,failure} from '@/lib/solar/server';
import {byKey} from '@/lib/solar/modules';
import {validate,Entry,isLocked,plan} from '@/lib/solar/domain';
import {demoEntries} from '@/lib/solar/demo';
const decode=(r:any):Entry=>({id:r.id,kind:r.kind,data:JSON.parse(r.data),revision:r.revision,demo:r.demo,archived:r.archived,createdAt:r.created_at,updatedAt:r.updated_at});
const newId=()=>crypto.randomUUID();
function insert(owner:string,kind:string,id:string,data:Record<string,any>,demo=0){const now=new Date().toISOString();return db().prepare('INSERT INTO records(id,owner,kind,data,revision,demo,archived,created_at,updated_at) VALUES(?,?,?,?,1,?,0,?,?)').bind(id,owner,kind,JSON.stringify(data),demo,now,now);}
async function get(owner:string,id:string){const r=await db().prepare('SELECT * FROM records WHERE id=? AND owner=? AND archived=0').bind(id,owner).first();if(!r)throw new Error('not_found');return decode(r);}
async function links(owner:string,kind:string,data:Record<string,any>){for(const f of byKey[kind].fields){if(f.type==='link'&&data[f.key]){const r=await get(owner,data[f.key]);if(r.kind!==f.target)throw new Error('invalid_reference');}}
if(data.lines){for(const line of data.lines){if(line.productId){const p=await get(owner,line.productId);if(p.kind!=='products')throw new Error('invalid_reference');}}}
if(data.projectId&&data.clientId){const p=await get(owner,data.projectId);if(p.data.clientId!==data.clientId)throw new Error('client_project_mismatch');}
if(kind==='visits'&&data.siteId){const s=await get(owner,data.siteId);if(s.data.clientId!==data.clientId)throw new Error('client_site_mismatch');}
if(kind==='projects'&&data.siteId){const s=await get(owner,data.siteId);if(s.data.clientId!==data.clientId)throw new Error('client_site_mismatch');}
if(kind==='payments'&&data.installmentId){const inst=await get(owner,data.installmentId);if(inst.data.clientId!==data.clientId)throw new Error('invalid_allocation');}
if(kind==='installments'){const inv=await get(owner,data.invoiceId);if(inv.data.clientId!==data.clientId||inv.data.invoiceType==='creditNote'||inv.data.status!=='issued')throw new Error('invalid_invoice');}
}
export async function GET(){try{const ctx=await access();const owner=ctx.owner;const [rs,al,st,ev,co,fi,se]=await Promise.all([db().prepare('SELECT * FROM records WHERE owner=? AND archived=0 ORDER BY created_at DESC').bind(owner).all(),db().prepare('SELECT * FROM allocations WHERE owner=?').bind(owner).all(),db().prepare('SELECT * FROM stock_balances WHERE owner=?').bind(owner).all(),db().prepare('SELECT * FROM events WHERE owner=? ORDER BY created_at DESC LIMIT 100').bind(owner).all(),db().prepare('SELECT data FROM company WHERE owner=?').bind(owner).first<{data:string}>(),db().prepare('SELECT * FROM files WHERE owner=? ORDER BY created_at DESC').bind(owner).all(),db().prepare('SELECT * FROM serial_locations WHERE owner=?').bind(owner).all()]);const records=rs.results.map(decode).filter((r:Entry)=>visible(ctx,r));const ids=new Set(records.map((r:Entry)=>r.id));return Response.json({access:{actor:ctx.actor,owner:ctx.owner,admin:ctx.admin,branches:ctx.branches,read:Object.keys(byKey).filter(k=>can(ctx,k)),write:Object.keys(byKey).filter(k=>can(ctx,k,true))},records,allocations:al.results.filter((r:any)=>ids.has(r.payment_id)&&ids.has(r.installment_id)),stock:st.results.filter((r:any)=>ids.has(r.product_id)&&ids.has(r.warehouse)),events:ctx.admin?ev.results:ev.results.filter((r:any)=>ids.has(r.record_id)),company:co?JSON.parse(co.data):{},files:fi.results.filter((r:any)=>ids.has(r.record_id)),serials:se.results.filter((r:any)=>ids.has(r.product_id)&&(ids.has(r.warehouse)||ids.has(r.project_id)))},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(request:Request){try{const ctx=await access();const owner=ctx.owner;if(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin)throw new Error('invalid_origin');if(Number(request.headers.get('content-length')||0)>200000)throw new Error('request_too_large');const raw=await request.text();if(raw.length>200000)throw new Error('request_too_large');const body=JSON.parse(raw);const {action}=body;
if(action==='save'){const kind=body.kind;assertModule(ctx,kind,true);if(!byKey[kind])throw new Error('invalid_module');if(kind==='movements'&&body.id)throw new Error('immutable');if(kind==='installments')throw new Error('use_schedule');const data=validate(kind,body.data);assertRecord(ctx,{id:body.id??'',kind,data} as Entry,true);await links(owner,kind,data);await validateBusinessSave(ctx,kind,data,body.id);
for(const f of byKey[kind].fields){if(f.type==='link'&&data[f.key])assertRecord(ctx,await get(owner,data[f.key]));if(f.type==='rows')for(const row of data[f.key]??[])for(const c of f.columns??[])if(c.type==='link'&&row[c.key])assertRecord(ctx,await get(owner,row[c.key]));}if(kind==='movements'){const p=await get(owner,data.productId);const w=await get(owner,data.warehouse);data.unitCost=p.data.purchasePrice||0;data.serialList=String(data.serials||'').split(/\r?\n/).map((v:string)=>v.trim()).filter(Boolean);if(new Set(data.serialList).size!==data.serialList.length)throw new Error('duplicate_serial');if((p.data.tracking==='serialTracking'||data.serialList.length>0)&&(!Number.isInteger(data.quantity)||data.serialList.length!==data.quantity))throw new Error('serial_count');data.agencyId=w.data.agencyId;const scaled=data.quantity*1000;if(!Number.isSafeInteger(Math.round(scaled))||Math.abs(scaled-Math.round(scaled))>1e-7)throw new Error('invalid_quantity');}
if(kind==='vehicles'){const duplicate=await db().prepare("SELECT id FROM records WHERE owner=? AND kind='vehicles' AND archived=0 AND json_extract(data,'$.registration')=? AND id!=?").bind(owner,data.registration,body.id??'').first();if(duplicate)throw new Error('duplicate_vehicle');}
if(kind==='missions'&&['planned','confirmed'].includes(data.status)&&data.time&&data.returnTime){const vehicle=await get(owner,data.vehicleId);if(vehicle.data.status!=='active')throw new Error('vehicle_unavailable');const overlap=await db().prepare("SELECT id FROM records WHERE owner=? AND kind='missions' AND archived=0 AND json_extract(data,'$.vehicleId')=? AND json_extract(data,'$.date')=? AND json_extract(data,'$.status') IN ('planned','confirmed') AND json_extract(data,'$.time') < ? AND json_extract(data,'$.returnTime') > ? AND id!=?").bind(owner,data.vehicleId,data.date,data.returnTime,data.time,body.id??'').first();if(overlap)throw new Error('vehicle_overlap');}
if(kind==='reservations'){const w=await get(owner,data.warehouse);data.agencyId=w.data.agencyId;const scaled=data.quantity*1000;if(!Number.isSafeInteger(Math.round(scaled))||Math.abs(scaled-Math.round(scaled))>1e-7)throw new Error('invalid_quantity');}
if(kind==='kitComponents'){if(data.kitId===data.componentId)throw new Error('recursive_kit');const cycle=await db().prepare("WITH RECURSIVE components(id) AS (SELECT ? UNION SELECT json_extract(r.data,'$.componentId') FROM records r JOIN components c ON json_extract(r.data,'$.kitId')=c.id WHERE r.owner=? AND r.kind='kitComponents' AND r.archived=0 AND json_extract(r.data,'$.status')='active' AND r.id!=?) SELECT id FROM components WHERE id=? LIMIT 1").bind(data.componentId,owner,body.id??'',data.kitId).first();if(cycle)throw new Error('recursive_kit');}
if(kind==='products'){const rows=await db().prepare("SELECT id FROM records WHERE owner=? AND kind='products' AND json_extract(data,'$.sku')=? AND archived=0 AND id!=?").bind(owner,data.sku,body.id??'').all();if(rows.results.length)throw new Error('duplicate_sku');}
if(kind==='effects'){const duplicate=await db().prepare("SELECT id FROM records WHERE owner=? AND kind='effects' AND archived=0 AND json_extract(data,'$.number')=? AND COALESCE(json_extract(data,'$.bank'),'')=? AND COALESCE(json_extract(data,'$.account'),'')=? AND id!=?").bind(owner,data.number,data.bank??'',data.account??'',body.id??'').first();if(duplicate)throw new Error('duplicate_effect');}
if(kind==='payroll'){const duplicate=await db().prepare("SELECT id FROM records WHERE owner=? AND kind='payroll' AND archived=0 AND json_extract(data,'$.employeeId')=? AND json_extract(data,'$.period')=? AND id!=?").bind(owner,data.employeeId,data.period,body.id??'').first();if(duplicate)throw new Error('duplicate_payslip');}
if(body.id){const old=await get(owner,body.id);assertRecord(ctx,old,true);if(old.kind!==kind||isLocked(old))throw new Error('immutable');if(old.revision!==body.revision)throw new Error('conflict');const result=await db().prepare('UPDATE records SET data=?,revision=revision+1,updated_at=? WHERE id=? AND owner=? AND revision=?').bind(JSON.stringify(data),new Date().toISOString(),body.id,owner,body.revision).run();if(!result.meta.changes)throw new Error('conflict');return Response.json({id:body.id});}
const id=typeof body.requestId==='string'&&/^[a-zA-Z0-9-]{8,80}$/.test(body.requestId)?body.requestId:newId();const exists=await db().prepare('SELECT owner,kind,data FROM records WHERE id=?').bind(id).first<{owner:string,kind:string,data:string}>();if(exists){if(exists.owner!==owner||exists.kind!==kind||exists.data!==JSON.stringify(data))throw new Error('idempotency_conflict');return Response.json({id});}await insert(owner,kind,id,data).run();return Response.json({id});}
if(action==='archive'){const old=await get(owner,body.id);assertRecord(ctx,old,true);if(isLocked(old))throw new Error('immutable');const linked=await db().prepare("SELECT id FROM records WHERE owner=? AND archived=0 AND id!=? AND EXISTS (SELECT 1 FROM json_tree(records.data) WHERE type='text' AND value=?) LIMIT 1").bind(owner,old.id,old.id).first();if(linked)throw new Error('record_in_use');const r=await db().prepare('UPDATE records SET archived=1,revision=revision+1,updated_at=? WHERE id=? AND owner=? AND revision=?').bind(new Date().toISOString(),old.id,owner,body.revision).run();if(!r.meta.changes)throw new Error('conflict');return Response.json({ok:true});}
if(action==='cancelPayment'){const old=await get(owner,body.id);assertRecord(ctx,old,true);if(old.revision!==body.revision)throw new Error('conflict');if(old.kind!=='payments'||old.data.status!=='cleared'||typeof body.reason!=='string'||!body.reason.trim())throw new Error('invalid_cancellation');return Response.json(await cancelPayment(ctx,old,body.reason));}
if(action==='schedule'){const inv=await get(owner,body.id);assertRecord(ctx,inv,true);assertModule(ctx,'installments',true);assertModule(ctx,'payments',true);if(inv.kind!=='invoices'||inv.data.status!=='issued'||inv.data.invoiceType==='creditNote')throw new Error('invalid_invoice');const exists=await db().prepare("SELECT id FROM records WHERE owner=? AND kind='installments' AND json_extract(data,'$.invoiceId')=?").bind(owner,inv.id).first();if(exists)throw new Error('schedule_exists');const deposit=body.deposit??0;if(!Number.isSafeInteger(deposit)||deposit<0||deposit>=inv.data.total)throw new Error('invalid_deposit');if(!/^\d{4}-\d{2}-\d{2}$/.test(body.firstDate)||new Date(body.firstDate+'T12:00:00Z').toISOString().slice(0,10)!==body.firstDate)throw new Error('invalid_date');const list=plan(inv.data.total-deposit,body.count,body.firstDate);const batch:D1PreparedStatement[]=[];const planId=inv.id+'-plan';batch.push(insert(owner,'plan_lock',planId,{invoiceId:inv.id}));const shared={agencyId:inv.data.agencyId,clientId:inv.data.clientId,...(inv.data.projectId?{projectId:inv.data.projectId}:{}),invoiceId:inv.id,status:'open'};if(deposit){const id=newId();batch.push(insert(owner,'installments',id,{...shared,name:`Acompte · ${inv.data.name}`,dueDate:new Date().toISOString().slice(0,10),amount:deposit}));batch.push(insert(owner,'payments',newId(),{name:`Acompte · ${inv.data.name}`,agencyId:inv.data.agencyId,clientId:inv.data.clientId,projectId:inv.data.projectId,installmentId:id,direction:'incoming',date:new Date().toISOString().slice(0,10),amount:deposit,method:body.method??'transfer',status:'cleared'}));}for(let i=0;i<list.length;i++)batch.push(insert(owner,'installments',newId(),{...shared,...list[i],name:`${inv.data.name} · ${i+1}/${list.length}`}));await db().batch(batch);return Response.json({count:list.length});}
if(action==='convert'){const quote=await get(owner,body.id);assertRecord(ctx,quote);assertModule(ctx,'invoices',true);if(quote.kind!=='quotes'||quote.data.status!=='accepted')throw new Error('quote_not_accepted');const id=quote.id+'-invoice';const exists=await db().prepare('SELECT id FROM records WHERE id=? AND owner=?').bind(id,owner).first();if(exists)return Response.json({id});const data=validate('invoices',{...quote.data,name:`FAC · ${quote.data.name}`,date:new Date().toISOString().slice(0,10),dueDate:body.dueDate??new Date().toISOString().slice(0,10),invoiceType:'invoice',status:'draft'});await insert(owner,'invoices',id,data,quote.demo).run();return Response.json({id});}
if(action==='transfer'){const product=await get(owner,body.productId);const from=await get(owner,body.from),to=await get(owner,body.to);assertModule(ctx,'movements',true);assertRecord(ctx,from);assertRecord(ctx,to);assertRecord(ctx,product);if(product.kind!=='products'||from.kind!=='warehouses'||to.kind!=='warehouses'||from.id===to.id||typeof body.quantity!=='number'||!Number.isFinite(body.quantity)||body.quantity<=0||!body.reason?.trim())throw new Error('invalid_transfer');const transferId=typeof body.requestId==='string'&&/^[a-zA-Z0-9-]{8,80}$/.test(body.requestId)?body.requestId:newId();const prior=await db().prepare('SELECT data FROM records WHERE id=? AND owner=?').bind(transferId+'-out',owner).first<{data:string}>();if(prior){const previous=JSON.parse(prior.data);const target=await db().prepare('SELECT data FROM records WHERE id=? AND owner=?').bind(transferId+'-in',owner).first<{data:string}>();if(!target||previous.productId!==product.id||previous.warehouse!==from.id||JSON.parse(target.data).warehouse!==to.id||previous.quantity!==body.quantity||previous.reason!==body.reason||previous.serials!==(body.serials??''))throw new Error('conflict');return Response.json({ok:true});}const serialList=String(body.serials||'').split(/\r?\n/).map((v:string)=>v.trim()).filter(Boolean);if(new Set(serialList).size!==serialList.length)throw new Error('duplicate_serial');if((product.data.tracking==='serialTracking'||serialList.length>0)&&(!Number.isInteger(body.quantity)||serialList.length!==body.quantity))throw new Error('serial_count');const common={serialList,serials:body.serials??'',unitCost:product.data.purchasePrice||0,productId:product.id,quantity:body.quantity,date:new Date().toISOString().slice(0,10),reason:body.reason,transferId,status:'posted'};await db().batch([insert(owner,'movements',transferId+'-out',{...common,name:`Transfert · ${product.data.name}`,direction:'stockOut',warehouse:from.id,agencyId:from.data.agencyId}),insert(owner,'movements',transferId+'-in',{...common,name:`Transfert · ${product.data.name}`,direction:'stockIn',warehouse:to.id,agencyId:to.data.agencyId})]);return Response.json({ok:true});}
if(action==='company'){assertAdmin(ctx);const data:Record<string,any>={};for(const key of ['name','address','phone','taxId','bank','email','printX','printY']){if(body.data[key]!==undefined){if(typeof body.data[key]!=='string'||body.data[key].length>500)throw new Error('invalid_company');data[key]=body.data[key];}}await db().prepare('INSERT INTO company(owner,data) VALUES(?,?) ON CONFLICT(owner) DO UPDATE SET data=excluded.data').bind(owner,JSON.stringify(data)).run();return Response.json({ok:true});}
if(action==='demo'){assertAdmin(ctx);const exists=await db().prepare('SELECT id FROM records WHERE owner=? AND demo=1 LIMIT 1').bind(owner).first();if(exists)throw new Error('demo_exists');const prefix=owner+'-';const entries=demoEntries();const mapped=entries.map(e=>{const d={...e.data};for(const [k,v] of Object.entries(d))if(typeof v==='string'&&v.startsWith('demo-'))d[k]=prefix+v;return insert(owner,e.kind,prefix+e.id,d,1)});await db().batch(mapped);return Response.json({ok:true});}
throw new Error('invalid_action');}catch(e){return failure(e);}}
